### ISSUE TITLE
Cost of disabling permessage-deflate to relieve native memory pressure

### ISSUE THREAD

**Issue by rameshmurthy** [cometd/cometd#1001]
Hi All,

This is a question, not an issue, I was unable to add label.

We are using cometd 3.4 with tomcat 8.5.47, Java 8. Recently we were seeing lot of nodes getting restarted because of insufficient memory. Our nodes are configured for 4 GB of Total Memory (Heap, Metaspace, Native). Those nodes seem to be under native memory pressure. After doing some analysis, It appears that the native memory pressure is caused by the number of WebSocket connections. It appears that by default tomcat adds "permessage-deflate" extension. And each WebSocket connection seem to have an instance of PerMessageDeflate object, which intern has an instance of a Deflater object. Specifically when we do a data center fail over or load balancer fail over all the clients will get disconnect and reconnect, which will cause flood or requests and will put pressure on native memory.

Since each Deflater object is creating native memory buffers we seem to be running into this issue. As a quick test, we wrote a simple test which creates 5000 Deflater objects. It increases process memory to ~1G. i.e. If we have 5000 WebSocket connections, that is 1G.

```java
import java.io.IOException;
import java.util.zip.Deflater;
public class DeflatorTest {
   public static void main(String[] args) throws IOException {
      String content = "blahblahblah";
      byte[] input = content.getBytes("UTF-8");
      System.out.println("Test size = " + 5000);
      for (int i = 0; i < 5000; i++) {
         byte[] output = new byte[500];
         Deflater deflater = new Deflater(-1, true);
      }
      System.out.println("Done");
      //Let it run for a while so I can monitor the java process.
      try {
         Thread.sleep(60 * 60 * 1000);
      } catch (InterruptedException ex) {
      }
   }
}
```

So we are exploring disabling "permessage-deflate" extension. Although it could increase network overhead, it should help with native memory and CPU cycles. 

Details about our set-up:
-------------------------
1. Cometd 3.4
2. Tomcat 8.5.47
3. Currently Java 8, will move soon to Java 11
4. WebSocketTransport
5. Message format is JSON
6. 1500 to 2000 active web socket connections per node.
7. maxMessageSize /MAX_BUFFER_SIZE is 8192

Any help with following questions is highly appreciated:

1. What is the cost of disabling pemessage-deflate? I see benefits from memory and CPU cycles. Not sure about the cost.
2. Below what size permessage-deflate wont make sense? I mean if we are not sending 10KB of messages does it make senses to use permessage-deflate? Here 10KB is an example. We are sending JSON. No binary data.
3. What is the cost on Network?
4. Dose it slow down to write messages on socket as compression is disabled? (If i disable permessage-deflate)
5. Currently from client If I send a message that is greater than 8192 characters, server is disconnecting the client. I did the test with and without permessage-deflate. This confused me a lot. If i think the browser is compressing the message, I should be able to send more than 8192 characters to server when permessage-deflate is enabled. But thats not happening. The client is disconnected by server when ever I send a message that is greater than 8192 characters irrespective of permessage-deflate enabled or disabled. This makes me think, the limit on maxMessageSize doesnot consider compression. It seems to take into consideration of actual message size. Is this right or wrong?

Excuse me for posting a long question any help is highly appreciated. Thanks in advance.

**Comment by sbordet** [comment]
> 1. What is the cost of disabling pemessage-deflate? I see benefits from memory and CPU cycles. Not sure about the cost.

You have to measure yourself, it depends on the size of the messages, how compressible they are, etc.
Typically, in a WAN deployment, the savings in less packets being sent to possibly slow clients are worth the additional CPU.
Same answer for 2., 3., 4., you have to measure your case, there is no answer that fits all. You trade more CPU for more bytes sent over the network and typically more system calls to do so.

> 5. This makes me think, the limit on maxMessageSize doesnot consider compression.

That is correct. The limit is applied by CometD to the WebSocket implementation, which for Tomcat I believe applies to the uncompressed message (it certainly does for Jetty).

**Comment by lachlan-roberts** [comment]
See these JDK bugs related to excessive memory consumption from Inflaters and Deflaters:
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4797189
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6293787

You could be experiencing excessive memory consumption due to these. I know in Jetty we had to write Inflater and Deflater Pools to recycle these in an attempt to avoid these memory issues, but I'm not sure if tomcat is doing something similar.

**Comment by rameshmurthy** [comment]
Thank you so much for your responses. Excuse me for late reply. I was busy with escalations.

As such tomcat is closing the inflaters and deflaters on close of the session. I mean thee is no memory leak as such, which we thought when the issue happened.

https://github.com/apache/tomcat/blob/f8fde70263fd9e5a087cf57df9af34f5e77342fb/java/org/apache/tomcat/websocket/WsRemoteEndpointImplBase.java#L738

I am also suspecting memory defragmentation  due to the nature of WebSocketConnections in our environment (clients come and go in our environment, they close the tab, open a tab, reload a page etc).

Having an object pool definitely  helps.

Currently, we are having multiple nodes getting restarted due to native memory pressure. Disabling of permessage-deflate is one of the option I am considering. I am also considering an option to restrict number of connections that can have permessage-deflate vs non permessage-deflate at a time on the system. I dont want to do these changes without understanding the cost of disabling it. 

If you have any suggestions on how to investigate further to measure the impact of disabling of permessage-deflate please share. In your experience has any customer did it and had a negative affect please let me know.

Thank you once again for the help. I really appreciate. I am working on a load test based on message sizes.
I will monitor memory, cpu and rate of sending of messages. I am looking how to measure the cost on network.


Thanks.

**Comment by sbordet** [comment]
> If you have any suggestions on how to investigate further to measure the impact of disabling of permessage-deflate please share.

You can disable the WebSocket extension as documented here: https://docs.cometd.org/current5/reference/#_java_server_configuration_transports
Search for `ws.enableExtension`.

> I am working on a load test based on message sizes.

Please don't write your own, but use CometD's as documented here:
https://docs.cometd.org/current5/reference/#_benchmarking

Or at least start from CometD's benchmark if you really need to write a custom one.
Also please read this blog for general advices about how to benchmark: https://webtide.com/introducing-jetty-load-generator/

**Comment by rameshmurthy** [comment]
> > If you have any suggestions on how to investigate further to measure the impact of disabling of permessage-deflate please share.
> 
> You can disable the WebSocket extension as documented here: https://docs.cometd.org/current5/reference/#_java_server_configuration_transports
> Search for `ws.enableExtension`.
> 

We made a custom implementation to seed configuration into system at run time. Currently the configuration is present in web.xml, we have implemented to bring that into a properties which live in our case database/properties file. With this change we were able to enable and disable permessage-deflate extension.

> > I am working on a load test based on message sizes.
> 
> Please don't write your own, but use CometD's as documented here:
> https://docs.cometd.org/current5/reference/#_benchmarking
> 
> Or at least start from CometD's benchmark if you really need to write a custom one.
> Also please read this blog for general advices about how to benchmark: https://webtide.com/introducing-jetty-load-generator/

Thank you on the load test suggestion.

**Comment by sbordet** [comment]
Closing as answered.
