### ISSUE TITLE
Bayeuxclient disconnections 

### ISSUE THREAD

**Issue by devPrvn** [cometd/cometd#1010]
I'm implementing Bayeuxclient(long-polling) for cometD connections for asynchronous messaging. Intermittently I receive a disconnect message out of the blue ( I haven't found any exception either in server or application logs) and try reconnecting. I believe some unknown latency is causing the issue (I'm not 100% sure). 

Can you please suggest how I can workaround the issue ? By moving from long-polling to websockets can we have better performance ?

**Comment by sbordet** [comment]
> I'm implementing Bayeuxclient(long-polling) for cometD connections for asynchronous messaging.

Why you need to implement this? We have Java, JavaScript and NodeJS support. Is it some other language?

> Intermittently I receive a disconnect message out of the blue ( I haven't found any exception either in server or application logs) and try reconnecting. I believe some unknown latency is causing the issue (I'm not 100% sure).

We need to understand what's causing this. 
A CometD server will idle timeout when the client does not long-poll, so it may well be a mistake in your implementation.

We need server DEBUG logs to diagnose this further.

**Comment by devPrvn** [comment]
The project is created in c#.

**Comment by sbordet** [comment]
The client is in C#, and the server is the standard Java CometD server?

**Comment by devPrvn** [comment]
Yes.

**Comment by sbordet** [comment]
So, server DEBUG logs? Attach them to this issue.

**Comment by devPrvn** [comment]
I can't share the debug logs however can you share the best practice or code snippets to avoid the idle timeouts disconnects ? By any chance, can we use websockets instead of long-polling?

**Comment by sbordet** [comment]
I don't understand. I am asking for the CometD server logs -- if what you're doing is to implement the Bayeux protocol in a .NET client, then everything is already public: the Bayeux protocol and the CometD Java server with the logs it prints.

> however can you share the best practice or code snippets to avoid the idle timeouts disconnects

There is not much that I can say. An idle timeout is an idle timeout, you don't avoid them.
This is basic network programming, you want to refer to tutorials online.

Unfortunately you have given zero information to help you: no configuration, no code, no diagrams of your system, nothing -- there is not much that I can say if you don't provide additional information, sorry.

**Comment by sbordet** [comment]
Closing as no further information was provided.
