### ISSUE TITLE
Cannot handle errors in websocket connection

### ISSUE THREAD

**Issue by boris-petrov** [cometd/cometd#1016]
[Here](https://github.com/cometd/cometd/blob/3.1.14/cometd-javascript/common/src/main/webapp/js/cometd/cometd.js#L942) a websocket connection is made and [here](https://github.com/cometd/cometd/blob/3.1.14/cometd-javascript/common/src/main/webapp/js/cometd/cometd.js#L1003) an error-handler is registered. However, I, as a `cometd` user, cannot handle the error myself. For example, I would like to show a popup notification that something is wrong. It would be nice if `cometd` adds support for that.

**Comment by sbordet** [comment]
@boris-petrov you should be able to get notification of network errors due to failing `/meta/connect` messages.
Have you tried registering a listener to `/meta/connect` and looking for `message.successful === false`?

**Comment by boris-petrov** [comment]
@sbordet - you're right, I didn't think about that. Thank you!
