### ISSUE TITLE
Update UMD to better support ecma6

### ISSUE THREAD

**Issue by jmcc0nn3ll** [cometd/cometd#1020]
I have been dealing with errors in chrome and firefox recently while blending normal cometd.js and ReloadExtension.js in with my ecma6 module based application.  Mostly object not found errors for org.cometd when trying to assign the CometD object to a cometd variable.

`
let cometd = new org.cometd.CometD();
`
The browser would complain about the 'org' not being defined, whist IntelliJ shows the contents of the .cometd. portion on mouse over. Simply removing the org simply makes 'cometd' go undefined, etc etc.

Anyway, looking around I saw different components of UMD for other environments and hit upon one that removes the error from the browser javascript console.

```
// Globals.
root.org = root.org || {};
root.org.cometd = factory();
root["org.cometd"] = factory();  <--- added this.
```

I added that line to cometd.js and the following to ReloadExtension.js
```
else {
  factory(root.org.cometd);
  root["org.cometd"] = factory(root); <--- added this.
}
```

I know this works in my situation but I have no idea if it is broadly useful, that would be your call!

**Comment by sbordet** [comment]
@jmcc0nn3ll your way is equivalent to the existing way, but will break existing code that is relying on the `org.cometd` object.
