### ISSUE TITLE
TypeScript custom transports

### ISSUE THREAD

**Issue by fergardi** [cometd/cometd#1057]
Hello everyone.

We are currently migrating an old VueJS project which uses JS into a more modern TS one.

Back in the day we developed our own set of transports, based on the already existing ones:

- WebSocketTransport
- LongPollingTransport
- CallbackPollingTransport

But now, with the new [TypeScript definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cometd/index.d.ts) those transports no longer exist or they are not yet typed, so we cannot use or extend them anymore in Typescript.

I'm using the 7.0.2 javascript client version along with the 4.0.9 (latest) definition types. Maybe there is the mismatch? Anybody can help me here?

Thanks.

**Comment by sbordet** [comment]
The CometD project is not the author of the TypeScript definitions you have linked, so you have to ask to that project.

However, a client recently sponsored the TypeScript definitions, so we are working on it.
See #1058.

**Comment by sbordet** [comment]
Closing as implemented in #1058.
