### ISSUE TITLE
Session using the WebSocket transports may be leaked

### ISSUE THREAD

**Issue by sbordet** [cometd/cometd#1134]
**CometD version(s)**
5.0.10

**Description**
CometD sessions that use the WebSocket transports may be leaked in the following scenario:
- a client sends a `/meta/connect` message which is suspended
- large message(s) are published and cause TCP congestion because the client does not read (e.g. it is vanished)
- the `/meta/connect` timeout elapses and queues the `/meta/connect` reply, which is not processed because there is a pending write for the large messages
- the idle timeout fires, which should fail all writes (pending and enqueued), but only fails the pending one
- because the `/meta/connect` reply is not failed, the correspondent session remains with `_expireTime=0`, which prevents sweeping the session, which remains in memory.

Note that this scenario does not happen with the ack extension, because messages are only written in the context of a `/meta/connect` reply.
It also does not happen with HTTP transports because they either write messages in the context of a `/meta/connect` reply, or write them on a different connection (so that the `/meta/connect` reply may fail separately).

**Comment by sbordet** [comment]
See initial discussion that triggered the investigation in #1132.

**Comment by maykov** [comment]
Still seeing this happening. Will work on exact repro steps.
