### ISSUE TITLE
Memory churn and regex pattern use?

### ISSUE THREAD

**Issue by dgormansn** [cometd/cometd#1158]
CometD version 3.1

In the resolve(string) method in org.cometd.bayeux.Channeld, a pattern is being recreated each time by doing `segment.matches(VAR.pattern())`, instead of using a pre-compiled pattern.  This is creating unnecessary memory churn as this method is called **alot**.  It appears to have remained that way in subsequent versions.  Is there a reason for this?

**Comment by sbordet** [comment]
Good catch, no reason to not optimize this.
Care to issue a pull request? Please follow the [contribution guidelines](https://github.com/cometd/cometd/blob/5.0.x/CONTRIBUTING.md).

**Comment by sbordet** [comment]
Fixed by #1165.
