### ISSUE TITLE
Where can we find the jars related to cometd?

### ISSUE THREAD

**Issue by inspire99** [cometd/cometd#1168]
CometD version(s) --> 7.0.6

**Java version & vendor** `(use: java -version)` -- java version 11

Question:

I tried to get the jars from maven repository, for 7.0.6, 

from https://repo1.maven.org/maven2/org/cometd/java/cometd-java-client/7.0.6/

But did not find any jar file.

Even I downloaded cometd distribution from https://download.cometd.org/

But, still did not find jar file.

Could someone point me to jar file ?

Thank you.

**Comment by sbordet** [comment]
`cometd-java-client` is a parent module, so it does not have any jar.

If you are upgrading from older CometD releases, please read the [migration guides](https://docs.cometd.org/current/reference/#_migration), in particular [this section](https://docs.cometd.org/current/reference/#_migration_40_to_50).

**Comment by inspire99** [comment]
I have built few components locally, using maven.
it has generated below jars.

I believe , this is the right way, to generate jars and use. Since I don't find them available in maven repository as well.

- cometd-java-annotation-client-7.0.6.jar
- 
- cometd-java-annotation-common-7.0.6.jar
- 
- cometd-java-api-client-7.0.6.jar
- 
- cometd-java-api-common-7.0.6.jar
- 
- cometd-java-client-common-7.0.6.jar
- 
- cometd-java-client-http-common-7.0.6.jar
- 
- cometd-java-client-http-jetty-7.0.6.jar
- 
- cometd-java-common-7.0.6.jar

**Comment by sbordet** [comment]
All the jars above are in Maven Central.

**Comment by inspire99** [comment]
In the distribution, I could find the jars. 
inside the target folder, under each maven module.


https://download.cometd.org/ 

We can close this issue.
