### ISSUE TITLE
What is the End of Life for cometd 5.0.x ?

### ISSUE THREAD

**Issue by inspire99** [cometd/cometd#1176]
**CometD version(s)** Cometd 5.0.x

**Java version & vendor** `(use: java -version)` Java 8

**Question** We are evaluating to upgrade to cometd 5.0.x. We would like to know about the supportability timeline for 5.0.x.

As I checked cometd reference table, as of now, it shows 'Stable' for 5.0.x. End of life for lower versions.

Just curious, would it reach 'End of Life' in next 6 months ? As we are based on Java8 runtime.

**Comment by sbordet** [comment]
CometD 5.0.x is based on Jetty 9.4.x, so their lifetimes are somehow linked.

Jetty 9.4.x is currently in maintenance mode where we don't develop new features unless for Webtide customers.

CometD typically follows Jetty with perhaps a little more delay (in the sense that we may develop features a little longer on CometD than in Jetty).

Having said that, we recommend to move away from Java 8 (current Java version is at 18, and there are 2 more recent "LTS" releases 11 and 17, with the next LTS, Java 21, coming in a little more than 1 year).

I recommend that if you are upgrading CometD from a version older than 5, you upgrade directly to CometD 7 and Java 17.

We are supporting customers in these migrations, see our [commercial support](https://docs.cometd.org/current/reference/#_support).

**Comment by inspire99** [comment]
@sbordet , a related doubt:

Is cometd 5.0.x compatible with Java 11 runtime ?

**Comment by sbordet** [comment]
> Is cometd 5.0.x compatible with Java 11 runtime ?

Yes, CometD 5 is built with Java 8, Java 11 and Java 17: https://github.com/cometd/cometd/actions/runs/2208267323.

**Comment by inspire99** [comment]
@sbordet : 

We understand that, cometd release cycle is closely linked with jetty release cycle.

We would like to know, what is your official stand on 'End of Life' for cometd 5.0.x ?

**Comment by sbordet** [comment]
@inspire99 we had internal discussions and we will come out, today or Monday, with an official statement.
Thanks for pushing this issue by asking clarifications, it helped us clarify as well.

**Comment by inspire99** [comment]
@sbordet , Sure, looking forward to your reply.

**Comment by sbordet** [comment]
@inspire99 the announcement has been made, see #1179.
