### ISSUE TITLE
Announcement of End of Community Support for CometD 5.0.x

### ISSUE THREAD

**Issue by sbordet** [cometd/cometd#1179]
The CometD project announces the **End of Community Support for CometD 5.0.x**, following [Jetty's announcement of End of Community Support for Jetty 9.x](https://github.com/eclipse/jetty.project/issues/7958).

September 1st, 2022 will mark the official **End of Community Support** for CometD 5.0.x.

While users of CometD 5.0.x will continue to see releases for security and critical issues until CometD 5.0.x goes **End of Life**, the only ongoing support provided will be for Webtide customers.

As for the official **End of Life** of CometD 5.0.x, we will give at least 6 months notice after the last Webtide customer has transitioned off of using CometD 5.0.x. We can’t provide a firm date, but it is unlikely to happen before 2025. 

Thank you for your continued usage and support of CometD.  
Please take a moment to look at the newer CometD releases 6.0.x and 7.0.x.

Action | Before September 1st, 2022 | End of Community Support (September 1st, 2022) | End of Life (Date TBD)
--- | --- | --- | ---
Community PRs reviewed and integrated | :heavy_check_mark: | :x: | :x: 
Webtide Customer PRs reviewed and integrated | :heavy_check_mark: | :heavy_check_mark: | :x:
Community triggered releases | :heavy_check_mark: | :x: | :x:
Webtide Customer triggered releases | :heavy_check_mark: | :heavy_check_mark:  | :x:
Security / Vulnerability triggered releases | :heavy_check_mark: | :heavy_check_mark: | :x:

**Comment by inspire99** [comment]
@sbordet , The link regarding eclipse jetty project seems to be incorrect.

Incorrect link --> https://github.com/cometd/cometd/issues/eclipse/jetty.project#7958

Was this the intended link --> https://github.com/eclipse/jetty.project/issues/7958 ?

**Comment by sbordet** [comment]
@inspire99 thanks, fixed the link.

**Comment by inspire99** [comment]
@sbordet , Regarding cometd 7.0.x, I have seen build jobs for Java 11, Java 17.

https://github.com/cometd/cometd/actions/runs/2108532674

I would like to know whether cometd 7.0.x is backward compatible with Java 8 runtime ?

Thank you.

**Comment by sbordet** [comment]
@inspire99 no, CometD 7.0.x requires Java 11, see https://github.com/cometd/cometd/blob/7.0.x/README.md.
