### ISSUE TITLE
ReloadExtension and requireHandshakePerConnection parameter

### ISSUE THREAD

**Issue by mtgemo** [cometd/cometd#1209]
**CometD version(s)**  3.1.4

**Java version & vendor** `(use: java -version)` Java version: 1.8.0_292, vendor: AdoptOpenJDK

**Question**
Hello, 
I want to confirm if `requireHandshakePerConnection` parameter needs to be set to **_false_** for `ReloadExtention` to work. That's the behavior I'm seeing. 
When `requireHandshakePerConnection` is true, I'm getting 
`[{"advice":{"interval":0,"reconnect":"handshake"},"channel":"/meta/connect","id":"2","error":"402::Unknown client","successful":false}]` 
Therefore, re-handshake is forced and ReloadExtension doesn't succeed.

**Comment by sbordet** [comment]
That is correct.
