### ISSUE TITLE
CometD client (BayeuxClient) state

### ISSUE THREAD

**Issue by dyutiman** [cometd/cometd#1246]
CometD: 7.0.6

java -version
openjdk version "11.0.15" 2022-04-19 LTS
OpenJDK Runtime Environment Zulu11.56+19-CA (build 11.0.15+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.56+19-CA (build 11.0.15+10-LTS, mixed mode)

Hi,

I was checking the BayeuxClient state in different error scenarios. 

When I have error in /meta/connect channel the BayeuxClient returns the following states:

```json
{"clientId":"*****","advice":{"reconnect":"none","interval":0},"channel":"/meta/connect","id":"7","error":"400::Authenticated user id does not match the session's user id","successful":false}
```

CLIENT STATE **isHandshook=false, isConnected=false, isDisconnected=true**

Here we are doing a re-handshake, which fails with TimeoutException because of some local environment issue. We receive the error on /meta/handshake channel

```json
{"failure":{"exception":"java.util.concurrent.TimeoutException: Network delay expired: 30000 ms","message":{"ext":{"replay":true},"supportedConnectionTypes":["long-polling"],"channel":"/meta/handshake","id":"8","version":"1.0"}},"channel":"/meta/handshake","id":"8","successful":false} 
```

This time the BayeuxClient client state is returned as follows:
CLIENT STATE **isHandshook=false, isConnected=false, isDisconnected=false**

This is kind of a state we are not able to make any decision on. I believe the client is doing the re-handshake internally. But if we want to take the control then we need to have a definite state as if the client is already disconnected or not.

Can I request an explanation here? If the client is re-handshaking in the background we need to know that. Also, we need to know in what scenarios the client does the re-handshake on its own.

thanks

**Comment by sbordet** [comment]
In the first message, you have: `"advice":{"reconnect":"none"}`, which is telling the client that it should not reconnect.

In the second message, the advice is absent, which by default indicates to the client that it should retry to connect.

See https://docs.cometd.org/current/reference/#_reconnect_advice_field.

You should not be looking at the internal state of the client, but just at the messages.

**Comment by dyutiman** [comment]
Thanks for the reply. 

So to summarise, 

 - If advice is **missing**, the Bayeux client tries to reconnect internally. It starts from the /meta/handshake call.
 - If reconnect is **retry**, the Bayeux client tries to reconnect internally and it tries the /meta/connect call only.
 - If reconnect is **handshake** the Bayeux client starts from the /meta/handshake.
 - If reconnect is **none**, the Bayeux client stops
 
Please let me know if above statements are correct.

- thanks

**Comment by sbordet** [comment]
* if the `advice` is missing, it is assumed be `advice: { reconnect: "retry" }`
* if `reconnect: "retry`, the client retries on `/meta/connect`. If the server communicates in the advice also the `maxInterval`, the client retries on `/meta/connect` until `maxInterval + maxNetworkDelay`, then switches to `/meta/handshake`.  The idea here is that if `maxInterval` expires, the server would have expired the session, so retrying on `/meta/handshake` would yield faster reconnects -- it's just a small optimization.

Your last 2 bullets are correct.

**Comment by dyutiman** [comment]
Thanks a lot for clarifying!

**Comment by dyutiman** [comment]
Hi,

Just to clarify one more thing in this context. Are the above statesments true for all the meta channels or just for /meta/connect?

If the /meta/handshake fails, CometD will try to reconnect based on the advice field in message received in /meta/handshake channel?


I saw a use case here with Salesforce. The /meta/subscribe fails:
```json
{"clientId":"****","channel":"/meta/subscribe","id":"18","subscription":"/topic/AccountUpdates51","error":"400::The replayId {67} you provided was invalid.  Please provide a valid ID, -2 to replay all events, or -1 to replay only new events.","successful":false}
```

But, /meta/connect receives:
```json
{"clientId":"****","advice":{"reconnect":"retry","interval":0,"timeout":110000},"channel":"/meta/connect","id":"19","successful":true}
```

And after 110 seconds the /meta/connect receives:
```json
{"clientId":"****","channel":"/meta/connect","id":"20","successful":true}
```

So here the /meta/connect is success, but the /meta/subscribe fails. In such case the CometD does not start from /meta/handshake.

**Comment by sbordet** [comment]
Only `/meta/handshake` and `/meta/connect` messages may have the `advice` field.

The subscription is failed due to application logic, not because of connectivity issues, so there is no reason to reconnect or rehandshake.

**Comment by dyutiman** [comment]
Yes, I agrre that the subscription may fail because of application logic and not because of connectivity issue. But if subscription fails, ideally the client should fail too. Isn't it? There is no point of the client being connected but not receiving any message.

Please let me know if I am thinking this right.

- thanks

**Comment by sbordet** [comment]
> But if subscription fails, ideally the client should fail too. Isn't it? There is no point of the client being connected but not receiving any message.

No.

The client can look at the subscription failure, and decide to report something to the end user, for example.

That one subscription failed does not mean that the others don't work.

Imagine you can subscribe to `/userChat` but you cannot subscribe to `/adminChat` because you're not an admin.
You still want to receive the `/userChat` messages so it's perfectly fine to remain connected.
