### ISSUE TITLE
java.util.concurrent.TimeoutException: Network delay expired: 30000

### ISSUE THREAD

**Issue by dyutiman** [cometd/cometd#1249]
CometD: 7.0.6

java -version
openjdk version "11.0.15" 2022-04-19 LTS
OpenJDK Runtime Environment Zulu11.56+19-CA (build 11.0.15+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.56+19-CA (build 11.0.15+10-LTS, mixed mode)

Hi,

We are the CometD client here and the server is Salesforce. Once in a while we are receiving disconnect message from the server due to authentication error. In one thread, on /meta/disconnect channel we are receiving
```json
{"channel":"/meta/disconnect"}
```

Then in the same thread on /meta/connect channel we are receiving
```json
{"clientId":"***","advice":{"reconnect":"none","interval":0},"channel":"/meta/connect","id":"7","error":"400::Authenticated user id does not match the session's user id","successful":false}
```

Then in the same thread we are fixing this authorization issue and trigerring a handshake. This handshake is failing with TimeoutException after 30 seconds. So in /meta/handshake we are receiving 
```json
{"failure":{"exception":"java.util.concurrent.TimeoutException: Network delay expired: 30000 ms","message":{"ext":{"replay":true},"supportedConnectionTypes":["long-polling"],"channel":"/meta/handshake","id":"8","version":"1.0"},"connectionType":"long-polling"},"channel":"/meta/handshake","id":"8","successful":false}
```

Just after this the Bayeux client is re-initiating the handshake and that comes as success
```json
{"ext":{"replay":true,"payload.format":true},"minimumVersion":"1.0","clientId":"***","supportedConnectionTypes":["long-polling"],"channel":"/meta/handshake","id":"9","version":"1.0","successful":true}
```

We are not getting any clue why this TimeoutException is happening. This is happening every time we are receiving the disconnect message and then in the same thread we are doing handshake again.

How to reproduce: After the Bayeux client is successfully subscribed, delete the session from the server.  After some time the disconnect message will be received and then re-initiate the handshake.

Any help or clue here will be appriciated.

- thanks

**Comment by sbordet** [comment]
This looks like a server problem, so not much that this project can do, as there could be many reasons this is happening (from application reasons to infrastructure reasons) that are outside control.

**Comment by dyutiman** [comment]
Thanks for taking a look at this. I was also thinking the same, but wanted to check from CometD's perspective too. I was guessing maybe something is going on at the Jetty layer, that the thread is held for some reason.

I was also wondering where from this 30 seconds value is coming. Anyway, I will try to explore it in more details with some use cases.
Thanks for your help.

**Comment by dyutiman** [comment]
After receiving error via onMessage(), I was resubscribing in the same thread (Jetty thread). In the same thread I was waiting for the subscription to success or fail.
This waiting on a Jetty thread was causing the TimeoutException. When I moved the resubscribing call to a different thread, the issue is resolved.
