### ISSUE TITLE
Typescript definition issue for Extension interface

### ISSUE THREAD

**Issue by paustint** [cometd/cometd#1324]
**CometD version(s)**
`^7.0.4`

**Java version & vendor** (use: `java -version`)
Not sure - a 3rd party (Salesforce) owns and operates the server.

**Description**
_Do not report security issues here!_
Typescript type definitions for `Extension` appear to have an invalid return type.

**How to reproduce?**

I don't know if I am "holding it wrong", but when I return `null` from `outgoing` it causes the handshake to fail and the subscription and the remaining initialization does not seem to work - nothing happens and there is no error messages, but the subscription does not work.

If I omit the return for the handshake message in the `outgoing` function then the handshake is successful and the subscription works.

Here is the fix that should be applied:

```diff
export interface Extension {
-    incoming?(message: Message): Message | null;
+    incoming?(message: Message): Message | null | undefined;

 -   outgoing?(message: Message): Message | null;
+    outgoing?(message: Message): Message | null | undefined;
}
```

```typescript
class CometdReplayExtension implements Extension {
  static EXT_NAME = 'replay-extension';
  static REPLAY_FROM_KEY = 'replay';
  cometd: CometD;
  extensionEnabled = true;
  replayFromMap: MapOf<number | undefined> = {};

  setEnabled(extensionEnabled: boolean) {
    this.extensionEnabled = extensionEnabled;
  }

  addChannel(channel: string, replay?: number) {
    channel = channel.startsWith('/event') ? channel : `/event/${channel}`;
    this.replayFromMap[channel] = replay ?? -1;
  }

  removeChannel(channel: string) {
    channel = channel.startsWith('/event') ? channel : `/event/${channel}`;
    this.replayFromMap[channel] = undefined;
  }

  registered(name: string, cometd: CometD) {
    this.cometd = cometd;
  }

  incoming(message: Message) {
    if (isNumber(this.replayFromMap[message.channel]) && message.data?.event?.replayId) {
      this.replayFromMap[message.channel] = message.data.event.replayId;
      return message;
    }
    // return null; // <-- not sure if retuning null has any adverse affects or not
  }

  outgoing(message: Message) {
    if (message.channel === '/meta/subscribe') {
      if (this.extensionEnabled) {
        if (!message.ext) {
          message.ext = {};
        }
        message.ext[CometdReplayExtension.REPLAY_FROM_KEY] = this.replayFromMap;
      }
      return message;
    }
    // return null; // <---- RETUNING NULL CAUSES INIT TO FAIL SILENTLY, BUT IS REQUIRED BASED ON TYPE
  }
}
```

**Comment by sbordet** [comment]
Returning `null` from `Extension.incoming()` or `Extension.outgoing()` means that the extension wanted the message to be "deleted", i.e. not processed at all (as if it was not received).

Conversely, in JavaScript, returning `undefined` is equivalent to returning the `message` parameter.

The above is documented here: https://docs.cometd.org/current7/reference/#_extensions_writing

Given the above, I think the TypeScript type definitions are correct, although stricter than plain JavaScript (because in TypeScript you cannot return `undefined` so you have to explicitly return the `message`).

**Comment by paustint** [comment]
While I think they types should be updated so that the types match what is included in the docs (allowing no return aka return undefined), **THANK YOU** for explaining how this works and pointing to the docs which I likely overlooked. I confirmed that returning the message works beautifully.
