### ISSUE TITLE
Received message are still being processed after disconnect

### ISSUE THREAD

**Issue by dyutiman** [cometd/cometd#1373]
CometD version(s): 7.0.6

C:\Users\dyc>java -version
openjdk version "11.0.15" 2022-04-19 LTS
OpenJDK Runtime Environment Zulu11.56+19-CA (build 11.0.15+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.56+19-CA (build 11.0.15+10-LTS, mixed mode)

Let's say there was an event burst and the CometD received 1K events together. While these events are being processed sequentially, a disconnet() call is made.

What we observed is even when CometD client is disconnected, those receive events are still being processed. Is there a way to stop the processing as soon as the client is disconnected?

**Comment by sbordet** [comment]
If the messages have been fully received, they will be processed by CometD.

If you want to stop the processing of already received messages, you can just ignore them, and you do this in your application.

You want to do this on the client or on the server?

**Comment by dyutiman** [comment]
I want to do this on the client side.

We keep track of the event id we process and in the next subscription we used the last processed event id to begin. Here as the events are still in process even after we disconnect the client, the next immediate subscription is picking an intermiddiate event id (among those which are being processed).
This is causing duplicate event processing.

**Comment by sbordet** [comment]
@dyutiman what you describe is custom application logic that you have to implement yourself.

From the CometD point of view, the messages have been received and they will be processed. 
Whether some of them contain an application-specific "event id", CometD cannot know and won't know what it means, so you have to implement your own logic.

**Comment by dyutiman** [comment]
Thanks for the reply @sbordet 

Yes I agree that it is application specific. I just wanted to check if there is any way available that when I disconnect the client the background Jetty thread which received all the events can be interrupted.

**Comment by sbordet** [comment]
You can do this with a client extension, something like this:

```java
bayeuxClient.addExtension(new Extension() {
  boolean rcv(ClientSession session, Message.Mutable message) {
    if (bayeuxClient.isDisconnected()) {
      // Drop the message.
      return false;
    }
    return true;
  }
});
```

**Comment by dyutiman** [comment]
This is great. Thanks a lot! Let me try this out and confirm.

**Comment by sbordet** [comment]
Does it work for you?

**Comment by dyutiman** [comment]
I will update here once we try this.

**Comment by dyutiman** [comment]
It seems like working!!

Thank you so much @sbordet
