### ISSUE TITLE
When is JakartaEE 10 compatible version release planned for cometd ?

### ISSUE THREAD

**Issue by softwareagsw** [cometd/cometd#1429]
**CometD version(s)** Currently, we are referring to cometd 7, which is based on Jakarta EE 9. But, we are looking for Jakarta EE 10 compatible cometd ( as well as jetty )

**Java version & vendor** `(use: java -version)` Java 17 

**Question** When is JakartaEE 10 compatible version release planned for cometd ?

As I can follow through, this is being planned with cometd 8.x - https://github.com/cometd/cometd/tree/8.0.x - just curious about the timeline. thanks.

**Comment by sbordet** [comment]
The release of Jetty 12 is probably going to be in the June/July timeframe.
CometD 8 will follow, but we need to do a little more work on it, so I'd say around September.

If you need to accelerate this process, you can refer to CometD commercial support here:
https://cometd.org/support/

**Comment by softwareagsw** [comment]
Could you please provide an update @sbordet about the timeline for the release  , thank you !

I see that 8.x is still in progress - https://github.com/cometd/cometd/tree/8.0.x

**Comment by sbordet** [comment]
We are a little behind schedule, so CometD 8 will be delayed.

I cannot predict a date at this time, likely another month or two, unless commercial support from a customer speeds up the process.

**Comment by sbordet** [comment]
CometD 8.0.0.beta0 was just released.

Please try it out and let us know how it goes for you.

**Comment by sbordet** [comment]
Closing this issue, as CometD 8 releases are now in the beta cycle and soon will become stable.
