### ISSUE TITLE
The BayeuxClient in java sends advice on /meta/connect

### ISSUE THREAD

**Issue by zenbones** [cometd/cometd#1457]
Cometd version 5.x, but I'll bet it's in 7 as well. The documentation does not specify advice as either a required or optional field for /meta/connect, but the client sends it anyway. Either the client or the documentation is incorrect.

**Comment by sbordet** [comment]
The Bayeux protocol specification for the `advice` field is here:
https://docs.cometd.org/current/reference/#_bayeux_advice

The field is optional, so the client and the documentation are correct.
Admittedly, the CometD implementation only sets the advice field on `/meta/handshake` and `/meta/connect` messages.

What is the reason to open this issue? 
Are you working on an alternate implementation and you're trying to achieve interoperability?

**Comment by zenbones** [comment]
An alternate implementation. We experience collapse of the server with many fast messages and a few large messages, that is under 10 clients operating at 30 messages a second, most quite small, and a few rather large. A debug process is possible, but difficult. We want to be sure we can handle a very large set of clients (1000 or so) sending messages at 30 a second. We need a scaling cluster. Oort allows for clustering, which we use, but is not really a scaling solution as it multiplies the problem. We envision a version of cometd that is compatible with the client, and with our few server-side drop-ins, such as security policy and extensions. We'll have to rewrite the ack extension as it depends on internal implementations, but looking at the code, it can be greatly simplified (along with most other parts of the code base) and hopefully improved for scaling.

What we want to end up with is a cometd with a clustering message backbone baked-in, such that the clustering solution is both easily replaceable and obviates the need for Oort. We also need internal message queues that will not break under load, presumably through unconstrained growth, if that's the reason for our current issues. There are message backbones that will resolve this possibility as well, such as Kafka, RabbitMQ or Pulsar.

The code base for cometd as a whole is greatly overwrought, and contributes to debugging difficulty and probably to scaling issues as well. We're looking for something complete with a third the amount of code or less, that will be both maintainable and easily debugged. We're about half way through the implementation of cometd and are tracking well for a code base at least that small.

It was either this or dump cometd for socket.io, and add in a clustering backbone (Redis and RabbitMQ have both been successful), which would present it's own customization debt. Hopefully this is the correct choice.

**Comment by sbordet** [comment]
> We experience collapse of the server with many fast messages and a few large messages, that is under 10 clients operating at 30 messages a second, most quite small, and a few rather large.

Are you talking about CometD or your implementation?
CometD handles without breaking a sweat 300k+ connected clients and tens of thousands of messages per second.

> We want to be sure we can handle a very large set of clients (1000 or so) sending messages at 30 a second.

That's a minuscule load for CometD.

> The code base for cometd as a whole is greatly overwrought, and contributes to debugging difficulty and probably to scaling issues as well.

Or you probably do not understand the codebase.

Rather than insulting, how about you explain your issues rather than writing a new implementation?
Seems to me that you had an initial problem with a minuscule load and decided for a complete rewrite rather than asking whether you did something wrong.

I think you are also underestimating the CometD codebase, which has been battle-proven over the years over challenging deployments and finely tuned for scalability.

**Comment by zenbones** [comment]
Apologies. I don't mean to be insulting. There are clear problems with the API, which may be historical, but are mostly internal. I would have made other choices. There's clearly a good deal more code than is necessary. Those statements are not meant personally. This is just code.

Our issues could be with the threading model in the web-server (Grizzly), or in the websocket implementation (Tyrus). Tyrus is not NIO and spins several threads per connection from what I've read. My problem is that we get consistent collapse with no logs or error messages. Getting to that state is not easily testable. If I can get a test bed I can't easily debug the cometd code base. Our problem may not be cometd. Could be oort, which would be even harder to debug. Could be the ack extension.

What I want to do is clear the cruft, get something relatively simple and testable, remove the need for oort to cluster and replace it with something highly scalelable (Kafka) and replaceable (modular design), and know that I have message queues that guard themselves and my resource usage. The current design will not do.

The bayeux protocol is clear and easy enough. There are some sub optional API choices in the server but I can deal with those. And the total implementation is a few weeks work. I will have a third the code, no need for oort, I will know the code base clean through to set debug points, and I can freely alter any part for metrics as needed.

I believe you on cometd's performance, but I've still got a problem to solve. At worst we'll have a cometd with a cleaner code base, and a swappable oort replacement. Seems worthwhile.

**Comment by zenbones** [comment]
Also, I didn't come here with this conversation. I only reported what I thought was an inconsistency. You asked. Taking offense at the answer seems a little disingenuous.

**Comment by sbordet** [comment]
> There are clear problems with the API

You continue to blame CometD, but you have no evidence, and it's not a kind way to interact with any project.

> Our problem may not be cometd.

I think so too. Have you tried Jetty instead of Grizzly and Tyrus?

So you also have no proof that it is a CometD issue at all, yet you seem to have embarked on a crusade to "fix" CometD by rewriting it from scratch, a typical NIH syndrome.

Good luck with your implementation.
