### ISSUE TITLE
The Promise in server extensions seems counter to the documentataion

### ISSUE THREAD

**Issue by zenbones** [cometd/cometd#1460]
The docs on extensions says...

If the extension function returns null, the processing should stop: other extensions do not process the message, and CometD does not further process it. CometD does not send the message to the server, nor notify listeners.

The interface for server extensions Includes a Promise<Boolean> and the code seems to use async fold left, which leads me to believe the server is built to run extensions in parallel. That seems like a possible benefit, but runs counter to the documentation which gives extensions an execution order such that any extension returning false (the docs say null, but seem javascript oriented) stops further processing, which indicates extensions are executed synchronously. Then why the Promise? Or are the docs client only, and server side extensions can be run in parallel and any failing promise will stop listener notification and further message processing?

**Comment by zenbones** [comment]
Thinking further, extensions can alter messages, which are all based on Map<String, Object> (a problematic api decision) which is not thread safe, so it would seems that asynchronous extension processing must be disallowed, which makes me question using Promise<Boolean>.

Sorry for the above. Map is obviously neither safe or unsafe for threading, only the implementation. I was thinking about HashMapMessage in light of possible asynchronous processing.

**Comment by sbordet** [comment]
> The interface for server extensions Includes a Promise and the code seems to use async fold left, which leads me to believe the server is built to run extensions in parallel.

Nope.

> That seems like a possible benefit,

It is not.

> Then why the Promise?

To allow applications to process messages asynchronously.

> Thinking further, extensions can alter messages, which are all based on Map<String, Object> (a problematic api decision)

It is not a problematic API decision.

**Comment by zenbones** [comment]
If the server waits for the promise to complete before proceeding, then I'm not sure what an extension could be doing asynchronously with the Promise that it could not do on its own? Internally it could always use a Promise that returns the boolean to the caller on completion. So the server is neither allowing nor disallowing asynchronous processing in extensions, whether it uses a Promise or not. The server is stuck waiting for the completion either way. Maybe I'm still missing something. I guess it does not matter. Extensions are ordered and that's all that does matter. Thanks.

**Comment by sbordet** [comment]
An application may need to perform an asynchronous operation to process the message, say calling an external service via HTTP.

> So the server is neither allowing nor disallowing asynchronous processing in extensions, whether it uses a Promise or not. The server is stuck waiting for the completion either way.

The server implementation allows asynchronous processing in extensions, and it waits without blocking the thread until the processing is completed. The usage of `Promise` is what allows that -- a `boolean` won't work.

The server is not "stuck", as it can process other clients and their messages without problems.

**Comment by zenbones** [comment]
I see, thank you. Assuming extensions and message listeners need the leeway to execute long running processes, but not other listeners, which should abide by the general contract for listeners that they be fast?

This assumes there's some way for the transport to give up the thread it's running in and pick up the continuation when the promise completes. Websockets don't really have an asynch api yet (via jsr 356), which is the largest use case for a push notification server, but servlets do these days. That's thoughtful. I'll keep that in mind when I get to the long polling transport.

**Comment by sbordet** [comment]
> Assuming extensions and message listeners need the leeway to execute long running processes, but not other listeners, which should abide by the general contract for listeners that they be fast?

Extensions and certain listeners are designed so that the application can interact with the implementation by returning a value. These are modeled with `Promise`.
The listeners with a `void` return type don't need `Promise`.
As for "fast", it is more or less correct, but more correctly they should be non-blocking.

> This assumes there's some way for the transport to give up the thread it's running in and pick up the continuation when the promise completes.

HTTP and Jetty WebSocket can do this. JSR WebSocket cannot, so it scales less.

I am still trying to understand why you want to rewrite CometD, given that from your questions/comments you seem to be hitting for the first time problems that CometD solved 15 years ago.

**Comment by zenbones** [comment]
I don't see these as problems. Just trying to get the implementation as correct as I can, or at least know why I'm deviating. As I've said, I'm creating an implementation I can debug and fix. We have a use case that collapses our cometd 'server'. That's spring, grizzly, tyrus and cometd. No logs, No oom message. Nothing. That use case takes 10 people in dev. I don't know who's at fault. But we want this use case to work, and ones much like it. I can turn up logging and probably should, but debugging by tracing through logs is unlikely to be completely useful when there's no error message, which is the log I actually want. And maybe this is grizzly or tyrus or oort or the ack extension. Could easily be. So I need metrics. I need an instrumented code base, and I need it to be one I understand. I need to be able to play with it and alter the instrumentation, the thread model, whatever I need. That's either re-building cometd from source... are you a maven project?, or just building one of our own.

I have a websocket only cometd after a couple of weeks work, missing only extensions and listeners, and I'll need long polling. The server itself is about as fast the original (few hundred milliseconds behind over 10000 messages, but we have not yet optimized). That's single threaded operation over local host. But cometd does not own the thread model, so that should be equal given the same http daemon and websocket framework (which is how we're testing). That's also localhost, but cometd does not own the network protocol or socket, so again, equivalent.

So what did I buy with this effort? I bought a very simple code path, easy to debug, a third the lines of code, completely readable and simple to instrument. Far fewer classes, very few steps, highly modular. As a side-effect, I'll get rid of oort, which is both a very possible cause of our scaling issues, difficult to debug, and a replication of functionality already provided by enterprise massaging backbones, which we need (and use) anyway. Instead the server will just cluster, it will do so out of the box, and the clustering solution will be modular and replaceable.

Then I can debug. I can add and pipe metrics to our collector. I can simplify the ack extension and see what's going on. I won't have to worry about oort. I can guarantee I'll get a log message on whatever is failing. We already act pretty deeply in grizzly and tyrus, so that should be helpful.

We will open source the result in case anyone else is interested in what we've done.

**Comment by zenbones** [comment]
And looking at the asynch api for servlets there's still no way to give up the thread and complete it later. The best you get is to have your servlet execution scheduled in an executor, which isn't much. So either way, cometd can't give up the thread and let the server proceed until the promise completes. All it can do is wait synchronously on the completion... at least currently. It's still a fine thought I guess. Maybe someday.

**Comment by sbordet** [comment]
> And looking at the asynch api for servlets there's still no way to give up the thread and complete it later. 

Sure there is.

> The best you get is to have your servlet execution scheduled in an executor, which isn't much. So either way, cometd can't give up the thread and let the server proceed until the promise completes. All it can do is wait synchronously on the completion... at least currently.

You are wrong on this.

CometD does "give up" the thread until the promise completes. Asynchronous operations such as waiting on a `Promise` or on a long poll or Jetty WebSocket are completely threadless.

As I said, all solved loong time ago.

Have you considered [CometD commercial support with Webtide](https://docs.cometd.org/current/reference/#_support)?
You would be able to spend your time on your business software, rather than infrastructure software (your CometD rewrite).
I say this because from your comments you don't seem to have a good grasp on the technologies, or on the problems involved.

If there are metrics or other things that you need that are missing in CometD, and are generic enough, we can add them to CometD for your use (and for the CometD community).
We have been doing this many times over the years with our clients, with good success.

**Comment by zenbones** [comment]
Thanks, I see it for the AsyncContext.

Our infrastructure is our business software. I do very much appreciate your patience here. Very close to the end. I have one more stupid question, but I'll open that in a new thread.
