### ISSUE TITLE
How does a message know it's lazy?

### ISSUE THREAD

**Issue by zenbones** [cometd/cometd#1461]
Extensions and some listeners get the message they are operating on. Messages have isLazy(). The json encoding of a message does not have a lazy attribute, so a message must get its lazyness from a channel.

- Assuming the channel /a/** is lay, and the channel a/b/c/d is not lazy, a session subscribed to /a/** will get the message lazily and one subscribed to a/b/c/d will not?
- If a session is subscribed to both, is it defined whether the message will come via channel /a/** or /ab/c/d?
- Does an incoming extension on a session see the message as lazy? Does it depend on where the session is subscribed?
- Does an incoming extension of the server see the message as lazy?
- What about outgoing server/session extensions as they are theoretically operating on some specific channel at that point, as the message delivery came through some choice of channel?

Thanks

**Comment by sbordet** [comment]
Read the documentation:
https://docs.cometd.org/current/reference/#_java_server_lazy_messages

Message laziness applies to outgoing messages, not incoming messages.

**Comment by zenbones** [comment]
Ah, I see it now. Sorry I missed that.
