### ISSUE TITLE
Do lazy channels using the default maxTimeout get that default from the sending or receiving transport?

### ISSUE THREAD

**Issue by zenbones** [cometd/cometd#1462]
> When a server channel is marked lazy, by default it has a lazy timeout specified by the global maxLazyTimeout parameter (see also [the server configuration section](https://docs.cometd.org/current/reference/#_java_server_configuration)).

I see maxLazyTimeout on the transport configurations, not the servers. A channel can be used by multiple transports. So does the global maxLazyTimeout come from the sending sessions transport or the receiving (subscribed) sessions transport?

**Comment by sbordet** [comment]
I don't think I understand the question.

**Comment by zenbones** [comment]
Where do I set the 'global maxLazyTimeout parameter' referenced by the piece of documentation above. I do not see a global max lazy timeout for the server. I do see one for transports. But a channel does not belong to a transport. What's the intention here? What value is the actual 'global lazy timeout' for a channel marked lazy, but with no adjustments to its lazy timeout?

**Comment by zenbones** [comment]
Nvm. In the code there is no global default lazy timeout. It never comes from the channel. If the lazy timeout of the channel has never been set it's -1, and it uses the timeout of the transport of the message being enqueued, which would the transport of the sender I believe. If the channel has its timeout set it uses that, unless it's set negative, in which case that turns off lazyness, and can't ever reset the channel to the default.

**Comment by sbordet** [comment]
The `maxLazyTimeout` is configured in your CometD web application, typically in `web.xml` as `init-param`.

If you are using CometD embedded (i.e. you set it up via code, not auto-deploy of web applications), then you typically configure via `BayeuxServer.setOption(...)`.

You can furthermore customize it on a per-transport basis, as e.g. certain transports are less expensive at delivering messages so you may not want a lazy timeout.

Finally, you can customize the lazy timeout per channel or even per message.

There is no "transport of the sender" nor "transport of the receiver", I have no idea what you are talking about.

Once a session has handshaken to the server, it only has one transport.

You can easily change the channel lazy timeout, including reset it to the default.
