### ISSUE TITLE
Move cometd.js to ES6

### ISSUE THREAD

**Issue by sbordet** [cometd/cometd#1511]
**CometD version(s)**
8+

**Description**
The `cometd.js` library should be moved to full ES6, using `export` rather than old JS tricks.

Similarly for `browser.js`.

**Comment by ghoullier** [comment]
Is this issue opened to external contribution? I used to [work](https://github.com/zetapush/zetapush/tree/master/packages/cometd/lib) with cometd for the past few years.

**Comment by sbordet** [comment]
Yes, it is open to external contributions.

**Comment by sbordet** [comment]
Do I understand correctly that zetapush is just a copy of the CometD files, with small modifications to use a NodeJS syntax?

Is there a reason you did not use https://www.npmjs.com/package/cometd-nodejs-client?

**Comment by ghoullier** [comment]
ZetaPush company went bankrupt and the related project is no longer active. When we start the project more 7 years ago the lib you mention [did not supports](https://github.com/cometd/cometd-nodejs-client/blob/1.0.0/cometd-nodejs-client.js) WebSocket transport. So we decided to create a fully `CommonJS` compliant version of the cometd client with a WebSockTransport support.

**Comment by ghoullier** [comment]
**question**❓
Should the PR introduce a breaking change on UMD compatibility?

**Comment by sbordet** [comment]
@ghoullier I would say that it is time to just embrace ES6 modules, dropping support for CommonJS, AMD, UMD, etc.

If you are working on this, please work on the CometD `8.0.x` branch.
I'd leave older branches unchanged.

**Comment by sbordet** [comment]
Fixed by #1613 and #1714.
