### ISSUE TITLE
Wrong Jetty version in CometD 6.x/7.x MANIFEST

### ISSUE THREAD

**Issue by tilenjez** [cometd/cometd#1535]
Import-Package section in MANIFEST files for CometD 6.x and CometD 7.x require Jetty 9.4 (< 10), instead of Jetty 10 and 11 respectively. This prevents CometD bundles from being deployed in OSGi environments running Jetty 10+.

The problem may be caused by the following Import-Package instruction in Maven Bundle Plugin configuration in the main pom.xml:
`<Import-Package>org.eclipse.jetty.*;version="[9.4,10)",*</Import-Package>`

**Comment by sbordet** [comment]
Thank you for opening this issue, I'll fix it right away.
