### ISSUE TITLE
 Support the "Partitioned" cookie attribute

### ISSUE THREAD

**Issue by sbordet** [cometd/cometd#1551]
**CometD version(s)**
6+

**Description**
See https://github.com/jetty/jetty.project/issues/10891

**Comment by AlexTestings** [comment]
Hello,

Can you please let us know if this patch will be included in CometD version 3 as well?

Thank you very much,
Best Regards,
Alex

**Comment by sbordet** [comment]
No, CometD 3 is at end-of-life since many years now, and you should upgrade, also to avoid being exposed to vulnerabilities.

There are [migration guides](https://docs.cometd.org/current7/reference/#_migration), or you can request [commercial support from Webtide](https://docs.cometd.org/current7/reference/#_support) where we can help you in the migration.
