### ISSUE TITLE
Wrong processing of Set-Cookie with "expires" with Jetty client

### ISSUE THREAD

**Issue by martin-frydl** [cometd/cometd#1599]
**CometD version(s)**

8.0-beta1

**Java version & vendor** (use: `java -version`)

openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment (build 17.0.9+9-Ubuntu-122.04)
OpenJDK 64-Bit Server VM (build 17.0.9+9-Ubuntu-122.04, mixed mode, sharing)

**Description**

When Set-Cookie header contains "expires", like `BrowserId=be7II763489fhwcun5pA; domain=.salesforce.com; path=/; expires=Thu, 02-Jan-2025 14:21:47 GMT; Max-Age=31536000`, cometd fails to process it and does not send it in following requests. The reason is commit 62c4663ead0d9865240ca213b79c13be02cad59f which changed `field.getValue()` into `field.getValueList()`. The problem is that Jetty `HttpField.getValueList()` treats the header value as CSV and splits it by comma. So the result is list with two values: `BrowserId=be7II763489fhwcun5pA; domain=.salesforce.com; path=/; expires=Thu` and `02-Jan-2025 14:21:47 GMT; Max-Age=31536000`. Frankly, I don't know how multiple cookies can be set by single Set-Cookie header as RFC 6265 does not seem to allow that so I don't see a reason for using `getValueList()` instead of `getValue()`.

**How to reproduce?**

Not sure, I'm using cometd to connect to Salesforce to read notifications.

**Comment by sbordet** [comment]
@martin-frydl thank you for reporting this issue, it should be fixed with #1631.

**Comment by sbordet** [comment]
Fixed by #1631.
