### ISSUE TITLE
Cannot access SessionId from BayeuxContext

### ISSUE THREAD

**Issue by wojtassi** [cometd/cometd#1652]
CometD version 8.0.0.beta2. JVM Corretto 17.0.6

**Description**
This PR: https://github.com/cometd/cometd/pull/1385/files#diff-bf6d5d87fbe8ff18ed38d014ea9ca5ceb525fe82cbc3e2bc75d3a62f184d93e0 abstracted out CometD from Servlet API.

One of the thing removed was getHttpSessionId(). You can still getSessionAttributes, but there is no way to get SessionId (without restoring to reflection). Any chance getSessionId() can be re-added? Alternatively getSession (that returns Object) would also work and be more generic.

**Comment by sbordet** [comment]
I think it can be restored.

Out of curiosity, what do you use the session id for?

**Comment by wojtassi** [comment]
We use sessionId to keep track of connections, so messages can be published to correct users and to be able to do cleanup.

BTW. Do you have a rough idea when 8.0 will be GA? Few weeks? Few months? If it helps, I have not seen any issues with 8.0 that were caused by CometD itself. (Other then missing getSessionId) Jetty 12 caused some issues, mainly because handshaking is now done asynchronously (instead of inside of spring framework's filter chain) so we lost Security context and one of the filters (ShallowEtagHeaderFilter) was causing content-type to not be set correctly but again, those were not caused by CometD itself. 

Thanks,

wojtassi

**Comment by sbordet** [comment]
> We use sessionId to keep track of connections, so messages can be published to correct users and to be able to do cleanup.

But you cannot keep track of connections using the HTTP session id.
It would be the same for all the connections from the same client, so you could only count different clients, not connections.

CometD 8 final is not far away, we need to decide on few things and restore Spring integration.
Thanks for the feedback on CometD 8 and Jetty 12.
Please report your problems in either project, if any, as it will help to fix them sooner.

**Comment by wojtassi** [comment]
> But you cannot keep track of connections using the HTTP session id.
> It would be the same for all the connections from the same client, so you could only count different clients, not connections.

In our case "connection" is misnomer, our code's connection is basically a multimap of sessionid to Bayeux ServerSession.

Thanks for the answer and sorry for confusion.

**Comment by sbordet** [comment]
> In our case "connection" is misnomer, our code's connection is basically a multimap of sessionid to Bayeux ServerSession.

Consider that for the same HTTP session id, you can have multiple `ServerSession`s (for example, 2 browser tabs).

**Comment by wojtassi** [comment]
Hi @sbordet With another beta released for 8.0, is there any world about when 8 will go GA? We have a release in few months, and it would be nice to know if we can include Jetty 12 update.

Thanks.

**Comment by sbordet** [comment]
@wojtassi this new beta was mostly about the JavaScript client, which has been ported to full ES6.

I expect a final 8.0.0 in a couple of weeks.

**Comment by wojtassi** [comment]
Thank you @sbordet for quick answer. Also I assume that you are hesitant of exposing SessionId. If so we can close this issue. I have a work around that will work for us.

**Comment by sbordet** [comment]
@wojtassi I still plan to restore access to the HTTP session id 😃

**Comment by sbordet** [comment]
Fixed by #1730.
