### ISSUE TITLE
When will the 8.0 version be released to support jetty12?

### ISSUE THREAD

**Issue by stevenniu9527** [cometd/cometd#1751]
Hi, When will the 8.0 version be released to support jetty12?
and Is there an migration instructions？

**Comment by stevenniu9527** [comment]
Is there an migration instructions？

**Comment by sbordet** [comment]
We are working on a few incompatibilities introduced with Jetty 12.0.9.

The plan is to release 8.0.0 as soon as these incompatibilities are resolved.

**Comment by stevenniu9527** [comment]
邮件已经收到，我会尽快查看，谢谢

**Comment by sbordet** [comment]
CometD 8.0.0 has been released to Maven Central and to npmjs.com.
