### ISSUE TITLE
Migrating from Cometd Java Client Websocket Jetty from 5.x to 7.x,8.x problem in handshake

### ISSUE THREAD

**Issue by cmveasngti** [cometd/cometd#1768]
**7.x - 8.x**

**JAVA VERSION 17 - Android Application - Emulator (Android 9 / 10)** 

**Description**
**This problem is only happening on Android 9 / 10 - API 28/29 - Newer versions of Android perform the handshake normally**

We are trying to migrate our dependecy on "cometd-java-client-websocket-jetty" from 5.x to something newer but we have different problems on the recent versions. Both problems during handshake:

1. 7.x -> reports a org.cometd.common.TransportException: {websocketCode=1002, httpCode=0}, websocketCode=1002, message={supportedConnectionTypes=[websocket], channel=/meta/handshake, id=2, version=1.0}, httpCode=0, connectionType=websocket}
2. 8.x -> reports a {exception=java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Ljava/util/stream/Stream; or its super classes (declaration of 'java.util.stream.Stream' appears in /apex/com.android.runtime/javalib/core-oj.jar), message={supportedConnectionTypes=[websocket], channel=/meta/handshake, id=1, version=1.0}, connectionType=websocket}

**How to reproduce?**

- We just try to perform a connection with handshake

**Comment by sbordet** [comment]
For the problem on CometD 7.0.x, there is too little detail, so cannot help you.

For the problem in CometD 8.0.x, the Android APIs do not support the new OpenJDK methods.
We could avoid using certain APIs in CometD, but I think even if we fix `Stream.toList()` usages, there may be other incompatibilities.

We would need your help to identify which APIs Android does not like, and see whether it's possible to modify them.
Can you provide a comprehensive list of incompatible APIs?

**Comment by cmveasngti** [comment]
Thanks for the answer!

For 7.x I will try to get more information. If you have any suggestions on what you would need to see, that would be great.

For 8.x I'll see if I can come up with that list but I'm not entirely sure where to look. I'm also wondering if we solve the incompatibilities problem if we wont run into the situation 7.x is having considering looking at the code the issue seems to be happening before calling the method that makes 7.x fail.

**Comment by cmveasngti** [comment]
here is what I got as incompatible APIs for the 8.x 

```
Stream.toList()
Stream.takeWhile()
Stream.dropWhile()
Stream.ofNullable()
Optional.orElseThrow()
```

**Comment by sbordet** [comment]
I just tried the CometD client on an Android Emulator API 28 and everything seems to work fine.

Are you using the `OkHttpClientTransport`?
Or, if you want to use WebSocket, the `OkHttpWebSocketTransport`?

**Comment by cmveasngti** [comment]
hey @sbordet 
Thanks for the reply, as far as I see we are using the 'JettyWebSocketTransport', not sure if we are able to switch btw since I was not the dev who integrated this solution.

**Comment by sbordet** [comment]
@cmveasngti switching the transport is a matter of a simple search/replace, it should be super-easy (along with the necessary dependency updates -- add `okhttp` as a dependency).

**Comment by cmveasngti** [comment]
@sbordet I'll give it a shot now. (Sorry, just back from vacations and rebooting the brain takes extra time)
Thanks again for the response

**Comment by cmveasngti** [comment]
YES! thanks @sbordet, this definitely works on Android 28 > and on the higher OS's. Thanks a lot for the support here

**Comment by sbordet** [comment]
Glad it worked, closing this issue.
