### ISSUE TITLE
I can't find AsyncJSONTransport after Migrating from CometD 7.0.x to CometD 8.0.x, is Package/Class Names Changes?

### ISSUE THREAD

**Issue by stevenniu9527** [cometd/cometd#1819]
**CometD version(s)**
ConetD 8.0.2

**Java version & vendor** `(use: java -version)`
JDK 21

**Question**
![image](https://github.com/cometd/cometd/assets/79351731/8a249240-aa06-4dd3-8579-3e40c7bfc98e)

I can't find AsyncJSONTransport after Migrating from CometD 7.0.x to CometD 8.0.x, is Package/Class Names Changes?

**Comment by sbordet** [comment]
The new name is `JSONHttpTransport`.

I will update the migration guide at:
https://docs.cometd.org/current8/reference/#_migration_70_to_80

Thanks for reporting this.

**Comment by stevenniu9527** [comment]
邮件已经收到，我会尽快查看，谢谢

**Comment by sbordet** [comment]
I'm curious about why you are extending this CometD class?

Is there any missing feature that could perhaps be made available in the CometD project?

**Comment by stevenniu9527** [comment]
> I'm curious about why you are extending this CometD class?
> 
> Is there any missing feature that could perhaps be made available in the CometD project?

Override  method toJSONBytes to prevent cross-site scripting , like < escaped to &lt
