### ISSUE TITLE
Missing artifact cometd-java-api:8.0.3 ?

### ISSUE THREAD

**Issue by stuban** [cometd/cometd#1860]
cometd version **8.0.3**

Looks like something went wrong when publishing the 8.0.3 release. I can not find the artifact cometd-java-api on maven central:

https://repo1.maven.org/maven2/org/cometd/java/cometd-java-api/8.0.3/cometd-java-api-8.0.3.pom
results in 404

Or did I miss some restructuring?

**Comment by sbordet** [comment]
You are right, it is not there... perhaps the upload failed, but the release continued?

In any case, I'm releasing CometD 8.0.4 in a few hours.

**Comment by sbordet** [comment]
@stuban CometD 8.0.4 has been released, should be in Maven Central soon.
