### ISSUE TITLE
User Principal Lost with JSONHttpTransport in Spring Boot/CometD

### ISSUE THREAD

**Issue by jtrentes** [cometd/cometd#1869]
**CometD version(s)**
8.0.4

**Java version & vendor** `(use: java -version)`
openjdk 17.0.11 2024-04-16 LTS
OpenJDK Runtime Environment Microsoft-9388408 (build 17.0.11+9-LTS)
OpenJDK 64-Bit Server VM Microsoft-9388408 (build 17.0.11+9-LTS, mixed mode, sharing)

**Spring Boot Version**
3.3.0

**Tomcat Version**
10.1.26

**Description**
We're encountering an issue with user principal retrieval using JSONHttpTransport in a Spring Boot 3.3.0 application running on Tomcat with CometD.

**Problem**

WebSocket transport works as expected, and message.getBayeuxContext().getUserPrincipal() returns the correct value.
JSONHttpTransport consistently returns null for the same method.

**Investigation**

I know that for long polling there is a direct link between the information contained in the BayeuxContext and the current HTTP request that carried the Bayeux message (JakartaBayeuxContext). And the WebSocket transport, the BayeuxContext instance is created only once (JakartaWebSocketContext). This explains the difference between the two transports.

We've confirmed that the user principal is available at the beginning of the HTTP request but is lost within CometD listeners and also in our SecurityPolicy.

Our configuration seems ok: 
- Tomcat is configured to support non blocking requests
-  Async mode is enabled in our Spring configuration and on the CometD servlet and filters (@EnableAsync, `<async-supported>true</async-supported>` is used on the CometDServlet)
- SecurityFilterChain is properly configured.

We tried using the MODE_INHERITABLETHREADLOCAL strategy and setting the task executor (BayeuxServerImpl#setExecutor) to use DelegatingSecurityContextAsyncTaskExecutor.

**Workaround**

To address this, we've implemented a custom CometDServlet that wraps the original request, preserving the user principal:
```
public class CometDServlet extends org.cometd.server.http.jakarta.CometDServlet
{
    @Override
    protected void service(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException
    {
        super.service(new CometDHttpServletRequestWrapper(request), response);
    }

    private static class CometDHttpServletRequestWrapper extends HttpServletRequestWrapper
    {
        private final Principal userPrincipal;

        public CometDHttpServletRequestWrapper(HttpServletRequest request)
        {
            super(request);

            // Save the user principal from the original request so that it is
            // available to CometD when using JSONHttpTransport
            this.userPrincipal = request.getUserPrincipal();
        }

        @Override
        public Principal getUserPrincipal()
        {
            return userPrincipal;
        }
    }
}
```

We know that this solution is not ideal, but at least it solves the problem for the JSONHttpTransport . Do you have any idea what the problem is?

**Comment by sbordet** [comment]
@jtrentes did you ask Tomcat?

Because CometD does not "lose" the user principal: it references the `HttpServletRequest` implementation Tomcat has built, and calls that. Why two calls, one at the beginning and one later, return different values, I don't know.

Have you tried to quickly switch to Jetty in your Spring Boot configuration, and verify whether it works as expected?

It should just be a matter of a simple change in your POM files, see https://docs.cometd.org/current8/reference/#_java_server_services_integration_spring_boot.

**Comment by jtrentes** [comment]
Sorry for the way I phrased it. I did see that CometD refers to HttpServletRequest and it's not directly responsible of the "lose" of the user principal.

I can't switch to Jetty easily because we're using an external tomcat server and not the Spring Boot launcher. I'll see if I can reproduce the problem with a smaller configuration.

**Comment by sbordet** [comment]
If you can reproduce, will be great.

If you open an issue in Tomcat for discussion, please reference it also here.

Thanks!

**Comment by sbordet** [comment]
@jtrentes did you figure out what was the problem?

**Comment by jtrentes** [comment]
@sbordet No... we don't have the time to work on it any further at the moment, so we're going to keep this workaround solution for the time being (we improved it a little by creating the HttpServletRequestWrapper in a Filter instead of overriding CometDServlet). If we find the reason I'll post an update but for now I'd rather close this issue as we don't know what's causing it.

Here is the updated workarround:
```java
@WebFilter(urlPatterns = "/cometd/*", asyncSupported = true)
public class CometRequestContextFilter implements Filter
{
    @Override
    public void doFilter(ServletRequest req, ServletResponse res, FilterChain chain)
            throws IOException, ServletException
    {
        HttpServletRequest request = (HttpServletRequest) req;
        chain.doFilter(new CometDHttpServletRequestWrapper(request), res);
    }

    private static class CometDHttpServletRequestWrapper extends HttpServletRequestWrapper
    {
        private final Principal userPrincipal;

        public CometDHttpServletRequestWrapper(HttpServletRequest request)
        {
            super(request);
            this.userPrincipal = request.getUserPrincipal();
        }

        @Override
        public Principal getUserPrincipal()
        {
            return userPrincipal;
        }
    }
}
```
