### ISSUE TITLE
Review negotiation and reconnection upon transport failure

### ISSUE THREAD

**Issue by sbordet** [cometd/cometd#483]
#468 and #478 introduced changes in the WebSocket transports to try to reconnect intelligently to the same WebSocket server or to fallback to long-polling.

Unfortunately these modifications fall short and do not cover all cases.
For example, if the server is restarted without WebSocket, a client that was previously able to connect won't anymore be able to, and will retry WebSocket without ever falling back to long-polling.

Therefore some kind of application logic should be applicable to the transport negotiation, something along these lines:

  1. notify the application of the transport failure via a listener
  1. give the application the ability to modify the transports to be attempted by allowing the application to enable/disable a transport
  1. retry the transport allowed by the application

This would allow the application to implement counters to retry a failing transport a number of times, even introduce a delay before retrying (and therefore this may have impacts on the backoff mechanism) or decide to stay on one specific transport that is known to be working despite the failures (perhaps only due to local network failures or to server restarts).

**Comment by abbakym** [comment]
Having developed a few CometD-based applications, I can tell that the level of abstraction required on application level was always "can / can't connect to server". Playing with transports, backoff increments and number of retry attempts in runtime is too low-level. It may be interesting and even useful for specific cases (although I can hardly imagine such cases to be honest), but on the application level I usually want to know one simple thing: if the server is up and can handle the connection. And if it's not, I want CometD to tell me about that _as early as possible_, so that end user's time is not wasted.

**Comment by sbordet** [comment]
Can you please detail what you would like to do _after_ that CometD notifies you that the server is down ? Let's assume that CometD does nothing, it just attempts to connect, fails, and notifies your application. Then ?

**Comment by abbakym** [comment]
Basically - to show a message to the end user: "We're sorry, something went wrong".

**Comment by sbordet** [comment]
Sure I understand that. But then ? CometD will do nothing, and your user has no other option than to close the application.
What if the failure was temporary ? You don't want to retry, nor to try another transport, or perhaps another URI, or something else ? Just show the user "sorry" and leave the application disconnected ?

**Comment by abbakym** [comment]
Well, for our particular cases (third-party apps embedded onto the page, like chat widget), this is enough. Having more is too costly and probably won't work. If the user tries to start the chat and it fails, there is a very low probability of conversion if we automatically detect that "server is up again" and ask the user to try again.

**Comment by abbakym** [comment]
Of course, having some kind of such functionality may be beneficial. However I think that again, the level of abstraction for application code here should be high enough: as app developer, I want to be notified that connection is now possible again.

**Comment by sbordet** [comment]
@givankin wrote:
> as app developer, I want to be notified that connection is now possible again

This is already possible by using `/meta/connect` and `/meta/handshake` listeners and a simple `boolean` flag.

The problem we're discussing here is how can CometD notify the application that the connection has been reestablished.
CometD _must_ try to reconnect over and over until one attempt succeed.
If CometD just gives up and does not try to reconnect, then it will never know if the connectivity has been reestablished, and it won't be able to notify the application.

The point of this issue is for an application to specify _how_ CometD should try to reconnect, rather than CometD having a hard-coded policy.

**Comment by sbordet** [comment]
Current variables for the reconnection policy:

 * what action to take 
  * akin to `advice.reconnect`: `"none"`, `"connect"`, `"handshake"`, etc.
 * when to execute the action
  * akin to backoff: immediately, after some time
 * what transport to use next; to decide, the application needs:
  * the transport that failed (type and URL)
  * the error type (recoverable or not, to understand whether it is possible to try the same transport - perhaps this can be done by CometD)
  * the list of possible transports (see above, perhaps CometD can filter out non-recoverable transports)
  * the URL to use with the new transport (perhaps the application want to change host or scheme/port or the entire URL - this implies that transports should support dynamic URLs)
