### ISSUE TITLE
Explore PhantomJS

### ISSUE THREAD

**Issue by sbordet** [cometd/cometd#487]
http://phantomjs.org/

We could replace usage of Rhino for a better JS test environment ?

**Comment by chchrist** [comment]
I would recommend http://casperjs.org/ which is built on top of phantomjs with a mushc easier to use API

**Comment by sbordet** [comment]
The problem is that PhantomJS does not support WebSocket, which we need, and I am not sure about the threading support as well (we need the single thread support like browsers do).

This has been open for years, and PhantomJS never implemented WebSocket, so I am closing it as not worth looking into.

If you have further information, please reopen.
