### ISSUE TITLE
Add package.json to make CometD npm installable

### ISSUE THREAD

**Issue by sbordet** [cometd/cometd#509]
It would be nice to be able to install CometD via npm. Currently this is impossible because of the missing package.json, so fixing this should be simple.

Having to use maven overlays to manage JS dependencies is too huge.

**Comment by seansfkelley** [comment]
I ported the client to an npm module at https://github.com/seansfkelley/cometd-commonjs, but note that it doesn't include the Dojo or jQuery bindings at the moment, nor any of the default extensions/plugins (like the timestamp sync one, etc.).

**Comment by chchrist** [comment]
Yes, it is a pain to update the JS library at the moment. I don't mind adding the package.json

**Comment by sbordet** [comment]
Discussion ongoing at #649.
