### ISSUE TITLE
Document configuration for spring boot application

### ISSUE THREAD

**Issue by sbordet** [cometd/cometd#590]
Describe how to configure cometd with spring boot application. 

@Configuration
@EnableAutoConfiguration
public class WebsocketConfiguration {

```
private static Logger logger = LoggerFactory.getLogger(WebsocketConfiguration.class);

@Bean
public JettyEmbeddedServletContainerFactory servletContainerFactory() {
    JettyEmbeddedServletContainerFactory factory = new JettyEmbeddedServletContainerFactory();

    factory.addServerCustomizers(new JettyServerCustomizer(){
        @Override
        public void customize(Server server) {
            try {
                WebSocketServerContainerInitializer.configureContext((WebAppContext)server.getHandler());
            } catch (ServletException e) {
                logger.error(e.getMessage());
            }
        }           
    });     
    return factory;
}

@Bean
public ServletRegistrationBean servletRegistrationBean(){
    CometDServlet cometdServlet = new CometDServlet();
    return new ServletRegistrationBean(cometdServlet,"/cometd/*");
}

@Bean
public FilterRegistrationBean filterRegistration() {
    FilterRegistrationBean filter = new FilterRegistrationBean();
    CrossOriginFilter crossOriginFilter = new CrossOriginFilter();
    filter.setFilter(crossOriginFilter);
    filter.setAsyncSupported(true);
    filter.setName("cross-origin");
    filter.addUrlPatterns("/cometd/*","/chat/template/*");
    return filter;
}

@Bean
public ServletContextInitializer initializer() {
    return new ServletContextInitializer() {
        @Override
        public void onStartup(ServletContext servletContext) throws ServletException {
            servletContext.setAttribute(BayeuxServer.ATTRIBUTE, bayeuxServer(servletContext));
        }
    };
}

@Bean
public BayeuxServer bayeuxServer(ServletContext servletContext)
{
    BayeuxServerImpl bean = new BayeuxServerImpl();
    bean.addExtension(new org.cometd.server.ext.AcknowledgedMessagesExtension());
    bean.setOption(ServletContext.class.getName(), servletContext);
    bean.setOption("ws.cometdURLMapping", "/cometd/*"); 
    return bean;
}
```

}

**Comment by jaypatel512** [comment]
Hey @sbordet !

We are trying to get cometD server running in Spring Boot Application that prohibits us to use any xml. We tried your example, but we are having trouble getting it to work. We use tomcat and NOT Jetty for this. 

Do you have a documentation that can help us point to the right direction. We could not find anything online that worked. E.g. Sample project.

**Comment by sbordet** [comment]
@jaypatel512 I added a fully working Spring Boot 2.x example in the source code.
See a0e0f5b91ac42cfdb0e9f9e6e9784b287c8f83b3, in particular class `CometDApplication`.

**Comment by jaypatel512** [comment]
Hey @sbordet !

Thank you so much for a prompt response as always. I tried implementing `CometDApplication`, `DemoServlet` and `ChatService` almost exactly the same way, with one exception that our CometDApplication extends `SpringBootServletInitializer`.

But even then, I am getting `_bayeux` bean not found in ChatService. Am I missing something here ? Or do I need more than these 3 files ?

Thanks again for your tremendous help.

**Comment by sbordet** [comment]
@jaypatel512 `SpringBootServletInitializer` implements `WebApplicationInitializer` and I was not able to make it work either. Probably something changed in Spring Boot.
However, it works if you implement `ServletContextInitializer`.
Try to dig into the Spring Boot documentation.

**Comment by jaypatel512** [comment]
Will do. And found one other tiny issue/mistake on my end was with using Spring's `@Service` and not cometd `@Service`. Not easy to point the difference. 🤣

**Comment by jaypatel512** [comment]
I think I was able to get it to work mostly. The final issue I found was related to my ChatService autowiring few services. As the `ChatService.class.getName()` is used as a part of initparams, and we allow cometD to initialize that class, we cannot autowire other dependencies using Spring @Autowired annotations. Not sure if that is doable @sbordet

**Comment by sbordet** [comment]
It should be doable, as [documented](https://docs.cometd.org/current/reference/#_java_server_services_integration_spring).

The idea is that instead of having `AnnotationCometDServlet` play the role of the dependency injection container, you let Spring do that, and only use `ServerAnnotationProcessor` to process CometD-specific annotations.
