### ISSUE TITLE
websocket error reason of javax.websocket is limited to 123 characters

### ISSUE THREAD

**Issue by squiddle** [cometd/cometd#606]
javax.websocket.CloseReason limits the reasonPhrase to 123 UTF-8 bytes (http://w3c-test.org/websockets/Close-Reason-124Bytes.htm this limitation follows from the close frame specification and the websocket packet framing)

The WebSocketTransport uses javax.websocket and can generate reasonPhrases longer than 123 characters, as it uses the message of a catched exception.

cometd-java-websocket-javax-server:3.0.5
WebSocketTransport.java:164 is the final culprit calling into javax.websocket API

**Comment by sbordet** [comment]
Thanks for reporting this, already fixed in master a while back, on both client and server.

**Comment by squiddle** [comment]
awesome, sorry for the superfluous ticket
