### ISSUE TITLE
CometD Java client does not call publish callback when publish reply contains "data" field

### ISSUE THREAD

**Issue by mskotnikov** [cometd/cometd#607]
Hi,
I have the following Java client code:
```java
ClientSessionChannel joinChannel = bayeuxClient.getChannel(CometdChannels.SERVICE_SESSION_JOIN);
joinChannel.publish(createJoinSessionRequest(session.getSessionToken(), role), new MessageListener() {
    @Override
    public void onMessage(ClientSessionChannel channel, Message message) {
        if (!message.isSuccessful()) {
            disconnectDueToError(ErrorType.JOIN_ERROR, message.getJSON(), callback);
            return;
        }
                        
        Map<String, Object> data = message.getDataAsMap();
        // handle data
    }
});
```
My message listener is not called for the following reply:
```json
{id=2, data={users=[], userToken=1fa97gbmd9ul5abivymy, userId=1, sessionHistoryId=1ac73000-6c3b-11e5-bbe8-4c72b94adfdd, writeModeAllowed=true}, successful=true, channel=/service/session/join}
```
Debugging revealed that callback is called only if reply does NOT contain the `data` field:
```java
@Override
protected void notifyListeners(Message.Mutable message) {
    ClientSessionChannel.MessageListener callback = (ClientSessionChannel.MessageListener)message.remove(CALLBACK_KEY);
    if (message.isMeta() || message.isPublishReply()) {
        String messageId = message.getId();
        callback = messageId == null ? callback : unregisterCallback(messageId);
        if (callback != null)
            notifyListener(callback, message);
    }
    super.notifyListeners(message);
}

public boolean isPublishReply() {
    return !isMeta() && !containsKey(DATA_FIELD);
}
```
But my CometD exchange does suppose to send response data and it perfectly worked with JavaScript client for 3 years.
Now I am trying to create load tool in Java which simulates the business protocol and encountered this limitation.

Could you align Java client to JavaScript in this regard?

At the same time I will try to workaround the issue by activating a listener at the channel level.

**Comment by sbordet** [comment]
The publish callback is not for receiving messages, but just to be notified that the message you sent arrived to the server, successfully or not.

The behavior you are seeing is by design.

The correct way to receive messages is to add a `MessageListener` to the channel, either via `ClientSessionChannel.subscribe(MessageListener l)` or via `ClientSessionChannel.addListener(ClientSessionChannelListener l)`

**Comment by mskotnikov** [comment]
Responses enable to send request contextualized data and publish callback enables to refer to request specific context. It is not available in case of a listener and ability to pass a context is a viable feature in asynchronous programming, which CometD is all about.

As I understand Java client is supposed to represent the same functionality of JavaScript client (in case client code uses Java, e.g. a desktop application). This feature is available in case of JavaScript client.
Thus, this discrepancy can be considered as a design defect in one of the clients.

It is absolutely not clear what is the purpose (in case of Java client only) of restricting calling callback in case a response contains data, while generally the possibility to associate a callback with response is already available.

**Comment by sbordet** [comment]
I don't understand what you mean by:

> Responses enable to send request contextualized data and publish callback enables to refer to request specific context. It is not available in case of a listener and ability to pass a context is a viable feature in asynchronous programming, which CometD is all about.

Can you provide an example ?

Both JavaScript and Java clients have the same features, so again I don't understand what discrepancy you are referring to.

A callback is just code that is notified when the message you published arrived to the server.
The Bayeux server (following the Bayeux protocol) replies to that with a message that does not contain the `data` field, and this reply is conveyed to the callback. This allows applications to know that the message they published successfully arrived on server.

A message listener is  code that is notified when a message arrives on that channel.

A client application may _never_ need to send messages to the server, yet needs receive messages from the server. That is what a message listener is for.

A different client application may _never_ need to receive messages from the server, yet needs to publish messages to the server, _and_ know whether they are arrived successfully or not (in which case it may retry). This is what a callback is for.

I hope it's clear now what difference there is between a callback and a message listener.
They serve different purposes, they need to exist separately, and both are present in the Java and JavaScript clients (albeit with a slightly different syntax).

**Comment by mskotnikov** [comment]
> Responses enable to send request contextualized data and publish callback enables to refer to request specific context.
Can you provide an example ?

On the server side extra data can be specified in a similar way as marking response as unsuccessful:
```java
    private void respondWith(ServerMessage requestMessage, Map<String, Object> responseData) {
        requestMessage.getAssociated().setData(responseData);
    }
```
```java
    @AfterThrowing(
            pointcut = "@annotation(org.cometd.annotation.Listener)",
            throwing = "e"
    )
    public void notifyRequestException(JoinPoint joinPoint, Throwable e) {
        ServerMessage message = (ServerMessage) joinPoint.getArgs()[1];
        ServerMessage.Mutable response = message.getAssociated();
        response.setSuccessful(false);
    }
```
On the client side callback function passed in publish can be a closure which may refer to the calling context:
```java
void join(Role role, final JoinListener callback) {
ClientSessionChannel joinChannel = bayeuxClient.getChannel(CometdChannels.SERVICE_SESSION_JOIN);
joinChannel.publish(createJoinSessionRequest(session.getSessionToken(), role), new MessageListener() {
    @Override
    public void onMessage(ClientSessionChannel channel, Message message) {
        if (!message.isSuccessful()) {
            disconnectDueToError(ErrorType.JOIN_ERROR, message.getJSON(), callback);
            return;
        }

        Map<String, Object> data = message.getDataAsMap();
        // handle data
        callback.onJoined( /* extracted data */ );
    }
});
}
```
Look at `final JoinListener callback` called from Bayeux callback.
> Both JavaScript and Java clients have the same features, so again I don't understand what discrepancy you are referring to.

As I wrote initially the case highlighted in the issue subject works perfectly with JavaScript equivalent code - publish callback is called and it can consume response data.

> A callback is just code that is notified when the message you published arrived to the server.
The Bayeux server (following the Bayeux protocol) replies to that with a message that does not contain the data field, and this reply is conveyed to the callback. This allows applications to know that the message they published successfully arrived on server.

It is clear which information exchange supports Bayeux protocol. Data field encapsulates information exchange of a business protocol built on top of Bayeux protocol. And it is quite common in client / server communication to have request / response like communication pattern.
It is mostly supported by CometD:
* Server side - fully supported
* JavaScript side - fully supported
* Java client side - partially supported (mechanism to associate callbacks with responses does exist, but callbacks for responses with data forcibly not called)

> I hope it's clear now what difference there is between a callback and a message listener.

Usage of callbacks is artificially limited in case of Java client and I don't understand **why** their power is not unleashed to full extent, as it is available with JavaScript client.

> They serve different purposes, they need to exist separately

They can complement each other: listener when request context is not important or simply does not exist and callback when request contextualized processing is needed.
Actually, this pattern is already an official design, for example, the handshake response can be processed via a callback and a listener:
http://docs.cometd.org/3/reference/#_java_client_handshake

**Comment by sbordet** [comment]
> As I wrote initially the case highlighted in the issue subject works perfectly with JavaScript equivalent code - publish callback is called and it can consume response data.

If that is true, then it is a bug. 

In fact, I just checked, and it is not true: the callback is only invoked with publish replies, not with event messages. JavaScript and Java behaves exactly the same.
Do you have a test case that reproduces that behavior ?

CometD fully supports the request/response style, via "remoteCall". There are explicit APIs for the server side and the JavaScript client side; explicit APIs for the Java side are coming, but it is currently possible to mimic the same functionality with a couple more lines of code.

The usage of callbacks is not limited in any way. 

I think you are confusing a "callback" with a "message listener".

When you do:
```javascript
cometd.publish("/channel", {}, function(reply) { ... });
```
then that function is a "callback" invoked only once to signal that the message arrived to the server. The message passed to the callback is a "publish reply message" and it's an internal Bayeux message: applications do not generate it, the implementation does.

When you do:
```javascript
cometd.subscribe("/channel", function(message) { ... });
```
then that function is a "message listener", it is invoked every time the application (or the server via broadcasting) emits a message on that channel.

If you want a request/response style you do this:
```javascript
cometd.remoteCall("rpc", {}, function(response) { ... });
```
the function is a "message listener", it is invoked only once when the response message generated by the application is returned to the client.

Because all messages sent on `/meta/*` channels are special because they are not event messages, the concept of callback and message listener for meta messages coincide, but that is only a degenerate case of the more general case implemented for event messages.

I hope this makes things clearer, and I am interested in your feedback about how to improve the documentation to avoid this confusion.

**Comment by mskotnikov** [comment]
> In fact, I just checked, and it is not true: the callback is only invoked with publish replies, not with event messages. JavaScript and Java behaves exactly the same.
Do you have a test case that reproduces that behavior ?

I am not sure what you mean by "event messages", this discussion is only about publish replies, which can actually contain custom "data" fields if a server side business service puts it there (the technique was demonstrated above).
It is how JavaScript client code looks like:
```javascript
    function _joinSession(sessionToken, role, cb) {
      var message = {
        sessionToken: sessionToken,
        role: role
      };
      // CB-607: tell server this browser needs his css "chunked" (i.e. it is ie<10)
      if (!support.longStylesheets) {
        message.chunkCss = true;
      }
      _getCometD().publish(channels.SESSION_JOIN, message, function(response) {
        // Note that in case of unsuccessful join response.data
        // is undefined. In this case it is responsibility of
        // calling code to handle join failure.
        var joinMessage = response.data || {};
        // cache user token
        if (joinMessage.userToken) {
          _setUserToken(joinMessage.userToken);
        }

        // Don't let CometD eat my exceptions
        _.defer(function() {
          cb(joinMessage);
        });
      });
    }
```
> CometD fully supports the request/response style, via "remoteCall". There are explicit APIs for the server side and the JavaScript client side

Interesting to know. 3 years ago when our business protocol was designed on top of Bayeux this feature was not available.
Actually we emulate similar functionality via service channels. What is possible with remoteCall and what is not possible with publish reply is to have asynchronous processing on server side.

> The message passed to the callback is a "publish reply message" and it's an internal Bayeux message: applications do not generate it, the implementation does.

Normally (be default) - yes, but server side handler can alter the reply message:
```java
requestMessage.getAssociated().setData(responseData);
```
And thus have control on what is sent back in reply.

> I hope this makes things clearer, and I am interested in your feedback about how to improve the documentation to avoid this confusion.

I think documentation does a very good job on explaining CometD concepts and usage.

Here I bring a specific type of usage that used to work (and fortunately still works) for JavaScript client to Java server communication.
Having remoteCall feature I will understand if you don't want to enable similar support for Java client.

**Comment by sbordet** [comment]
> This discussion is only about publish replies, which can actually contain custom "data" fields if a server side business service puts it there:
> `requestMessage.getAssociated().setData(responseData);`

This is really wrong, and you must not do it because you are interfering with the Bayeux protocol.
For example, this will break the acknowledgement extension, and the callback mechanism - as you noticed.

Can I ask you why you are doing this instead of just sending back an event message ?
An "event message" is a message that is published by the server to client(s).

Either use the `remoteCall` mechanism, or just deliver back to the client a message in this way:
```java
public void onRequestMessage(ServerSession session, ServerMessage requestMessage)
{
    session.deliver(null, requestMessage.getChannel(), responseData);
}
```
The above solution allows for asynchronous processing of the `requestMessage` on server side, like the `remoteCall` mechanism does. 

If the processing is synchronous, the publish reply and the event message are delivered efficiently by CometD (typically in the same HTTP response).

For your example above, I think `remoteCall` is best because you will have the context that you need:

```javascript
var requestData = {
    sessionToken: sessionToken,
    role: role
};
cometd.remoteCall("/join", requestData, function(reply)
{
    var joinMessage = reply.data;
    // Do something
});
```
