### ISSUE TITLE
CometD experience problems if order of invocation of method of ServerEndpointConfig.Configurator is not the one it expect

### ISSUE THREAD

**Issue by dpelevin** [cometd/cometd#611]
Current implementaion of WebSocketTransport expects that
ServerEndpointConfig.Configurator.modifyHandshake()
is called before
ServerEndpointConfig.Configurator.getEndpointInstance()

In the case getEndpointInstance() is called before modifyHandshake() we getting situation with WebSocketScheduler initialized with 'null' WebSocketContext.

Not all web containers guaranty the order expected by CometD. For example, 'WAS Liberty with Java EE 7 Web Profile' 8.5.5.7 does not (https://developer.ibm.com/wasdev/downloads/liberty-profile-using-non-eclipse-environments/).

It is hard to call 'incorrect' order of invocation as bug of the web container, because JSR-356 does not specify order of Configurator method invocation.

It make sense to change implementation of WebSocketTransport to one expecting that getEndpointInstance() could be called before modifyHandshake().

**Comment by joakime** [comment]
While it doesn't specify in the spec an order, there's really only 1 way to implement it if you want to support both the RFC6455 and the Basic functionality of the JSR356 feature set.

See [discussion on stackoverflow about how to obtain the HttpSession from within a JSR356 upgrade](http://stackoverflow.com/questions/17936440/accessing-httpsession-from-httpservletrequest-in-a-web-socket-serverendpoint/17994303#17994303) for details on this order.

**Comment by joakime** [comment]
In short, you have to `modifyHandshake()` before `getEndpointInstance()` if you want to carry anything over from the handshake to the instance, or possibly even instantiate a different instance/implementation of the endpoint based on information gleaned during that handshake.

Doing it as `getEndpointInstance()` then `modifyHandshake()` is just a bad implementation that WAS has.

**Comment by dpelevin** [comment]
I am agree with you about quality of WebSphere implementation. And I know that Tomcat devs have to change their implementation to have correct calls order (https://bz.apache.org/bugzilla/show_bug.cgi?id=56025).

But current behavior of CometD library is also not the best one. Here how it looks:
1) I am taking web container which implements JSR356 (we will not talk about quality of implementation for now).
2) I am taking the library implemented on top of JSR356.
3) And finally I am trying to make it work with this web container.
Result: Nothing works! WTF?!
The only thing I can think is that there is bug in the library as how will doubt in the quality of IBM's product ;)

So if there is no safe way to implement WebSocketTransport to handle getEndpointInstance() before modifyHandshake(), then it make sense to notify developer, that library running in the evvironment with bad/incorrect implementation of JSR356. It looks that it is possible to implement such check and at least it will not make CometD looks as a buggy library.

I am currently reading and trying to understand all details of discussion at StackOverflow. Is there are really no way to make CometD work with such bad implementations of JSR356?

**Comment by dpelevin** [comment]
Question about code example on StackOverflow:

Http session information stored in ServerEndpointConfig during execution of modifyHandshake() then it is extracted from ServerEndpointConfig during execution of open(Session session, EndpointConfig config). It this implementation is correct, the lets look at the current implementation of CometD and the implementation of WebSphere:

**Current implementation of CometD** expect the following order of method calls:
1). ServerEndpointConfig.Configurator.modifyHandshake() - [creating WebSocketContext and storing http session](https://github.com/cometd/cometd/blob/3.0.5/cometd-java/cometd-java-websocket/cometd-java-websocket-javax-server/src/main/java/org/cometd/websocket/server/WebSocketTransport.java#L245).
2) ServerEndpointConfig.Configurator.getEndpointInstance() - [setting WebSocketContext by passing it to the constructor of Endpoint](https://github.com/cometd/cometd/blob/3.0.5/cometd-java/cometd-java-websocket/cometd-java-websocket-javax-server/src/main/java/org/cometd/websocket/server/WebSocketTransport.java#L281).
3) Endpoint.onOpen(Session wsSession, EndpointConfig config)

**WebSphere implementation** provides the following order of method calls:
1) ServerEndpointConfig.Configurator.getEndpointInstance()
2) ServerEndpointConfig.Configurator.modifyHandshake()
3) Endpoint.onOpen(Session wsSession, EndpointConfig config)

**Possible implementation** to handle the problem:
1) ServerEndpointConfig.Configurator.getEndpointInstance()
2) ServerEndpointConfig.Configurator.modifyHandshake() - [creating WebSocketContext and storing http session](https://github.com/cometd/cometd/blob/3.0.5/cometd-java/cometd-java-websocket/cometd-java-websocket-javax-server/src/main/java/org/cometd/websocket/server/WebSocketTransport.java#L245).
3) Endpoint.onOpen(Session wsSession, EndpointConfig config) - [setting WebSocketContext during execution of onOpen() method](https://github.com/cometd/cometd/blob/3.0.5/cometd-java/cometd-java-websocket/cometd-java-websocket-javax-server/src/main/java/org/cometd/websocket/server/WebSocketTransport.java#L181).

Why it can't be implemented in such way?

**Comment by joakime** [comment]
OK, from the JSR356 spec document.

The only prescribed place to access the HandshakeRequest and HandshakeResponse is outlined in Section 3.1.5 (Handshake modification), and this is limited to the modifyHandshake()

You cannot cast the EndpointConfig obtained during the onOpen events to anything else.  The contract is only an EndpointConfig, even in server operations, even with custom EndpointConfigs.

And no, you cannot cast to a ServerEndpointConfig.

ServerEndpointConfig.Configurator.getEndpointInstance() is free to return any "instance of" the specified class in that configuration.  This even includes other classes derived from the stated class.  Completely controlled by the implementation of the ServerEndpointConfig.Configurator.

example:

    @ServerEndpoint("/foo")
    public class FooSocket {
       @OnMessage
       public void onMessage(String msg) {
           handleMessage(msg);
       }
       public void handleMessage(String msg) {
           // normal processing
       }
    }

    public class BarSocket extends FooSocket {
        public void handleMessage(String msg) {
           // special processing
        }
    }

    public class FooConfig extends ServerEndpointConfig.Configurator
    {
        private boolean barMode = false;

        public void modifyHandshake(ServerEndpointConfig sec, HandshakeRequest request, HandshakeResponse response)
        {
            barMode = request.getQueryString().contains("bar");
        }
        public <T> T getEndpointInstance(Class<T> endpointClass)
        {
            if ( barMode ) return new BarSocket();
            else return new FooSocket();
        }
    }

Again, modify occurs before getEndpointInstance()

To address your "Possible implementation"

  1. ServerEndpointConfig.Configurator.getEndpointInstance()
  2. ServerEndpointConfig.Configurator.modifyHandshake() - creating WebSocketContext and storing http session
  3. Endpoint.onOpen(Session wsSession, EndpointConfig config) - setting WebSocketContext during execution of onOpen() method.

Where do you store the HttpSession?

The normal ServerEndpointConfig.Configurator isn't created per connection, it exists as a single instance at Container initialization.   This is how the actual javax.websocket.server.ServerEndpointConfig code works. Look it up.

If someone decides to completely extend ServerEndpointConfig and change the behavior of ServerEndpointConfig.getConfigurator() to return a new Configurator per call, that's up to them, just know that the various JSR356 implementation cannot rely on that behavior as default.  They can only rely on the *actual* (as implemented by the spec) default behavior.

By the time you have called getEndpointInstance() its too late to call modifyHandshake() as all of the decisions about *what* endpoint instance to return have already been made (origin, extensions, sub-protocol, request headers, etc...)

The folks that use ServerEndpointConfig.Configurator.getEndpointInstance() to construct an endpoint instance based on information from the request are also penalized in the WAS solution.
Perhaps they have an alternative authentication scheme.  Perhaps they have api-keys as request headers.

For another angle of this argument ...

  * Jetty, Tomcat, and Tyrus follow the same ordering (at last investigation of this).  Why not WAS?

**Comment by dpelevin** [comment]
Thanks for your detailed explanation.

Now it is absolutely clear that there is no sutable way to make CometD work with broken webscoket implementation like one provided by WAS.

I've mixed up ServerEndpointConfig.Configurator with EndpointConfig when I was looking through CometD sources:
```
ServerEndpointConfig.Builder.create(WebSocketScheduler.class, mapping)
					.subprotocols(protocols).configurator(new Configurator(context)).build();
try {
	container.addEndpoint(config);
} catch (DeploymentException x) {
	throw new RuntimeException(x);
}

```
the line with instantiation of personal ServerEndpointConfig.Configurator for the endpoint was source of my confusion.

I will close this issue as there is no point to left it open.
