### ISSUE TITLE
Please expose request.getLocale() in BayeuxContext

### ISSUE THREAD

**Issue by fdummert** [cometd/cometd#615]
Could you please consider to also expose getLocale() in the BayeuxContext - just by delegating to request.getLocale()? Implementation on that end would be trivial and would save quite some effort for the app developer.
Thanks, Florian

**Comment by sbordet** [comment]
It's trivial for HTTP and Jetty WebSocket, but not available for JSR356 WebSocket. Will figure something out for that. 
Thanks!

**Comment by sbordet** [comment]
Exposing `List<Locale> getLocales()` instead of just `getLocale()`. That good for you ?

**Comment by fdummert** [comment]
Would this list be sorted in a reliable way, like: order of matching quality? Than it would be fine, of course!

**Comment by sbordet** [comment]
Yes, the list will be sorted based on the `Accept-Language` header and their `q` attributes.
The list will also be never null and never empty (if the `Accept-Language` header is absent, the default locale of the server will be present as the only element).

**Comment by fdummert** [comment]
That sounds like a very good plan, thanks a lot!
