### ISSUE TITLE
Exception on multi-byte channel names

### ISSUE THREAD

**Issue by cgailey** [cometd/cometd#620]
I'm receiving a java.lang.IllegalArgumentException when trying to subscribe to a multi-byte channel name "/crowds/कमल", and the server then disconnects.  This was working fine for me with v2.7, but I started experiencing the exception once I upgraded to v3.0.6.  Otherwise other channel subscriptions and messages are working fine.
Following is the client side debug output:

[Log] arrived _metaConnect: (chat.js, line 1605)
[Log] { (chat.js, line 1606)
    "id": "6",
    "successful": false,
    "channel": "/meta/connect",
    "failure": {
        "websocketCode": 1011,
        "reason": "java.lang.IllegalArgumentExcep",
        "connectionType": "websocket",
        "transport": {},
        "message": {
            "id": "6",
            "channel": "/meta/connect",
            "connectionType": "websocket",
            "clientId": "b1y1v7u62c3id8pmhfoy76plvq"
        }
    }
}
[Log] _connectionBroken (chat.js, line 1580)
[Log] postManager.chatSessionDisconnected() (postManager.js, line 203)
[Log] ochloi.postMessage.chatSessionDisconnected() (postMessage.js, line 630)
[Log] Status,connected,->,connecting (CometD.js, line 188)
[Log] Function scheduled in,0,ms, interval =,0,backoff =,0, (CometD.js, line 188)
[Log] handleFailure,{},[ (CometD.js, line 188)
    {
        "id": "31",
        "channel": "/meta/subscribe",
        "subscription": "/crowds/कमल",
        "clientId": "b1y1v7u62c3id8pmhfoy76plvq"
    }
],{
    "websocketCode": 1011,
    "reason": "java.lang.IllegalArgumentExcep",
    "connectionType": "websocket"
}
[Log] Removed failed subscription,{ (CometD.js, line 188)
    "0": "/crowds/कमल",
    "1": 0,
    "channel": "/crowds/कमल",
    "listener": false,
    "id": 0
}

**Comment by sbordet** [comment]
CometD 3 has strengthened the validation of message fields as per the [Bayeux Specification](http://docs.cometd.org/reference/#_bayeux_protocol_elements).

The actual issue is #526, and the behavior is configurable.

I suggest you change the channel name to accept only accepted characters, but in the meanwhile you should be able to get the old behavior by turning off validation.

Closing the issue; if you still have problems, please reopen with more details.

Thanks !

**Comment by cgailey** [comment]
Hi Simone,

That makes sense.  Now that I know what is going on I can work something out.  Thanks for the great work you folk do.  CometD is really awesome!

Regards,
.cg.


> On Dec 7, 2015, at 3:38 PM, Simone Bordet <notifications@github.com> wrote:
> 
> CometD 3 has strengthened the validation of message fields as per the Bayeux Specification <http://docs.cometd.org/reference/#_bayeux_protocol_elements>.
> 
> The actual issue is #526 <https://github.com/cometd/cometd/issues/526>, and the behavior is configurable.
> 
> I suggest you change the channel name to accept only accepted characters, but in the meanwhile you should be able to get the old behavior by turning off validation.
> 
> Closing the issue; if you still have problems, please reopen with more details.
> 
> Thanks !
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/cometd/cometd/issues/620#issuecomment-162671806>.
> 

 <http://summatrix.com/>
 <http://summatrix.com/>
