### ISSUE TITLE
Broken demo on cometd-3.0.7-distribution.tar.gz

### ISSUE THREAD

**Issue by galkovsky** [cometd/cometd#622]
Hi.

I've tried to launch demo application from scratch for cometd-3.0.7-distribution.tar.gz via 'mvn jetty:run' command ( as described in documentation ) and got 
FAILED org.eclipse.jetty.maven.plugin.JettyServer@5529ff44: java.lang.NoClassDefFoundError: org/slf4j/spi/LocationAwareLogger
java.lang.NoClassDefFoundError: org/slf4j/spi/LocationAwareLogger

Demo for cometd-3.0.0distribution.tar.gz works perfect. 

I didn't go in details why this error happens. Maybe there is trivial problem. I just think that it can scare and discourage new users

Thanks.

**Comment by sbordet** [comment]
Thanks for reporting this.

I just tried myself, and everything is working correctly.

A wild guess is that Maven failed to download correctly the jar containing the referenced class, so perhaps removing the `$HOME/.m2/repository` directory and retrying will work fine.

If still does not work, can you please detail what operative system are you on ?
