### ISSUE TITLE
cometd 3.0.9 build error on Fedora 23

### ISSUE THREAD

**Issue by sandrobonazzola** [cometd/cometd#631]
cometd 3.0.9 is built against version 9.2 of Jetty, but Fedora
includes version 9.3 of Jetty, and there is an incompatibility in one of
the methods causing a build to fail wiith:

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.421 s
[INFO] Finished at: 2016-01-21T11:54:20+01:00
[INFO] Final Memory: 31M/366M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project cometd-java-server: Compilation failure: Compilation failure:
[ERROR] /NotBackedUp/sbonazzo/rpmbuild/BUILD/cometd-3.0.9/cometd-java/cometd-java-server/src/main/java/org/cometd/server/ext/BatchArrayQueue.java:[168,5] method does not override or implement a method from a supertype
[ERROR] /NotBackedUp/sbonazzo/rpmbuild/BUILD/cometd-3.0.9/cometd-java/cometd-java-server/src/main/java/org/cometd/server/ext/BatchArrayQueue.java:[176,23] cannot find symbol
[ERROR] symbol: method grow()
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cometd-java-server
error: Bad exit status from /var/tmp/rpm-tmp.P5lJoO (%build)

Can you please rebase on Jetty 9.3?
Thanks

**Comment by sbordet** [comment]
No, CometD 3.0.x cannot be rebased on Jetty 9.3 because it needs to keep compatibility with JDK 7.

CometD 3.1.x will be out hopefully soon, and after that CometD 4.0.x will be based on Jetty 9.3.x.

**Comment by sandrobonazzola** [comment]
Any ETA or link to a schedule for CometD 4.0.x? Java 7 EOL was on April 2015.

**Comment by sbordet** [comment]
I know that Java 7 was EOL some time ago, but JDK 8 is not available in Android. We need to make some compromise.

CometD 4.0.x is scheduled for February-March 2016, but the schedule may vary.
