### ISSUE TITLE
CometD doesn't include the license file

### ISSUE THREAD

**Issue by puntogil** [cometd/cometd#632]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
thanks
regards

**Comment by sbordet** [comment]
Sorry, but in the guidelines you linked I don't see any reference that a file name `LICENSE` should be in the directory structure; am I missing something ?

I don't mind adding it if it's really needed, but I don't want to add files that are not used.

**Comment by puntogil** [comment]
hi
from second line of LicensingGuidelines#License_Text: "If the source package does not include the text of the license(s), the packager should contact upstream and encourage them to correct this mistake. "



Despite that it is licensed under Academic Free License, v. 2.1 and and Apache 2.0, and BSD  (?)
license, it is still licensed, and that needs to be made clear. This is necessary for two reasons:

 -  Not licensed code, read code not licensed under a certain license or missing any license information has to be assumed to be not licensed. Which means that it defaults to "all rights reserved" which pretty much means "don't touch, and sometimes better don't look at it". Adding a license file and header to the source makes this absolutely clear without any question.
-  Currently the repository does not contain any license information. The only site containing this info is the AMO page. So, let's assume that the AMO page goes away for some reason, it can not be verified that the code in this repository is licensed under MPL, which means point 1 gets into effect.

Adding the license information does remove any ambiguity and clearly indicates your intentions.

**Comment by sbordet** [comment]
But every source file (*.java and *.js) does contain the license header, so the source package does include the text of the license. IIUC, that is enough to comply with the above.

Or perhaps I don't understand what "source package" means ?

Can you clarify ?

Merely adding a file called `LICENSE` in the root of the source tree does not seem to qualify either as complying with the bullets you report above. 

Certainly the guidelines do not mention any file called `LICENSE`, so at this point I am confused at what exactly those guidelines require.

**Comment by puntogil** [comment]
The following source files are without license headers.
Please, confirm the licensing of code and/or content/s, and add license headers
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification
 cometd-javascript/common/src/main/js/org/cometd/CallbackPollingTransport.js
 cometd-javascript/common/src/main/js/org/cometd/cometd-amd.js
 cometd-javascript/common/src/main/js/org/cometd/cometd-header.js
 cometd-javascript/common/src/main/js/org/cometd/cometd-json.js
 cometd-javascript/common/src/main/js/org/cometd/cometd-namespace.js
 cometd-javascript/common/src/main/js/org/cometd/CometD.js
 cometd-javascript/common/src/main/js/org/cometd/LongPollingTransport.js
 cometd-javascript/common/src/main/js/org/cometd/RequestTransport.js
 cometd-javascript/common/src/main/js/org/cometd/Transport.js
 cometd-javascript/common/src/main/js/org/cometd/TransportRegistry.js
 cometd-javascript/common/src/main/js/org/cometd/Utils.js
 cometd-javascript/common/src/main/js/org/cometd/WebSocketTransport.js

**Comment by sbordet** [comment]
The files you mention are split only for development reasons. 

During the build they are composed in a single file called `cometd.js` that does have the license header, which is provided by file `cometd-header.js`.

The file `cometd.js` is what is distributed, so it should comply with the guidelines because it does have the license header.

Is that enough to comply ?

**Comment by puntogil** [comment]
> Or perhaps I don't understand what "source package" means ?
for "source package" we intend:
- the source structure present in a branch or a tag on your git repository
- the downdable source archive always by your git repository
> Can you clarify ?

In the previous release there is a folder in the previous
https://github.com/cometd/cometd/tree/3.0.8/LICENSES
what I mean and you add in place at least the licenses listed on the parent pom

> Merely adding a file called LICENSE in the root of the source tree does not seem to qualify either as > complying with the bullets you report above.

> Certainly the guidelines do not mention any file called LICENSE, so at this point I am confused at >what exactly those guidelines require

You can call COPYRIGHT(.txt, .md, .html ) or in another way, 
but does not change the fact that the file "license (s)" does not exist

**Comment by sbordet** [comment]
Can you please confirm that after this commit CometD complies ? Thanks !

**Comment by puntogil** [comment]
Yes, sure. Again thanks
