### ISSUE TITLE
Extensions as middlewares

### ISSUE THREAD

**Issue by chchrist** [cometd/cometd#633]
Hello,

In order to authenticate with our server, we need to pass a token that we get from another endpoint.
When the user handshakes the first time is easy to just get the token and then handshake, but the re handshake happens automatically. This causes a handshake denied error cause of authentication. We can't solve this with an extension because we can't prevent the message from being send ( correct me if I'm wrong).

Is it a good idea to add middleware functionality to extensions that will execute the next action only when you call next(); So before any publish to /meta/handshake I could make that token call and the proceed to the message to the server.

**Comment by sbordet** [comment]
Thanks for reporting this !

I'm not sure I understand well your definition of "middleware". From what I understand, a `next()` is not really making me excited about, on the contrary.

An extension can prevent the message to be sent; it is enough to return `null` from the JavaScript function, or `false` from `ClientSession.Extension.sendMeta()`.

The application can then re-authenticate and re-handshake.

This authentication model can be coded in an extension, even for the first handshake. I have not done it myself, but I don't see why it would not be possible to do it.

Give it a try, and report back if you could successfully implement your use case.

**Comment by chchrist** [comment]
Thanks for but I was not very clear. I am talking about a javascript extension.

**Comment by sbordet** [comment]
@chchrist me too. What I wrote previously applies to the JavaScript client library too.

**Comment by chchrist** [comment]
OK, returning null in the outgoing method prevents the message to be sent. I suppose there is no way to resume the message so I have to handshake again from within the extension?

**Comment by sbordet** [comment]
Exactly.

As I was saying, since you will need to handshake from within the extension, and you can handshake only after having gotten a token, you can put this logic (getting the token and handshaking) into the extension, and it will be triggered for any handshake.

**Comment by sbordet** [comment]
Are you good with the proposed solution ? Can I close this issue ?

**Comment by chchrist** [comment]
It isn't working actually. If I return false in the outgoing method the message will be prevented. But if I try to do something async before returning false cometd library will continue sending the message with false as a parameter...

```
"{"url":"https://domain.com/cometd/handshake","sync":false,"messages":[false]}"
```

**Comment by chchrist** [comment]
```
outgoing(message) {
    if (message.channel === '/meta/handshake') {
      this._getToken().then(token => {
        this.cometd.handshake({
          token
        })
      }).catch(res => {
        //TODO something meaningful
      })
      return false;
    }
  }
```

**Comment by sbordet** [comment]
You should return `null` if you're using the JavaScript library.

**Comment by chchrist** [comment]
This is what I have so far which seems to work but I haven't tested thoroughly
https://gist.github.com/chchrist/1b7d2cd2c6ed03b0b185

**Comment by chchrist** [comment]
Hello @sbordet I'm closing this issue cause the extension works fine. Of course there is space for improvement
