### ISSUE TITLE
OSGi split package for websockets

### ISSUE THREAD

**Issue by rocketraman** [cometd/cometd#637]
Both the bundle `cometd-java-websocket-common-server` and `cometd-java-websocket-javax-server` export the same package: `org.cometd.websocket.server`.

This is called a "split package" in OSGi and its a best practice to avoid it. It makes using cometd websocket under OSGi difficult.

**Comment by rocketraman** [comment]
In addition, the "[standard](http://wiki.osgi.org/wiki/Split_Packages)" solution of using `Require-Bundle` and marking the package as split does not work, because we have an inner class trying to access a protected member of the Abstract base class (https://github.com/cometd/cometd/blob/master/cometd-java/cometd-java-websocket/cometd-java-websocket-javax-server/src/main/java/org/cometd/websocket/server/WebSocketTransport.java#L277), and since they are in two different classloaders, you get an java.lang.IllegalAccessError at runtime.

**Comment by sbordet** [comment]
Suggestions on how to fix this ?

**Comment by rocketraman** [comment]
The best way is to move the Abstract common class into a different package called `common`. I'll submit a pull request for you.
