### ISSUE TITLE
Salesforce Streaming not working over http proxy

### ISSUE THREAD

**Issue by vijaychd** [cometd/cometd#644]
403 error faced for subscribing to topic in Salesforce with http proxy.  Without proxy, it works fine.
 INFO y --- [  HttpClient-19] o.cometd.client.BayeuxClient.x  : Processing meta connect {clientId=x, advice={reconnect=handshake, interval=500}, channel=/meta/connect, id=z, error=403::Unknown client, successful=false}

Need patch for version:
cometd-java-client-2.4.3

**Comment by sbordet** [comment]
CometD does not reply with `403::Unknown client`. Perhaps it's a modified version of CometD.

Have you tried to configure the HTTP proxy on `HttpClient` ?

Note that both CometD 2.x and Jetty 7.x (used by CometD 2.x) are end-of-life.

**Comment by vijaychd** [comment]
Yes proxy is configured for HttpClient.

error is reported from 
org.cometd.client.BayeuxClient

If i remove proxy,  it works fine.  But we have to use proxy for implementation.

I need to use 2.4.3 version as camel latest version supports that version only.

**Comment by sbordet** [comment]
Too little information to help. DEBUG logs or a network trace can show what's going on.

**Comment by vijaychd** [comment]
which DEBUG logs you are looking for ?
is it for org.cometd.client.BayeuxClient?

**Comment by sbordet** [comment]
Yes, client DEBUG logs. If you have server's even better.

**Comment by vijaychd** [comment]
[log.txt](https://github.com/cometd/cometd/files/208695/log.txt)

**Comment by vijaychd** [comment]
i got feedback from Salesforce support.
"Adjust proxy to not strip the cookies"

Does that help to make adjustment in the API or changes are needed in the Proxy?

**Comment by sbordet** [comment]
If the proxy strips the cookies, you need to change the proxy to not to that.

**Comment by saisfdc21** [comment]
Hi, we have the same issue connecting through https://cs43.salesforce.com but the handshake was successfull for https://cs22.salesforce.com
Is there any work around to use the same connections with in the proxy? we can successfully connect ouside the proxy. 
The below error was for https://cs43.salesforce.com when we connect using proxy
Login successful!

Server URL: https://cs43.salesforce.com

Session ID=***!AQEAQDMbBWhYPlSXmvdouxmMbYtSn.PVb_41dzPu8kyIbCIYu38_QF9DFKq6gwOLbEB4e43eqWv7SO.ONKtYLg1vqMBbFLKu

Waiting for handshake

[CHANNEL:META_HANDSHAKE]: {id=1, minimumVersion=1.0, supportedConnectionTypes=[Ljava.lang.Object;@2cb1a911, successful=true, channel=/meta/handshake, clientId=98bt7zp41oz83s1uzcimbdd10c2, version=1.0}

[CHANNEL:META_CONNECT]: {id=2, error=403::Unknown client, successful=false, advice={interval=500, reconnect=handshake}, channel=/meta/connect, clientId=98bt7zp41oz83s1uzcimbdd10c2}

Error during CONNECT: 403::Unknown client

Exiting...

**Comment by vijaychd** [comment]
I am having same issue.  Salesforce believes proxy is dropping the cookies.  Unfortunately it is not resolved as changing proxy is a big deal.  Wondering if jetty or cometd can handle that.

**Comment by sbordet** [comment]
Not much that CometD or Jetty can do, if it is the proxy that strips out the cookies, and you cannot control the server, sorry.

**Comment by vijaychd** [comment]
saisfdc21,  are you still facing issue?  Per salesforce,  they have resolved the issue but i am still getting the problems.

**Comment by theGribbler** [comment]
This happens when a cometd client is not loaded into the code. Properly load the cometd client and it worked for me
