### ISSUE TITLE
How can our iOS client can communicate with cometd server.

### ISSUE THREAD

**Issue by piweihwt** [cometd/cometd#651]
Our Server using cometd, client is mobile. Android now is ok, But how can I do with iOS.

**Comment by sbordet** [comment]
Unfortunately, there is no open source client support for iOS maintained by CometD.
There are no plans to support it, for now.

**Comment by jaypatel512** [comment]
Has there been any changes to this ? We are hoping to use cometd for our mobile native integration as well and were wondering if that is an approach we can do. Also, if not, are there any alternatives without redesigning our entire code to support both cometD and non-cometD versions @sbordet !

Thanks.

**Comment by sbordet** [comment]
@jaypatel512 no changes to this. 

We have not had many requests for an iOS client, and apparently not many are interested in writing one and maintaining it. Unless there is some sponsoring or contribution, I don't see this changing in the near future, sorry.

As a reminder for readers of this issue, it is possible to sponsor CometD development via [Webtide's commercial support](https://docs.cometd.org/current/reference/#_support).

**Comment by oohusl** [comment]
@piweihwt @jaypatel512 @sbordet  We plan to contribute a client for swift language .

**Comment by sbordet** [comment]
@oohusl can you detail your contribution? 
Is it already done? 
Already public somewhere? If not, when?

**Comment by oohusl** [comment]
@sbordet  just starting and expect a release in February 2020

**Comment by digvijayu** [comment]
@oohusl is it released? where can I find it?
