### ISSUE TITLE
this.setTimeout is undefined

### ISSUE THREAD

**Issue by DPr00f** [cometd/cometd#665]
Hi guys,
https://github.com/cometd/cometd/blob/master/cometd-javascript/common/src/main/js/org/cometd/WebSocketTransport.js#L160
If you take a look at that line, `this` is undefined because it's wrapped in a self invoking function.
This wasn't noticeable before because `this` would fallback to `window`. But if you prevent that fallback, the script will throw at that line.

**Comment by chchrist** [comment]
@DPr00f pull request?

**Comment by DPr00f** [comment]
Fair enough. Will do it this afternoon.
