### ISSUE TITLE
OortObject synchronization issues

### ISSUE THREAD

**Issue by fdummert** [cometd/cometd#667]
Hi Simone,

when doing more advanced fail-over tests with an Oort cluster, we're experiencing Oort map synchronization issues, additionally we discovered NPE's in our logs. We took the latest snapshot jar, including your fix for the issue #664. The synchronization issues are happening always and reproducible with the setup described below, the NPE happens intermittently and seems not to be the cause, but likely a symptom.

**Setup:**
We're having two nodes and we're interrupting the network connection between the nodes (we experienced it on our production platform with a powered-off switch between the nodes, we reproduced it with a firewall that blocks the connection between the nodes). In this setup, the clients  can still connect to the "separated" nodes. Then we're restoring the network connection between the nodes.

1) **Synchronization issue**: In our scenario, node A notices that node B has left, while node B can't see that node A has left, because the existing socket on B never gets a "closed" event. When the network connection is restored, node A notices that B joins, while B does not notice that A is back again. Now A does not see Oort map entries of B, until there is a change in B's map, which will then transmit the map to A. Still B sees stale data of A (which it got before the connection was gone). 
Is there some way to enable keep-alive messages between the nodes? This could help all nodes to identify a broken connection reliably and react accordingly.

2) **NPE**: We found following stacktrace in our log, repeatedly, but not always. Seems like an info object in the collection can be null under some conditions in conjunction with the scenario described above:
```
java.lang.NullPointerException
        at org.cometd.oort.OortObjectMergers$ConcurrentMapUnionMerger.merge(OortObjectMergers.java:80) ~[cometd-java-oort-3.1.0-SNAPSHOT.jar:?]
        at org.cometd.oort.OortObjectMergers$ConcurrentMapUnionMerger.merge(OortObjectMergers.java:74) ~[cometd-java-oort-3.1.0-SNAPSHOT.jar:?]
        at org.cometd.oort.OortObject.merge(OortObject.java:390) ~[cometd-java-oort-3.1.0-SNAPSHOT.jar:?]
```

Best Regards,
Florian

**Comment by sbordet** [comment]
Florian, there already are keep-alive messages between nodes, on the `/meta/connect` channel.

Each `OortComet` that connects from one node to another sends those messages. The time for them to detect that a node is gone is the server's `timeout` + the client's `maxNetworkDelay`.

I'll try to reproduce your case. If you have the logs, especially those that show that B does not notice that A is gone, will be great.

When A notices that B rejoins, it pushes its whole content. If B still sees stale A data after, then that is really strange. Logs for that will be great too.

**Comment by fdummert** [comment]
Hi Simone, 

here are detailed logs of a test run with both nodes and a little description what was performed at what timestamp. Hope it helps. Nice weekend!

Best Regards,
Florian
[oort-test.zip](https://github.com/cometd/cometd/files/378400/oort-test.zip)

**Comment by sbordet** [comment]
Florian,

the failure you are triggering is a _half_ disconnection, because node B cannot heart-beat to node A, but node A _can_ heart-beat to node B.

In this scenario, after a while node A considers B gone, but not viceversa.

When node B is able to reconnect, node A pushes its information to B, which already has A's part, and therefore does not push its own part to A.

I fixed it by forcing push replies every time a node receives an explicit push.

Note also that I fixed #671 (that was introduced by #664).

Let's open another issue for the NPE, if you see it again (could have been caused by #671).

Can you test the latest code ?

**Comment by fdummert** [comment]
Hi Simone,
the latest code appears to behave much better (still we'll continue trying to break it :-)). 
But one question remains: As we know, node A sees that node B is gone while node B still keeps data for node A. Node A gets a proper cometLeft event (I'm assuming because of missing heart-beats from B, right?). Node B is getting exceptions (because it cannot send messages to node A), but never gets a cometLeft event (I'm assuming because it still gets heart-beats from A, right?). This behaviour is still the same with the latest code. Reconnection, however, seems to get everything into sync again, which should fix most of the practical issues.
But: is it ok that B is _not_ cleaning up A and does _not_ trigger a cometLeft? B is getting exceptions and this should indicate there is something wrong. The situation we are facing is somewhat tricky, for sure. In our application, I'd still strongly prefer to clean up B. If the framework doesn't do it, do I have a chance to catch this condition and do it from within my application?
Best Regards,
Florian

**Comment by sbordet** [comment]
Florian,

in Oort, node disappearance (and appearance) is performed by the server-side mechanisms.

Imagine node A and B (the servers); each node has an `OortComet` (the client) connecting to other nodes. Node A has `oortCometAB`, while node B has `oortCometBA`.

A "normal" disconnection breaks the communication of both `oortCometAB` and `oortCometBA`, so the servers won't see the heartbeats and eventually the server-side session sweeping mechanism will trigger a `comet left` event in both nodes.

An `oortComet` does notice that the communication has been broken.
However, we have chosen to not create another timeout mechanism on the client side in competition to that already existing on the server side to fire `comet left` events.

Your case is a bit exceptional, in that only one direction sees communication failure, `oortCometBA`.
You can attach a `/meta/connect` listener to `oortComet`s, and then after a number of failures of `/meta/connect` messages you can call `BayeuxServerImpl.removeServerSession(ServerSession, boolean)`, which is the same mechanism that the server-side will trigger.

Having said _how_ you can do it, I haven't tried it, and I'm not sure I would recommend it. I suspect having to mechanisms and coordinating them could be more problems than benefits.

**Comment by fdummert** [comment]
Hi Simone,

that makes totally sense (and this scenario can be considered as an edge case anyway). Thanks a lot for your hints and explanations. I think this issue can be closed for now. I'll let you know if we find something else :-)

Best Regards,
Florian
