### ISSUE TITLE
Allow dissassociating all user sessions based on user id

### ISSUE THREAD

**Issue by zaynetro** [cometd/cometd#668]
Discussed here: https://groups.google.com/forum/#!topic/cometd-users/3hZ2xeyQ-QA

I am working on a pull request now. Base idea suggested by Simone Bordet is that we provide a method for Seti object to allow disassociating all user sessions given user id:

```
public Set<ServerSession> disassociate(final String userId);
```

I am planning to submit work in progress pull request as I am lacking familiarity with cometd project and may miss some important points.

**Comment by sbordet** [comment]
Thanks !

Please be sure to follow the [contribution guidelines](https://docs.cometd.org/current/reference/#_contribute_code).
