### ISSUE TITLE
To use cometd in C#

### ISSUE THREAD

**Issue by seljhas** [cometd/cometd#677]
Hi, I need to use cometd on c# as client. Can I do this implementation? 

I am using the library cometd.net, but, the server return me this message:

WARN  o.c.server.BayeuxServerImpl.1fca68f - 4k6r3bunx0clq2139bx7s3gba60 - last connect 2617 ms ago denied Subscribe@/meta/connect by org.cometd.server.DefaultSecurityPolicy
Any Can you help me?

**Comment by sbordet** [comment]
You cannot subscribe to the `/meta/connect` channel.
Please read the documentation about the CometD concepts: https://docs.cometd.org/current/reference/#_concepts.

The CometD project does not maintain a C# library, but there are a couple of projects that seem to have implemented a C# CometD client, see https://github.com/Oyatel/CometD.NET and https://github.com/nthachus/CometD.NET.

**Comment by seljhas** [comment]
I am using the C# Cometd client:  https://github.com/Oyatel/CometD.NET, but, 
I did not understand the message that return me the server.

Thanks for your support!

**Comment by sbordet** [comment]
A CometD client cannot _subscribe_ to channel `/meta/connect`.
It can add a listener to channel `/meta/connect`, but not a subscriber.
This is explained in the documentation that I linked.

Now, typically this error is done by applications, so you are trying to subscribe to `/meta/connect` and the server tells you that you can't do that.

If you are not doing this, then perhaps CometD.NET is doing it, but that would be incorrect.
