### ISSUE TITLE
Version 2 documentation 

### ISSUE THREAD

**Issue by cferriby** [cometd/cometd#680]
Can https://docs.cometd.org/ please have the older version 2 docs available? 
Salesforce servers are still using version 2 of the cometd libraries, which is a pretty large base of developers. It would be nice if there was an easy link to look at the older versions of the documentation.

**Comment by sbordet** [comment]
Done. Note that SalesForce has customized CometD 2, so it may be that the official CometD 2 documentation is not valid for SalesForce usage. You may want to refer to their documentation.
