### ISSUE TITLE
Warning during Tomcat shutdown

### ISSUE THREAD

**Issue by boris-petrov** [cometd/cometd#682]
I have an application which uses CometD and runs in Tomcat 8. When the server is shutting down, the following warning appears:

`
SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [myapp] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@6cf7047e]) and a value of type [org.cometd.websocket.server.WebSocketTransport.ContextHolder] (value org.cometd.websocket.server.WebSocketTransport$ContextHolder@17eed49f]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
`

I guess it is because of [this](https://github.com/cometd/cometd/blob/c20b75f79d18ff149404b2f2502c9fb0a805b0b6/cometd-java/cometd-java-websocket/cometd-java-websocket-javax-server/src/main/java/org/cometd/websocket/server/WebSocketTransport.java#L284) not being removed.

**Comment by sbordet** [comment]
Thanks for reporting this !

Would you be able to test the latest code with the fix and report back if the warning is gone ?

**Comment by boris-petrov** [comment]
Hi, I'm having some troubles running my code with the SNAPSHOT build (the front-end doesn't want to connect to the server), but by looking at the commit - why don't you use [ThreadLocal.remove](https://docs.oracle.com/javase/7/docs/api/java/lang/ThreadLocal.html#remove()) instead of `set(null)`?

**Comment by sbordet** [comment]
Because I don't need to remove the `ThreadLocal` itself, just unset its value.
Removing the `ThreadLocal` will incur in possible creation of a `WeakReference` the next time it is accessed, causing more pressure on the GC to clear references.

**Comment by boris-petrov** [comment]
:+1:  Thanks for the quick resolution!

**Comment by sbordet** [comment]
Does it make the warning go away ?

**Comment by boris-petrov** [comment]
I cannot get my application to work fine with the code from the `3.0.x` branch. I am getting a `Error during WebSocket handshake: Unexpected response code: 200` but as I said, probably I'm doing something wrong. The error doesn't appear in the log when I stop the server, however it might be because no client is ever connected to it.

**Comment by sbordet** [comment]
A `200` received for a WebSocket upgrade means that the server is not configured correctly for WebSocket, or you are pointing to the wrong context or path, so that the WebSocket machinery on the server is not triggered.

Anyway, if you get it working, let us know if it worked.

Thanks !
