### ISSUE TITLE
Cannot set ws.bufferSize on JettyWebSocketTransport beyond 32768

### ISSUE THREAD

**Issue by eggilbert** [cometd/cometd#690]
Hello -
I'm currently using CometD 3.0.5 with embedded Jetty 9.3.14.v20161028.

When I try and set the `ws.bufferSize` property using the server [JettyWebSocketTransport](https://github.com/cometd/cometd/blob/3.0.x/cometd-java/cometd-java-websocket/cometd-java-websocket-jetty-server/src/main/java/org/cometd/websocket/server/JettyWebSocketTransport.java#L68) beyond 32768, I receive the following error:

```
java.lang.IllegalArgumentException: InputBufferSize [65536] must be less than MaxTextMessageBufferSize [32768]
	at org.eclipse.jetty.websocket.api.WebSocketPolicy.assertLessThan(WebSocketPolicy.java:109)
	at org.eclipse.jetty.websocket.api.WebSocketPolicy.setInputBufferSize(WebSocketPolicy.java:276)
...
```

It looks like the Jetty [WebSocketPolicy](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-websocket/websocket-api/src/main/java/org/eclipse/jetty/websocket/api/WebSocketPolicy.java#L273-L280) class is validating that this parameter is less than the value of 2 other parameters that the `JettyWebSocketTransport` class is not configuring anywhere.

The CometD documentation says that the default value for `ws.bufferSize` is `65536`, but if I don't specify any value myself, I actually get the embedded Jetty default of `4096` instead. And then I'm unable to set the property to the default value specified in the docs because it's larger than the `32768` default for the other parameters.

Should `JettyWebSocketTransport` be setting all 3 buffer sizes equal? Or is there something I'm missing here?

**Comment by sbordet** [comment]
This is a Jetty bug that reported at eclipse/jetty.project#1149.

We need to fix the CometD documentation, since it was referencing an old default value that was later enlarged.

**Comment by sbordet** [comment]
Documentation has been fixed.

**Comment by eggilbert** [comment]
:+1:
