### ISSUE TITLE
Facing problem With cometD 3.1.0 - ServerChannelImpl publish() method

### ISSUE THREAD

**Issue by SusilPanda** [cometd/cometd#696]
Hi,

We are facing problem with new cometD 3.X version.

We are using the ServerChannelImpl.java  - publish(Session from, Object data, String id) method in cometd-java-server-2.7.0 which has been removed in the latest version(3.x ). 

Why it has been removed ?

Is there any workaround ?

Facing problem because the response from the publish method has been used by a third party , so they are unable to parse the response as the used the "id" , which has been set by setId() method which removed from the publish method in the latest version.

**Comment by sbordet** [comment]
The migration guide from 2.x to 3.x: https://docs.cometd.org/current/reference/#_migration

Field `id` is an Bayeux field that application should not deal with. If it was used to convey application data, please use an application id in an object stored in the `data` field, which is where application should put their data.
