### ISSUE TITLE
CometD and Jetty Versions chart

### ISSUE THREAD

**Issue by DeepuSahni** [cometd/cometd#697]
I have recently upgraded my jetty from 8 to 9.4 (9.4.0.v20161208) 
Was using cometD 2.7.0.

Now my code compiles with cometD 3.0.0 and Jetty 9.4
Could you please tell which is the best version of CometD to use with Jetty 9.4.
Or if I need to choose any other jetty version. 

Would like to use the latest and stable CometD version. ( 3.0.9? )

A version compatibility chart would be nice to have on the cometD documentation.

**Comment by sbordet** [comment]
This is documented already in the [installation section](https://docs.cometd.org/current/reference/#_installation).
