### ISSUE TITLE
errors are logged at `info` level

### ISSUE THREAD

**Issue by seansfkelley** [cometd/cometd#700]
In a few places, `Throwable`s are caught and logged at `info`. This seems bad; shouldn't they be logged at `error` or at least `warn`? My server was swallowing important errors because I had erroneously configured logging at too-high of a level and had to trace back into CometD internals to discover my assumptions were wrong.

Example instances:

- https://github.com/cometd/cometd/blob/fa00c1c8eeacc6e7c2ddc9addafb0afe213bca75/cometd-java/cometd-java-server/src/main/java/org/cometd/server/BayeuxServerImpl.java#L463
- https://github.com/cometd/cometd/blob/fa00c1c8eeacc6e7c2ddc9addafb0afe213bca75/cometd-java/cometd-java-server/src/main/java/org/cometd/server/BayeuxServerImpl.java#L471
 - https://github.com/cometd/cometd/blob/fa00c1c8eeacc6e7c2ddc9addafb0afe213bca75/cometd-java/cometd-java-server/src/main/java/org/cometd/server/BayeuxServerImpl.java#L938

**Comment by sbordet** [comment]
Listeners should not throw; if they do is most - if not all the times - an application problem, so it's logged at INFO level exactly for that reason.

**Comment by seansfkelley** [comment]
Sure, I don't disagree that it's an application problem, but it still seems user-unfriendly to catch all errors and pass them off as "informative" log lines, when in reality they likely indicate programmer error or unexpected state. Put another way, the second half of your comment doesn't seem to follow from the first half; I could just as well state that "it's an application problem, so it's logged at ERROR level exactly for that reason".

In either case, this is not documented anywhere I can find, which was frustrating. I spent about an hour trying to to figure out why something was apparently hanging forever, only to discover that CometD had been swallowing important logs (NullPointerExceptions, to be precise, which is indeed an application problem). I didn't immediately turn on debug logging for CometD when starting to debug because the connection seemed to be functioning as normal at a glance (i.e., there were requests and responses, but just not all the responses that were expected by the protocol).

**Comment by sbordet** [comment]
Then I don't understand what happened to you.

Typical logging configuration is INFO level. At that level, CometD only logs application errors.

If you had to turn on DEBUG level to see an application error, then we can improve, but from your description does not appear to be the case.

If you had configured your logging at WARN level, then I'd say you have been too aggressive in your logging configuration.

**Comment by supersteves** [comment]
I ran into the same problem today. CometD 3.1.5 crashing with NPE in AcknowledgeMessageException:157 because `Long batch` is null. Took me a few hours to realise this was happening because it was being swallowed by INFO log. I don't understand the resolution of this issue. Program errors (such as this case) should never be logged as INFO for exactly this reason - they get swallowed.

**Comment by supersteves** [comment]
Clarification: it's quite common to have default logging at WARN level. As we do. I'd expect a program error to be at ERROR level. So here we have a program error at INFO level and our default at WARN so we never see program errors.

What I'm questioning here is: why are program *errors* with bundled extensions not get logged at *ERROR* level

**Comment by sbordet** [comment]
@supersteves because everybody has a different opinion on what an error is, what a program is, and what a good default for logging frameworks is.

**Comment by sbordet** [comment]
The NPE in the ack extension must not happen. If it still happens to you, please log a different issue.

**Comment by supersteves** [comment]
Agreed, but perhaps there are other undiscovered problems in extensions that should be logged as ERROR.

**Comment by supersteves** [comment]
The problem in question is https://github.com/cometd/cometd/issues/810

**Comment by supersteves** [comment]
I can see why you want to use INFO for errors in extensions - perhaps these are 3rd party extensions, or non-program errors (e.g. IOExceptions). Not sure what the answer is here, but several people have had problems with program errors being swallowed.
