### ISSUE TITLE
Expose details/protocol for current connection via BayeuxContext

### ISSUE THREAD

**Issue by giantninja** [cometd/cometd#701]
Currently the details that can be assertained during a handshake, via:

```
SecurityPolicy.canHandshake(BayeuxServer server, ServerSession session, ServerMessage message)
```

are limited to basic info like the IP address, port, scheme and transport: 
```
String ip = server.getContext().getLocalAddress().getAddress().getHostAddress();
Integer port = server.getContext().getLocalAddress().getPort();
String scheme = server.getContext().getURL().split(":")[0];
String transport = server.getCurrentTransport().getName();
```

It would be useful to expose other useful connection information like the protocol in use.  For example, if http2 is being used, there isn't currently a way to get that information from the objects exposed to the `canHandshake()` method, since http2 will most likely be `long-polling` transport with a scheme of `https` but that is the same details as a http 1.1 long-polling over https.

**Comment by sbordet** [comment]
As a workaround, what you can do is to install a Servlet Filter where you extract the protocol version from the request and store it as a request attribute:

```
public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {
    String protocol = request.getProtocol();
    request.setAttribute("protocol", protocol);
    chain.doFilter(request, response);
}
```

Then from CometD you can access that via `BayeuxContext.getRequestAttribute("protocol")`.

Unfortunately adding a new method to BayeuxContext is an API change that we only do in major/minor version updates, but not micro version updates (so it will be in 3.2 or 4.0).
