### ISSUE TITLE
400 status during Websocket handshake (couldn't re-establish connection)

### ISSUE THREAD

**Issue by EugeneDymo** [cometd/cometd#703]
I'm trying to integrate CometD (2.5.1 version) with existing application, but faced with the unstable issue: after a while js-client loses connection with comet server and cannot establish it again.
Exception in browser's console: https://www.screencast.com/t/Yr8ZL4M0q , it tries and tries to connect (https://www.screencast.com/t/QhqCZxAp) but no luck. Jetty server worked with TRACE log level, and there is the latest records for my clientId:

> 2017-01-24 13:08:08 [BayeuxServer@2381076] DEBUG org.cometd.bayeux.server.ServerSession - Sweeping session ax4s2bytk5k0xo3ma8cgvv8v36 - last connect 20015 ms ago
> 2017-01-24 13:08:08 [BayeuxServer@2381076] DEBUG org.cometd.server.BayeuxServerImpl.2381076 - Removing session ax4s2bytk5k0xo3ma8cgvv8v36 - last connect 20015 ms ago, timed out: true

The lastest successfull handshake looks like this: https://www.screencast.com/t/dPjLOQ54f3x5
CometD servlet params on server side: https://www.screencast.com/t/pNFNjmgsYRE

Is there anything obviously wrong with my settings or my comet's behavior? Thanks in advance.

**Comment by sbordet** [comment]
CometD 2.x support is only available via [commercial support](https://docs.cometd.org/current/reference/#_support). You are encouraged to move to CometD 3.1.x.

You can find the migration guides from 2.x to 3.0.x and to 3.1.x [here](https://docs.cometd.org/current/reference/#_migration).

The status code 400 is typically due to a wrong WebSocket configuration on the server, for example the required dependencies are missing.

Getting WebSocket to work may be tricky. I recommend that you start by configuring CometD properly with HTTP. Once everything works fine, you can work on adding WebSocket support.

**Comment by EugeneDymo** [comment]
Thanks for response.

> The status code 400 is typically due to a wrong WebSocket configuration on the server, for example the required dependencies are missing.

It could appear in such unstable way when it works, works and just stopped?

I used long-pulling transport before, but WebSocket looks as more stable and modern variant (no?).

**Comment by sbordet** [comment]
If WebSocket was working fine, and then stopped working replying with a 400, then something has changed on the server. I would advise to check the cron jobs on the machine your server is installed: it won't be the first time that we hear that a cron job clears `/tmp` where Jetty has exploded the WAR, rendering the web application non functional.

The feedback I have from real-world deployment of WebSocket is mixed. Sometimes it works very well, sometimes it just does not. It was supposed to be the final solution for bidirectional web communication, but unfortunately the Internet infrastructure, ISP providers, mobile network carriers and browsers implementations do not appear to be at the same level of robustness as HTTP.
You need to try out and verify it.

**Comment by sbordet** [comment]
Closing, no further activity on this issue.
