### ISSUE TITLE
Review extensions invocation order

### ISSUE THREAD

**Issue by sbordet** [cometd/cometd#705]
Currently, `BayeuxServer.Extension`s are processed in registration order for incoming messages, and reverse registration order for outgoing messages.

I don't think this is right, especially for `BayeuxServer.Extension`s that register `ServerSession.Extension` from `sendMeta()` to verify that the handshake succeeded.

Furthermore, `ServerSession.Extension` are not processed in reverse registration order, making this asymmetry a problem.

**Comment by svarovski** [comment]
I think it is correct to have opposite processing order for sending. It makes processing chain look like this:
```
client -> ext A -> ext B -> ext C -> server
client <- ext A <- ext B <- ext C <- server
```
which is more logical that if there was direct invocation order in both cases. Actually, I think this was the reason to do so initially.

**Comment by sbordet** [comment]
Let's document an example, where one would want to process 2 extensions in a precise order, let's say gzip + binary.

```
... -> network -> server -> server_ext_binary -> server_ext_gzip
```

where `server_ext_gzip.rcv()` does `gunzip`.

In case of a broadcast message, the server broadcasts the message so needs to first gzip and then encode binary, so `server_ext_gzip.send()` does `gzip`. Inversion of the invocation order is therefore correct for `BayeuxServer.Extension`s.

Let's run the case for `ServerSession.Extension`s.
We need a `BayeuxServer.Extension` that identifies the sessions that needs to have the extensions (let's say gold customers only), and then register the `ServerSession.Extension`s onto the session.

Such `BayeuxServer.Extension` must register the `ServerSession.Extension`s during `rcv*()` methods, not during `send*()` methods, otherwise the order of the session extensions is inverted.
Note that the `AcknowledgedMessagesExtension` violates this rule.

If the rule is respected, when a message arrives it's processed in this way:

```
... -> server -> session_ext_binary -> session_ext_gzip
```

If the application sends a message we need to first gzip and then encode binary, so also `ServerSession.Extension`s must be invoked in reverse order.
However, currently this is not done.

There are 2 issues then: 

- document the rule that `BayeuxServer.Extension` must register `ServerSession.Extension`s from `rcv()` methods and make `AcknowledgedMessagesExtension` respect the rule
- invert the invocation order for outgoing messages of `ServerSession.Extension`s
