### ISSUE TITLE
Listener not working

### ISSUE THREAD

**Issue by tharivignesh** [cometd/cometd#708]
I am adding a listener to the Connect call. But the listener function is not firing after the connect call has been made.

**Comment by sbordet** [comment]
We have tests in the CometD test suite that prove that it's working.

You need to detail your issue report with code.

**Comment by tharivignesh** [comment]
Thank you for the quick response.
This is my code:

function connect(args) {
            try {
                 if (args != undefined) {
                    var serverUri = args.serveruri;
                    console.log('Connecting to [' + serverUri + ']...');

                    cometd.configure({ url: serverUri,logLevel: 'debug' }, function(message){
						console.log(message);
					});

                    cometd.handshake(function(h) {
						if (h.successful) {
							console.log("handshake successful.");
				        	onopen(args);
                	    }
						else{
							console.log("handshake failed.");
						} 
					}); 

                    console.log(cometd.getStatus());
                    console.log(cometd.isDisconnected());
                    console.log(cometd.getConfiguration());
                }
                else {
                    console.log('Connection cannot be established.');
                }

            }
            catch (err) {
				console.log("Exception : ");
                                console.log(err);
            }
        }

When I check the status it remain as handshaking. The listener added for the connect is also not firing.

the listener code: 

 cometd.addListener('/meta/connect', function (message) {
            console.log('Connecting...');
            
	   if (cometd.isDisconnected()) {
                return;
            }
           
            _connected = message.successful;
            if (_connected) {
                onopen();
            }
            else {
                onclose();
            }
        });

I am not getting any errors.
Where can I download the test suites for nodeJS ?

**Comment by sbordet** [comment]
Your code looks fine, so there must be something else going on - probably some misconfiguration.
I see that you have already configured at `debug` level.
Can you please attach the client-side logs ?

**Comment by sbordet** [comment]
If you need CometD to run in NodeJS, please look at https://github.com/cometd/cometd-nodejs-client and https://github.com/cometd/cometd-nodejs-server.
