### ISSUE TITLE
@Listener methods swallow all exceptions

### ISSUE THREAD

**Issue by boris-petrov** [cometd/cometd#718]
In a `@Listener` method, if an exception is thrown, it is swallowed and there is no log, there is no notification, nothing. I could not find in the documentation any mention of what to do in that case. Are we supposed to try-catch the whole method or I am missing something fundamental?

**Comment by sbordet** [comment]
Exception thrown from `@Listener` methods, like exceptions thrown by all the listeners in CometD, are caught, logged at `INFO` level, and then ignored - this is by design.

If your code throws a `RuntimeException` and you want to handle it, you have to catch it yourself and handle it. Otherwise it is typically an unexpected error (i.e. `NullPointerException`, etc.).

You are right that this is not documented, so I will take care of documenting it.

**Comment by boris-petrov** [comment]
Thanks for the answer. Logged with what logger? I'm using `SLF4J` with bridges for almost anything I could think of and I don't see any exceptions logged (and I throw them on purpose to test). Also, perhaps it's a good idea to expose an "uncaught exception handler" or something so clients of CometD could decide what to do with the exception themselves - I want to log at `ERROR` level for example.

**Comment by sbordet** [comment]
If you want to do custom logging, or anything custom, then the best way is to try/catch the exceptions yourself. There are just too many variations of what one wants to do in case of exceptions that the CometD implementation cannot accommodate them all.

The logging at INFO level is just the basic notification from CometD that something went wrong.

The CometD loggers that log at INFO level are different ones, depending on where the listener belongs, see for example [this](https://github.com/cometd/cometd/blob/3.1.1/cometd-java/cometd-java-server/src/main/java/org/cometd/server/BayeuxServerImpl.java#L938) and [this](https://github.com/cometd/cometd/blob/3.1.1/cometd-java/cometd-java-server/src/main/java/org/cometd/server/ServerChannelImpl.java#L134).

**Comment by boris-petrov** [comment]
Well, a custom exception handler would allow me to log to the `ERROR` level which I definitely want. And I also definitely do NOT want to try-catch all my `@Listener` methods.

Also, why are you logging errors at the `INFO` level? I have the following `logback.xml`:

```xml
...
    <logger name="com.mycompany" level="TRACE" additivity="false">
        <appender-ref ref="consoleAppender" />
    </logger>

    <root level="WARN">
        <appender-ref ref="consoleAppender" />
    </root>
...
```

As you see, I print to the console only messages from my code and only warnings/errors from third-party code (which makes sense I believe). That's why I don't see any logs from CometD as it logs at `INFO`. Why do you log exceptions at `INFO`?

**Comment by sbordet** [comment]
A custom exception handler will not have any context of what you're doing in your `@Listener` method and enclosing object so it is of very limited use.

I don't want to start a religious war on logging.
What you consider an error may not be an error for CometD.
You can easily change your logback configuration to output the CometD logs at INFO level.

**Comment by boris-petrov** [comment]
Yes, I'm not trying to start any war, I was just curious as to why you log user exceptions at `INFO` level (which obviously are bugs in user code). That's what I already did - log CometD stuff at `INFO`. Hopefully only exceptions are going to be logged and not internal CometD stuff.

Anyway, thanks for the time! Do consider changing the level of the user's exceptions to at least `WARN` so other people are not bitten like me (or at least mention that in the documentation).
