### ISSUE TITLE
How to use JavaScript cometd

### ISSUE THREAD

**Issue by nerdtron123** [cometd/cometd#723]
With jQuery 2.4.4, and Bootstrap 3.3.7 js loaded, I am not able to access $.cometd
I believe I am very lost, I currently am including the JS as follows: <script src="https://raw.githubusercontent.com/cometd/cometd/master/cometd-javascript/common/src/main/webapp/js/cometd/cometd.js"></script>

**Comment by sbordet** [comment]
Please have a read at the [CometD documentation](https://docs.cometd.org/current/reference/), especially the [primer](https://docs.cometd.org/current/reference/#_primer) that will setup an example project for you.

After that, please have a look at all the [demos and examples](https://docs.cometd.org/current/reference/#_installation) that are shipped with the CometD distribution.

You can find examples for jQuery, Dojo, Angular 1 and vanilla JavaScript.

**Comment by nerdtron123** [comment]
@sbordet i'm trying to make a javascript web interface for my application, and I cannot find the javascript needed. I'm including both jquery, and your common cometd.js script (vanilla?)

**Comment by nerdtron123** [comment]
The vanilla example refrences to var _cometd = new org.cometd.CometD(); which is undefined in my environment.

**Comment by sbordet** [comment]
Aren't you using jQuery ? Look at the jQuery examples in the distribution. https://github.com/cometd/cometd/tree/master/cometd-javascript/examples-jquery/src/main/webapp/jquery-examples/chat
