### ISSUE TITLE
Gracefully shutdown WebSocketContainer

### ISSUE THREAD

**Issue by sbordet** [cometd/cometd#727]
JSR 356 `WebSocketContainer` does not have a lifecycle.

Because of that, we want to try a best effort to stop it when other components that use it are stopped.

**Comment by sbordet** [comment]
After discussion, not a great idea. Who provides and starts the `WebSocketContainer` should be responsible to stop it too.

**Comment by joakime** [comment]
Links to spec bugs about this (in case someone in future reads this issue)

* javaee/websocket-spec#230
* javaee/websocket-spec#212
