### ISSUE TITLE
Maximum connections supported by CometD

### ISSUE THREAD

**Issue by chathurarandika** [cometd/cometd#743]
In our application, when concurrent connections count exceed 500 suddenly set of connected clients disconnected. Is there parameter to configure to increase the maximum connection count.

**Comment by sbordet** [comment]
You need to be more precise in your report. Server configuration, client configuration, what errors exactly (if any), etc.

I have tested CometD to 400k connections on a single server, so if you have problems at 500 there is likely something really wrong with your configuration.

**Comment by chathurarandika** [comment]
Thanks  a lot Simone, we found out an issue in client side. So there is no issue in cometd library.
