### ISSUE TITLE
excessive creation of new loggers

### ISSUE THREAD

**Issue by erwrock** [cometd/cometd#750]
Hello
We are using cometd in combination with ch.qos.logback as logger-implementation for org.slf4j.Logger.

Our problem lies in the class org.cometd.websocket.server.common.AbstractWebSocketTransport.AbstractWebSocketScheduler

This class has a field:
protected final Logger _logger = LoggerFactory.getLogger(getClass());

A new instance of this class is created in the constructor of org.cometd.websocket.server.WebSocketTransport.WebSocketScheduler:

delegate = new AbstractWebSocketScheduler(context) {...

therefore each new instance of AbstractWebSocketScheduler "has it's own class" because at every instantiation a new anonymous class is created.

"LoggerFactory.getLogger(getClass());" in AbstractWebSocketScheduler generates a new Logger at each call.

So for each new Instance of AbstractWebSocketScheduler you get a new Logger which stays in the heap even if the AbstractWebSocketScheduler instance is garbage collected.

In our environment we have about 1 000 000 instances of that logger after a few days.

This is not only a problem with the heap (memory is cheap - so who cares?). createing a new logger gets slower a little bit every time. I assume that the LoggerFactory has to look up the internal logger table if a suitable logger exists already. At first this is negligible. But after some weeks or so the getLogger method consumes a considerable fraction of a second. As getLogger is kind of a bottle neck it slows down the application.

I know it is kind of bad practice. But would it be possible to change the line to:

protected static final Logger _logger = LoggerFactory.getLogger("org.cometd.websocket.server.WebSocketTransport.WebSocketScheduler");

(ok - I don't think that the "static" helps much...)

regards

**Comment by sbordet** [comment]
I would expect just _one_ anonymous class, namely `WebSocketTransport$WebSocketScheduler$1` to ever be created, and `LoggerFactory.getLogger(getClass())` should just have that one instance related to that class.
I don't know about LogBack, but other loggers just do `clazz.getName()` and store loggers by their string name, so again there would be just one instance.

How did you figure out the logger instances were retained by the logging framework ? Can you share that analysis ?

**Comment by erwrock** [comment]
Hi

I think I "double-posted" this error:
https://github.com/cometd/cometd/issues/600

We are still using cometd-3.0.5. The issue above relates to 3.0.4. So maybe the problem is fixed already. Eventually I have checked the wrong version of the source code.

The behavior is quite similar to that in issue 600. The logger names have the same structure.

I am now at home and have no access to the production environment. Tomorrow I can provide more details. For now in short:

Connecting to the jvm over jmx with jmc (or jconsole or whatever). logback provides a managed bean which shows the loggers in use. Here I can clearly see additional loggers of the kind "org.cometd.websocket.server.WebSocketTransport$WebSocketScheduler$1.###" (where ### is a random number). The number or loggers is increasing with each WebSocket connection.

After several weeks the server shows an increased heap consumption. A heap histogram shows an abnormal high amount of logger instances.

Threaddumps of the running server show that some threads are waiting to get a logger. The stack trace shows, that it is excactly the constructor of the org.cometd.websocket.server.WebSocketTransport.WebSocketScheduler class who tries to get a logger. At some point (1.5 months of running) some threads have a thread lock here.


We will try to upgrade to a newer version of cometd. Hopefully the problems cease to exist.

**Comment by erwrock** [comment]
aaahhh - silly me

just checked the source of 3.0.5

protected final Logger _logger = LoggerFactory.getLogger(getClass().getName() + "." + Integer.toHexString(System.identityHashCode(this)));

now everything is clear. sorry to bother you. I think, this issue can be closed now...

**Comment by sbordet** [comment]
That was fixed in 3.0.6.
