### ISSUE TITLE
@Listener methods called after SessionListener.sessionRemoved

### ISSUE THREAD

**Issue by boris-petrov** [cometd/cometd#754]
For the same `ServerSession.getId`, I receive a `SessionListener.sessionRemoved` notification and *after* that a `@Listener` method is called.

Is this expected? If not, could it be my mistake somewhere? If yes, why?

**Comment by sbordet** [comment]
Which CometD version ?
How much after ?
The session is removed because of server-side expiration (the `timeout` parameter will be `true`) ?

**Comment by boris-petrov** [comment]
Sorry, should have put the version. The latest - `3.1.3`. The `SessionListener.sessionRemoved` callback is invoked in the middle of some `@Listener` notifications so it is pretty much immediately after the `sessionRemoved` that the `listener` is invoked. I'll put some logging and will tell you whether its because of a timeout.

**Comment by boris-petrov** [comment]
OK, the `timeout` parameter is `true` which is kind of strange as the session was created around a second before that, a few `@Listeners` were invoked and then the `SessionListener.sessionRemoved`... any ideas on how to approach this?

**Comment by sbordet** [comment]
It's unlikely that the session is expired on server if it's created around a second before.
I need server-side DEBUG logs, please attach them here.

**Comment by boris-petrov** [comment]
OK, I'll need some time for that, I'll try to do it in the next few... weeks probably.

**Comment by sbordet** [comment]
Closing as no further activity. Please open another issue if this is still a problem for you, but I do need DEBUG logs to understand what's going on.
