### ISSUE TITLE
angular-cometd does not work with angular 1.6.x

### ISSUE THREAD

**Issue by panakran** [cometd/cometd#756]
angular-cometd uses success/error instad of then. 

Replacing with `then()` and passing `data.data` to onSuccess()  instead of `data` solves the issue.

**Comment by sbordet** [comment]
Can you please be more specific ? The Angular Demo works fine for me, so I'm not sure where the problem is.

**Comment by panakran** [comment]
I am referring to this https://code.angularjs.org/1.5.10/docs/api/ng/service/$http#deprecation-notice
AngularJs examples use version 1.5.8, latest angularjs version is 1.6.x

**Comment by sbordet** [comment]
Ah, thanks. I will upgrade Angular.

**Comment by d-eisenga** [comment]
Is there any update on this? In addition to the `.success` and `. error` methods, Angular 1.6 also forbids passing `jsonp: 'JSON_CALLBACK'` to `$http.jsonp` configuration objects but the server returns a 500 error when I omit the property.
