### ISSUE TITLE
Vue Cometd plugin

### ISSUE THREAD

**Issue by fergardi** [cometd/cometd#765]
Hello!

I need a CometD plugin for [VueJS](https://vuejs.org/) and, since you have no one yet, I'll try to build one from scratch based on the Angular one and make a PR to your repository with the result.

See you!

**Comment by sbordet** [comment]
Note that CometD offers vanilla bindings (i.e. ones based on pure JavaScript with no other dependencies) and support both AMD and CommonJS/NodeJS styles of modules.

The only reason to have Angular 1.x bindings are that it has its own module system and that it requires to call `$apply()` to WebSocket callbacks.

From what I understand, Vue does not have any wrapper around `XMLHttpRequest` or `WebSocket` and does not require any special treatment of their callbacks, so you should be good with vanilla CometD with whatever module system you like.

Let us know how it goes. Thanks !

**Comment by fergardi** [comment]
Hello! I was able to replicate the vanilla code in my custom VueCometD plugin (which I intent to PR you with after some testing, don't worry).

Now the problem I'm experiencing is with sending the additional requestHeaders in order to send my Authorization Bearer token with. Following the documentation, it is done by:

```javascript
let cometd = new library.CometD()
cometd.unregisterTransports()
cometd.configure({
  ...,
  requestHeaders: {
    Authorization: 'Bearer xxxxxxxxxxxx'
  },
  ...
})
```

But I keep getting 401 from my Jetty server! And in the WS devtools inspector, I cannot see my custom seader being sent to the server. I've tried every possible combination with no luck so far.

What am I doing wrong?

Thanks in advance.

**Comment by sbordet** [comment]
By default Jetty does not implement the `Bearer` authentication, so you have to plug something inside Jetty server to make this work.

The vanilla CometD transport does handle request headers in the format you have specified, but only for the `http` transports, not `websocket` because there are no browser APIs to set a HTTP header when opening a WebSocket connection.

If you disable the `websocket` transport with:

```javascript
cometd.websocketEnabled=false;
```

does it work ?

**Comment by fergardi** [comment]
Thanks for your response, but it does not even handshake with that configuration.

**Comment by sbordet** [comment]
Why do you have this:

```javascript
cometd.unregisterTransports()
```

Make sure that you client and your server have the `http` transports available.
They are the only way to send the `Authorization` header.

**Comment by fergardi** [comment]
That code comes from the Angular plugin, on which I've based mine.

https://github.com/cometd/cometd/blob/master/cometd-javascript/angular/src/main/webapp/js/angular/angular-cometd.js#L79

I do believe both have the http transport enabled, cause I use OAuth for http/s API Authorization already.

I still believe I'm missing something here. How is usually OAuth Bearer token security handled with WS, due to the missing headers limitation?

**Comment by sbordet** [comment]
The `Bearer` token cannot be handled with WebSocket.

The angular binding replaces the vanilla transports with its own versions of those transports, so it unregisters all transports (the vanilla ones) before registering the angular specific transports under the same names.

If you are using the vanilla transports for Vue, you don't need to unregister the transports.

**Comment by sbordet** [comment]
Closing as the Vue plugin seemed ok (hey, we expect the PR!), but the issue went into WebSocket authentication issues that are not CometD related.

**Comment by michaelherger** [comment]
@fergardi would you have working Vue/CometD code?
