### ISSUE TITLE
Java client does not support additional objects on subscribe 

### ISSUE THREAD

**Issue by makobernal** [cometd/cometd#766]
Unlike the Javascript client's _subscribe()_, or the Java and Javascript handshake(), cometd's java client does not support adding additional objects to the initial message sent on a subscription to a channel.

https://github.com/cometd/cometd/blob/846ceb4d627252699a4dcaa44db3766793db428a/cometd-java/cometd-java-common/src/main/java/org/cometd/common/AbstractClientSession.java#L461

This means that any server-side `Authorizer` which would need to read some additional field, would only be able to do so from messages coming from an `Operation.PUBLISH` if using the Java client.

**Comment by sbordet** [comment]
Can you expand on this use case ?

Typically the additional fields are only needed during the handshake to validate the session.
Once you have a valid `ServerSession` you trust it.

Thanks!

**Comment by makobernal** [comment]
In our use case we have channels which are restricted to each connected user. 

An implementation of `Authorizer` validates the session is valid, and also that the user associated to this session can subscribe to this channel, and no one else.

Since in our use case they are dealing with the Javascript client this hasn't been a problem until I tried creating a little java app to connect to cometd.

**Comment by sbordet** [comment]
From your description you only need the session, the channel and the user associated to the session.

Why would you need additional fields on subscribe messages ?

**Comment by makobernal** [comment]
Sorry for the confusion, I meant our concept of session (which is how we can retrieve the user), not Bayeux ServerSession. 

Our javascript clients have been passing this on an additional field on the subscribe message.

**Comment by sbordet** [comment]
@makobernal you cannot trust an id passed along with subscribe messages, unless you pair it with the `ServerSession` id; and at that point, you don't need your id.

**Comment by makobernal** [comment]
What would be the preferred way of authorizing access to some channels upon subscription, upon some arbitrary data or challenge, if a payload cannot be sent in the subscribe message?

I'm also curious as to why would the Javascript client implementation would support it, but not the Java client

**Comment by sbordet** [comment]
You have a point about the possibility to customize the subscribe message. As this is an API change, it'll be scheduled for 4.0.x.

**Comment by sbordet** [comment]
@makobernal I made the change in CometD 4.0.x, would you try it to see if it fits your case ?

Be _very_ careful at passing your custom session ids around. You want to read the CometD [security section](https://docs.cometd.org/current/reference/#_security) to see what kind of attacks you may be exposing yourself to.

**Comment by makobernal** [comment]
I've tried with a locally built 4.0.x branch and it does work, my server-side `Authorizer` is now able to read the first `ServerMessage` on a subscribe operation. I think this puts it on par with the javascript client. Thank you for the commits.

I will definitely have a read to the security section, and perhaps try to tamper with my own sessions on our cometd endpoint to verify our risk.

**Comment by sbordet** [comment]
Thanks for feedback, closing this issue.
