### ISSUE TITLE
Is there any other way of knowing when to re handshake other than /meta/connect channnel listener ??

### ISSUE THREAD

**Issue by dpnkr** [cometd/cometd#770]
How do I know when a re handshake is required ? And How do I re handshake ? Is it the way to do it :

1. client.disconnect() (after unsubscribe everything)
2. stop jetty http client 
3. start jetty http client
4. initialize bayeux client 
5. client.subscribe()
6. client.handshake()

OR 
just 
1. client.handshake() again in case re handshake required . Please note that in this way every time I try to do re handshake i get illegalstate exception.

Please suggest the ideal way of re handshaking as well as how do I know when to do the same ??

**Comment by sbordet** [comment]
I'm guessing this is the same as https://stackoverflow.com/questions/48902125/. 
If so, the question/issue is incomplete since it entails updating the `Authorization` header, rather than using the CometD APIs.

**Comment by dpnkr** [comment]
Hi @sbordet  can you please reply to the comment which I have added in that stackoverflow link ??

**Comment by dpnkr** [comment]
Also can you answer the first part of the question(How do I know when a re handshake is required) which I asked here ???

**Comment by sbordet** [comment]
A re-handshake is not required, as CometD performs automatic re-handshakes in your behalf.
