### ISSUE TITLE
Push Technology/Web Streaming classification

### ISSUE THREAD

**Issue by Pratibha24** [cometd/cometd#774]
I need to implement a framework for the web streaming but i am confused in the classification of streaming techniques and protocols. like HTTP, HTTP Long Polling, WebSockets, Bayeux protocol, Comet, Jetty etc. Can someone tell me the proper hierarchy/classification of the web streaming (pictorial view will be better) so that it will be easy for me to understand and design it in a better way.

Thanks, Pratibha

**Comment by sbordet** [comment]
Google and Wikipedia are your friends here.

The [preface](https://docs.cometd.org/current/reference/) of the CometD documentation should also be of help.

You want to be more detailed about what exactly you mean by "web streaming" (what data, what constraints of latency, how many clients, etc.) for further information.

**Comment by Pratibha24** [comment]
I want to know the classification of Push technology. Like it can be break down to "HTTP" and "Web Sockets". And then HTTP can be classified into other categories.
So i want some pictorial view of this hierarchy , like where comet,Bayeux,transport protocol etc sits into the picture.
