### ISSUE TITLE
API Error=403 Unknown client Reconnection mechanism is shown correctly but not received messages after that

### ISSUE THREAD

**Issue by kyleabcha** [cometd/cometd#775]
Hi,

We are facing a critical issue with a long poll by using Salesforce Streaming API 42.0 and cometd 3.1.3. After every a few hours connected to Salesforce server, Salesforce returned an Unknown client Error=403 through /meta/connect channel with the following debugging messages 
```
**Connect channel message 1**: {**clientId=1xz1kbxnyn98wa5f16rafvddhqbcj**, channel=/meta/connect, id=103, successful=true}
**Connect channel message 2**: {advice={reconnect=handshake, interval=0}, channel=/meta/connect, id=104, error=403::Unknown client, successful=false}
```
Reconnection mechanism is shown correctly. 
```
**Handshake channel message 3**: {ext={replay=true, payload.format=true}, minimumVersion=1.0, clientId=3ll1jkeest5ommhf1cfv2wbgmz1et, supportedConnectionTypes=[Ljava.lang.Object;@59de241b, channel=/meta/handshake, id=105, version=1.0, successful=true}
**Connect channel message 4**: {**clientId=3ll1jkeest5ommhf1cfv2wbgmz1et**, advice={reconnect=retry, interval=0, timeout=110000}, channel=/meta/connect, id=106, successful=true}
**Connect channel message 5**: {**clientId=3ll1jkeest5ommhf1cfv2wbgmz1et**, channel=/meta/connect, id=107, successful=true}
**Connect channel message 6**: {**clientId=3ll1jkeest5ommhf1cfv2wbgmz1et**, channel=/meta/connect, id=108, successful=true}
```
Followed reconnection mechanism at https://docs.cometd.org/current/reference/#_long_network_failures_or_server_failures

Rehandshake is successful and the Salesforce server accepts it and allocates a new client Id and a long connection re-established. However, we have not received any messages yet since that time.

Could anyone help me on this? Thanks a lot.

**Comment by sbordet** [comment]
Unfortunately, `error=403::Unknown client` is not something that is generated by CometD, but by the SalesForce application.
Why they generate that error, you have to ask SalesForce.

Please make sure your client application follows the recommendation in [this section](https://docs.cometd.org/current/reference/#_javascript_subscribe) - subscribe your channels from a `/meta/handshake` listener.

**Comment by kyleabcha** [comment]
Thanks sbordet for your input. I am double checking the recommendation and let you know if it works.

**Comment by kyleabcha** [comment]
Thanks sbordet it is a correct recommendation. The issue is closed.

**Comment by guruprasad83** [comment]
@sbordet - Your comments above helped me to solve my case. Thanks a lot :)

**Comment by aminejamoussi** [comment]
Hi kyleabcha,
I have the same problem, could you share the solution in your case ?

**Comment by kyleabcha** [comment]
We called subscribe() after handshake(), for example:

client.handshake();
client.subscribe();

This led to the problem. We fixed by adding a callback to handshake() call to verify if the handshake is successful and only call subscribe() in the safe place.

client.handshake(message -> {
    if (message.isSuccessful()) {
        client.subscribe();
    }
});
