### ISSUE TITLE
Reset backoff after successful connect

### ISSUE THREAD

**Issue by fdummert** [cometd/cometd#782]
Hi Simone,

the issue is described with logs attached in the [mailing list](https://groups.google.com/forum/#!topic/cometd-users/k0CygzoVd1c): BayeuxClient should reset the backoff after a publishing error not only on handshake but also on successful connect. In our case the backoff was incremented after a MessageTooLargeException permanently for the session lifetime until reaching max backoff. As we're using the ack extension this leads to long communication delays.

Best Regards,
Florian

**Comment by sbordet** [comment]
@fdummert can you please try the latest code to verify it's working for you?
