### ISSUE TITLE
Memory leak with publish callback / extension that prevents sending

### ISSUE THREAD

**Issue by fdummert** [cometd/cometd#783]
Hi Simone,

using a publish callback in conjunction with an extension that prevents a message to be sent out is leading to a memory leak: the publish callback never gets unregistered. The issue is also explained in the [forum](https://groups.google.com/forum/#!msg/cometd-users/uykjb3KfpFQ/T74t9iSWBQAJ).

Best Regards,
Florian

**Comment by sbordet** [comment]
Fixed.
