### ISSUE TITLE
UTF-16 does not work

### ISSUE THREAD

**Issue by kyleabcha** [cometd/cometd#784]
Hi cometD team,

We are using cometD client version 3.1.4. It is not able to receive UTF-16 messages correctly. if a message contains a UTF-16 character, it is printing a question mark '?' character instead.

Could you please let me know how to deal with UTF-16 characters?

**Comment by sbordet** [comment]
CometD uses JSON as message format. JSON requires UTF-8.

If you see `?` characters, it means that a certain points there has been a character to bytes (or bytes to characters) conversion that did not go well.

For example, you save a text on a file: there is a conversion from characters to bytes and let's assume you used UTF-16.

Later you want to send that text as a chat message in CometD; you read the file from the file system but you wrongly use UTF-8, so now you have a garbage bytes representing your text in a `String` object in memory. When that is sent as JSON over the network (again, conversion from text to bytes using UTF-8), the other side receives garbage bytes.

Double check where you are doing wrong conversions, or where you are using the default charset (which most likely is not the correct one).

**Comment by kyleabcha** [comment]
Thanks Simone for your hint.

Will check and update you soon.

**Comment by kyleabcha** [comment]
Hi Simone,

I double check but could not find any issue at the client codebase.

We are using CometD client for Java version and connect to Salesforce system. Below is the sample code used in our application. Could you please help with this? Many thanks in advance.


`package test;

import org.cometd.bayeux.Message;
import org.cometd.bayeux.client.ClientSessionChannel;
import org.cometd.client.BayeuxClient;
import org.cometd.client.transport.LongPollingTransport;
import org.eclipse.jetty.client.HttpClient;
import org.eclipse.jetty.client.api.Request;
import org.eclipse.jetty.util.ssl.SslContextFactory;

public class UTF16Test {

	private static final String URL = "https://my_instance.salesforce.com/cometd/43.0";
	private static final String SESSION_ID = "my_session";

	public static void main(String[] args) throws Exception {
		// Create a new HttpClient instance
		SslContextFactory sslContextFactory = new SslContextFactory();
		sslContextFactory.setIncludeProtocols("TLSv1", "TLSv1.2", "TLSv1.1");
		final HttpClient httpClient = new HttpClient(sslContextFactory);
		httpClient.start();
		
		// Create a LongPollingTransport instance
		LongPollingTransport transport = new LongPollingTransport(null, httpClient) {
			@Override
			protected void customize(Request request) {
				request.listener(new Request.Listener.Adapter() {
					@Override
					public void onBegin(Request request) {
						request.header("Authorization", "OAuth " + SESSION_ID);
					}
				});
			}
		};

		// Create a LongPollingTransport instance
		BayeuxClient client = new BayeuxClient(URL, transport);
		client.handshake();
		client.waitFor(60000, BayeuxClient.State.CONNECTED);

		// Subscription to channels
		ClientSessionChannel channel = client.getChannel("/topic/MyExample");
		channel.subscribe(new ClientSessionChannel.MessageListener() {
			public void onMessage(ClientSessionChannel channel, Message message) {
				// Handle the message
				System.out.println("Received Message: " + message.getJSON());
			}
		});

		while (true) {
		}
	}
}
`

**Comment by sbordet** [comment]
Your code above is a receiving only client; if you receive messages with `?` characters, then the error happens on server side and you should contact SalesForce.

If the messages you receive are made of data that you gave to SalesForce, then you should double check that you gave SalesForce correct data (with correct encoding, etc.) and you should double check with SalesForce that they are performing the right encoding/decoding of your data.

There is nothing that CometD can do in this case: it all depends on the server side application.

**Comment by kyleabcha** [comment]
Thanks Simone for your quick feedback.

I will contact Salesforce for this and update you soon.

**Comment by kyleabcha** [comment]
Hi Simone,

We got the update from Salesforce. Salesforce system does not support UTF-16 messages. No issue at CometD. So I close the ticket.

Thank you for the valuable feedback.
