### ISSUE TITLE
The order of statements are incorrectly placed.

### ISSUE THREAD

**Issue by JerryChin** [cometd/cometd#786]
https://github.com/cometd/cometd/blob/781c5a88c629254f02e34a31a379fbedab1c8022/cometd-java/cometd-java-server/src/main/java/org/cometd/server/transport/AsyncJSONTransport.java#L309-L315

Hey guys, I think the `if` statement should come before `state` assignment, or the last packet will be lost.

**Comment by sbordet** [comment]
The order seems correct to me.
Can you detail how the last packet will be lost?

**Comment by JerryChin** [comment]
My apology, I just realize that writing one single byte will always succeed.
