### ISSUE TITLE
[4.0.0] java.lang.ClassNotFoundException: org.eclipse.jetty.util.component.Dumpable

### ISSUE THREAD

**Issue by boris-petrov** [cometd/cometd#792]
I get this exception after upgrading from 3.1.5. Using Tomcat 9.0.12. First mentioned in https://github.com/cometd/cometd/issues/791.

**Comment by sbordet** [comment]
`Dumpable` is part of `jetty-util` that should be in your war. Is that the case?

**Comment by boris-petrov** [comment]
OK, my bad, I was importing local JAR files to test the other issue and hadn't added all necessary ones. Adding everything fixes this issue and also the other one.
