### ISSUE TITLE
Can't build cometd

### ISSUE THREAD

**Issue by nmorenor** [cometd/cometd#796]
Hi,

I'm trying to build cometd by running:

mvn clean install 

But I get an error while doing that this is the output I get:

[ERROR]     Unresolveable build extension: Plugin org.apache.felix:maven-bundle-plugin:3.5.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.felix:maven-bundle-plugin:jar:3.5.1: Could not transfer artifact org.apache.felix:maven-bundle-plugin:pom:3.5.1 from/to central (https://repo.maven.apache.org/maven2): Received fatal alert: protocol_version -> [Help 2]

Am I missing something? I've just cloned the cometd repository.

**Comment by sbordet** [comment]
It is there: https://repo.maven.apache.org/maven2/org/apache/felix/maven-bundle-plugin/3.5.1/.

You probably have hit a temporary glitch on Central or your network.

**Comment by nmorenor** [comment]
Hey,

Thanks for your quick response. This was solved by doing something like this mvn -Dhttps.protocols=TLSv1.2 clean install perhaps is something that can be mentioned on docs.

**Comment by sbordet** [comment]
What Java version and OS are you using to build CometD?
I don't need that system property on Ubuntu 18.10 with Java 11.

**Comment by nmorenor** [comment]
Right now I'm running OSx with multiple versions of Java on the system. If I use java --version I get the 1.7.0 this could probably be the issue, not sure how mvn take which version of java to use from what is installed.

$echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home

**Comment by sbordet** [comment]
https://central.sonatype.org/articles/2018/May/04/discontinued-support-for-tlsv11-and-below/
