### ISSUE TITLE
Any place to see what changed between v3 and v4

### ISSUE THREAD

**Issue by jaypatel512** [cometd/cometd#797]
Hey all.

I tried searching for CometD documentation on what changed between v3 and v4, but failed to find any concrete information. did not see any CHANGELOG.md either.

Is there a place where we can keep this documentation so that we can make an informed decisions when we upgrade please.

**Comment by sbordet** [comment]
https://docs.cometd.org/current/reference/#_migration_31_to_40

**Comment by jaypatel512** [comment]
Thanks @sbordet !

Did not see that in the docs. I was searching for "Changelog". Thank you so much for pointing me to the right direction. 👍 Cheers.
