### ISSUE TITLE
Cometd.org is quarantined by Chrome

### ISSUE THREAD

**Issue by akauppi** [cometd/cometd#799]
The web site mentioned in the GitHub project's title is currently (6-Nov-18) quarantined by Chrome:

<img width="662" alt="nayttokuva 2018-11-6 kello 17 05 16" src="https://user-images.githubusercontent.com/1297734/48073055-8d0d8000-e1e6-11e8-9604-2b42d1d0524c.png">

(it's in Finnish but I think you recognize the dialog. Essentially: don't get there - its safety cannot be guaranteed)

I'm new to CometD and did not find an issue about this. Just want to make sure someone is aware.

**Comment by sbordet** [comment]
Thanks! I have renewed the certificates.
