### ISSUE TITLE
Allow async customization of long polling request

### ISSUE THREAD

**Issue by Iteratrix** [cometd/cometd#801]
`LongPollingTransport` defines an empty `protected void customize(Request request)` method, presumably so that subclasses can override it in order to customize the request before it's sent. Unfortunately, this method returns immediately so it can't be used to customize the request with the result of an asynchronous operation. For example:

```java
@Override
protected void customize(Request request) {
final CompletionStage<String> authorization = getAuthorizationFromAsyncSource();
request.header(HttpHeader.AUTHORIZATION, "Bearer " + authorization.join()); // Need to block since the method is synchronous.
}
```

Adding an alternative that accepts a `Promise<Request>` parameter should fix this, since we could complete that `Promise` with the result of any callback.

**Comment by sbordet** [comment]
@Diagoras I understand the need for customizing the request, but adding an async operation for every request sent by the client seems a lot of overhead.
Is the async source returning a different value every time?
Why can't you compute the async value once and use that inside `customize()`?

**Comment by Iteratrix** [comment]
@sbordet You're correct that actually invoking an async request for each long polling request would be too much overhead, and also in saying that being able to cache a single token for the lifetime of the `LongPollingTransport` would be better. A more reasonable example is an authorization that's cached for some amount of time. Something like:

```java
final Mono<String> authorization = getAuthorizationFromAsyncSource().cache(() -> Duration.ofMinute(20));
```

So most callbacks registered to that future would complete immediately, but every twenty minutes they'd instead have to wait as a fresh authorization header was retrieved from somewhere. Does that clear things up at all?

**Comment by sbordet** [comment]
PR #815 merged.
