### ISSUE TITLE
Fetching Headers on receiving a message from cometD long-polling connection

### ISSUE THREAD

**Issue by jaypatel512** [cometd/cometd#803]
Hello folks,

We are using long-polling based Java Server setup. Our clients have two headers "SecurityContext" and "CorrelationID" that are automatically injected for each call to our server.

CorrelationID is used in our system to correlate all the logs that were generated during processing of this request across our entire ecosystem. And securityContext is used to identify our customers token.

I am trying to fetch those header values when accepting a message. The way we listen to it right now looks something like this:
```
        addService("/service/chat, "processMessage");

    public void processMessage(ServerSession client, ServerMessage serverMessage) {
    }
```

The processMessage only allow these two options to be passed, and none of them have any way to fetch those headers.

Could we get something like `serverMessage.getHeaders()` as a method, or any other way `serverMessage.getAttributes()` to fetch those values ?

**Comment by sbordet** [comment]
In CometD 4 you can do:

```java
public void processMessage(ServerSession client, ServerMessage serverMessage) {
    BayeuxContext context = serverMessage.getBayeuxContext();
    String correlationID = context.getHeader("Correlation-ID");
    // Etc.
}
```

**Comment by jaypatel512** [comment]
Makes sense. Thanks @sbordet !

Currently we are on CometD 3. Is there a way to do that ?

**Comment by sbordet** [comment]
In CometD 3 you have to access the `BayeuxServer` instance, which typically is accessible from the service class:

```java
public void processMessage(ServerSession client, ServerMessage serverMessage) {
    BayeuxContext context = getBayeux().getBayeuxContext();
    String correlationID = context.getHeader("Correlation-ID");
    // Etc.
}
```

**Comment by jaypatel512** [comment]
That is amazing. You are the best @sbordet ! Thanks a lot for such a quick response. Will test it out and close this issue once confirmed. Thank you again.
