### ISSUE TITLE
OkHttp-based implementation of client AbstractWebSocketTransport

### ISSUE THREAD

**Issue by nathklei** [cometd/cometd#807]
At my organization, we use OkHttp for our http clients. For consistency I wrote an implementation of AbstractWebsocketTransport using the OkHttp `WebSocket` and `WebSocketListener` APIs. If this seems generally useful I can work on making the code public.

**Comment by sbordet** [comment]
@nathklei yes it would be useful! - OkHttp has better Android support.
We have tests for various transports, so we can plug in this new one eventually.
FYI, CometD contribution guidelines: https://docs.cometd.org/current/reference/#_contribute_code
OkHttp is also AL2, so licensing wise there is no problem.

**Comment by nathklei** [comment]
I've pushed the client here: https://github.com/cometd/cometd/pull/808
Feel free to comment on the PR!

**Comment by sbordet** [comment]
@nathklei Thanks for the PR!
I'm currently busy on #795, so this has to wait a bit, but it's next on the list.

**Comment by JesseScott-MS** [comment]
I'm currently migrating from 2.X to 5.X (I know...) and am wanting to use OkHttp.
I'm struggling a bit with handling multiple connections like we did w/ the Jetty client.
I don't see any samples that use the `OkHttpClientTransport` - can that be added?

**Comment by sbordet** [comment]
@JesseScott-MS you should not worry about multiple connections, and you do not explain what the problem is.

Please open a new issue with exact details, and please upgrade to CometD 8.
