### ISSUE TITLE
Syntax error via cometd.js WorkerSchedule blob

### ISSUE THREAD

**Issue by giantninja** [cometd/cometd#813]
CometD Version: 3.1.6
Script: cometd.js
Console error: `Uncaught SyntaxError: Unexpected token }`

The Web Workers code in cometd.js in the logic block on lines 1466-1502 throws an error when creating a new Blob object with a source code string from line 1467 `var code = WorkerScheduler.toString();` 

The code variable is manipulated via regex and attempts to strip the function declaration and corresponding closing brace, but will not remove properly if the javascript code has been minified (as it often is).  It removes more than intended when the code is all on one line with no line breaks.

I would suggest extracting the function body/contents instead of trying to regex and remove the declaration, beginning brace and closing brace.  This is working for me with both minified and un-minified sources for the javascript:

replace lines 1466-1474 with this:

```js
if (window.Worker && window.Blob && window.URL && _config.useWorkerScheduler) {
    var code = WorkerScheduler.toString();
    // Extract the function body/contents.
    code = code.substring(code.indexOf("{") + 1, code.lastIndexOf("}"));
    var blob = new window.Blob([code], {
        type: 'application/json'
    });
```

There could be more effecient ways to extract the contents of the function, but seems to be more robust method of getting the code variable to it's intended result, no matter if `WorkerScheduler.toString()` returns a formatted or minified source code string.

**Comment by boris-petrov** [comment]
Same here but with version 4.0.1.
