### ISSUE TITLE
Cometd connect calls taking huge time respond, the waiting TTFb time is more than 30 seconds

### ISSUE THREAD

**Issue by sharneha** [cometd/cometd#817]
![cometd snapshot](https://user-images.githubusercontent.com/34139509/50780691-a0fa5e80-12c9-11e9-9d70-0fbdc1e60f6b.PNG)

**Comment by sbordet** [comment]
The default value for the `timeout` parameter is 30 seconds, so the behavior you report is known as long-polling and it's expected and correct.
