### ISSUE TITLE
No "connect" requests after "handshake" in IE and Edge unless "useWorkerScheduler" disabled

### ISSUE THREAD

**Issue by InGenius-Nick** [cometd/cometd#822]
CometD (4.0.2) is not making a request to "connect" after successful handshake in IE (11.785.16299.0) and Edge (41.16299.785.0). Code works in Firefox and Chrome.

If I disable a configuration option "useWorkerScheduler" it works. However, I cannot find any documentation on this option, it was found by reading the code. It seems that CometD will normally use a window.Worker to schedule requests to connect. IE and Edge will work when the option is disabled.

Is there any documentation on "useWorkerScheduler"?
Should I be doing something else to solve my problem?

**Comment by sbordet** [comment]
I will document `useWorkerScheduler`.

The workaround you found, to set `useWorkerScheduler=false` for Windows browsers is fine, although CometD is using standard browser APIs that must work in any browser :sob: 
I'll try to figure out why they don't work and see if this can be fixed.

**Comment by sbordet** [comment]
Found the cause of this issue.

The call to `window.URL.revokeObjectURL(blobURL);` revokes just the URL in Chrome and Firefox, but apparently revokes also the Worker in Edge.
Removing the call makes the Worker work fine in Edge.

@InGenius-Nick can you just remove that call from `cometd.js` and try it out in your application to confirm that the solution fixes the issue for you?

**Comment by InGenius-Nick** [comment]
That worked. I commented out the revokeObjectURL and set useWorkerScheduler back to false.

**Comment by sbordet** [comment]
Thanks for confirming!
