### ISSUE TITLE
to use Cometd  in Springboot

### ISSUE THREAD

**Issue by wubin19881121** [cometd/cometd#825]
I want to use cometd in the springboot framework .webcontainer is tomcat. Do you have demo.

**Comment by sbordet** [comment]
Yes there is a demo at https://github.com/cometd/cometd/blob/4.0.2/cometd-java/cometd-java-examples/cometd-java-examples-springboot/src/main/java/org/cometd/examples/spring/boot/CometDApplication.java.

The documentation is not online yet, but it's written, see https://github.com/cometd/cometd/blob/4.0.x/cometd-documentation/src/main/asciidoc/java_server_services_integration_spring.adoc#_java_server_services_integration_spring_boot.
