### ISSUE TITLE
Spring Boot 2.1.2.RELEASE Breaks CometD 4.0.2

### ISSUE THREAD

**Issue by pdavidson** [cometd/cometd#826]
I had CometD 4.0.x working with Spring Boot 2.1.1.RELEASE, when I upgraded to 2.1.2.RELEASE, I get the Missing WebSocket ServerContainer when trying to initialize the WebSocketTransport.  I know there's a jetty version upgrade in 2.1.2.RELEASE, not sure if that's the issue.

I'll provide more documentation later, but was hoping someone had already ran into this issue and had a solution.

**Comment by pdavidson** [comment]
It's not the jetty upgrade.  I just confirmed jetty version jetty-9.4.12.v20180830 fails with spring 2.1.2.RELEASE

**Comment by sbordet** [comment]
I just updated CometD 4.0.x with Spring Boot 2.1.2.RELEASE and the tests we have pass cleanly.

Can you please detail your setup, stack trace, etc.?

**Comment by pdavidson** [comment]
@sbordet thanks for looking into this - 

Here's the relevant stuff from my config:
```
    @Bean(initMethod = "start", destroyMethod = "stop")
    fun bayeuxServer( servletContext: ServletContext): BayeuxServerImpl {
        val server = BayeuxServerImpl()

        server.setOption("ws.cometdURLMapping", "/bridge/realtime/*")
        server.setTransports(WebSocketTransport(server), JSONTransport(server), JSONPTransport(server))

        server.setOption(ServletContext::class.java.name, servletContext)

        server.securityPolicy = securityPolicy()
        servletContext.setAttribute(BayeuxServer.ATTRIBUTE, server)
        return server
    }

    
    @Bean
    @DependsOn("bayeuxServer")
    fun cometDServletBean(): ServletRegistrationBean<CometDServlet> {
        val bean = ServletRegistrationBean<CometDServlet>(CometDServlet(), "/bridge/realtime/*")
        bean.setLoadOnStartup(1)
        bean.setName("cometd")
        bean.isAsyncSupported = true
        bean.initParameters = mapOf(
                "maxInterval" to "60000",
                "interval" to "0"
        )

        return bean
    }
```

Here's my stacktrace
```
Caused by: java.lang.IllegalArgumentException: Missing WebSocket ServerContainer
	at org.cometd.websocket.server.WebSocketTransport.init(WebSocketTransport.java:60)
	at org.cometd.server.BayeuxServerImpl.initializeServerTransports(BayeuxServerImpl.java:256)
	at org.cometd.server.BayeuxServerImpl.doStart(BayeuxServerImpl.java:136)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1870)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1813)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741)
```

**Comment by pdavidson** [comment]
I can confirm that the `JettyWebSocketServletWebServerCustomizer` is not being run prior to the WebSocketTransport being initialized in the bayeuxServer method.

**Comment by sbordet** [comment]
I'm not that familiar with Spring Boot to know what's the difference between annotating a class with `@SpringBootApplication` and doing what you're doing.
Either there is some step that you are not doing that `@SpringBootApplication` does under the covers, or there is a problem in Spring Boot.
Does not seem to be a CometD problem.

In the past I was starting from what it was working (e.g. the CometD Spring Boot example) and then one step at a time go towards the code I wanted.
At a certain step the Spring magic would break and I had a more precise place to look at.

Have you reported this to Spring Boot? If the same code is working in 2.1.1 and not working in 2.1.2, seems a regression in Spring Boot.

**Comment by pdavidson** [comment]
I started a from scratch app and it's working fine with 2.1.2.  I think we're just going to pull out WS support and fallback to long polling.

**Comment by sbordet** [comment]
@pdavidson sorry, not sure I understand.
Why would you pull out WS if it's working?

**Comment by pdavidson** [comment]
@sbordet - Since this was working in a demo app from scratch, it appears I was hitting a non deterministic issue on the spring side.  I've pulled the WSTransport out of our production app and just use long polling instead.
