### ISSUE TITLE
workerScheduler fails to instantiate in IE11/Edge

### ISSUE THREAD

**Issue by w0jcik** [cometd/cometd#831]
CometD 4.0.2 ->
Line 1475             window.URL.revokeObjectURL(blobURL);
It's causing worker to never instantiate in IE/Edge.
Blob URL is not supported by IE due to security restrictions.
IE has its own API for creating and downloading files, which is called msSaveOrOpenBlob.

Furthermore i managed to get cometD to work in IE11 by setting useWorkerScheduler=false in config. This flag isn't documented anywhere.

**Comment by w0jcik** [comment]
This seems to be a fix:
```
if (window.navigator && window.navigator.msSaveOrOpenBlob) {
                        var fileName = escapeHtml(data.name);
                        window.navigator.msSaveOrOpenBlob(blob, fileName);
                    } else {
                        var blobURL   = URL.createObjectURL(blob);
                    }
```

**Comment by sbordet** [comment]
@w0jcik this issue is a duplicate of #822. It's already fixed in the 3.1.8 and merged to the 4.0.x branch, so will be in 4.0.3, probably released next week.

**Comment by w0jcik** [comment]
@sbordet - any update on planned 4.0.3 release?

**Comment by sbordet** [comment]
@w0jcik I am waiting for the Jetty 9.4.15 release, hopefully early next week. CometD 4.0.3 will follow that.
