### ISSUE TITLE
Unhide secure cookies when behind TLS-originating HTTP-Proxy

### ISSUE THREAD

**Issue by twiechert** [cometd/cometd#833]
We use the Java cometd client behind a TLS-orginating http proxy. Thus, the communication between cometd client and proxy is unencrypted through plain http.

This will cause the Java cookie store used in `LongPollingTransport` to not expose cookies flagged by the server as `secure`

This is very likely to be the actual cause for https://github.com/cometd/cometd/issues/644.
Since we observed exactly the same error messages, eventually caused by the missing cookie Information.

Are you aware of a way to "convince" the cookie store to also expose the secure cookies. Or otherwise, do you consider it a useful feature in cometd to allow a workaround of this security feature in Java?

**Comment by sbordet** [comment]
I'm not sure I understand.
Are you saying that `BayeuxClient.getCookie(String)` returns `null` for a non-CometD cookie sent by the CometD server?

**Comment by twiechert** [comment]
`for (HttpCookie cookie : getCookieStore().get(uri))`in LongPollingTransport returns only cookies that have not been flagged as secure in case you pass an URL that does not start with `https`. This is a secuity feature but very annoying if the application sits behind a TLS originating http proxy:

Cometd App --> HTTP --> Envoy --> HTTPS -> Salesforce
(Salesforce returns secure cookies such as BAYEUX_BROWSER)

These cookies are omitted in the subsequent requests, thus leading to auth errors.

**Comment by sbordet** [comment]
Why is not "Envoy" stripping the `secure` flag?

**Comment by twiechert** [comment]
Yes, it can be built like this, modifying the response headers received by salesforce.

However, this seemed to have caused trouble for other people as well:
https://github.com/cometd/cometd/issues/644
(you find other references to this 403 error on google as well without clearly identified root cause)

So basically I wanted to create awareness for this "problem" and potentially help others who face the same issue.

A very simple "fix", yet not ideal would be to build the lookup url in `
LongPollingTransport`like this

`final URI uri = URI.create(url.replace("http://", "https://"));`

**Comment by sbordet** [comment]
@twiechert what about this: the retrieval of the cookies can be factored out to a method that you would be able to override and implement your logic.

Would that solve this issue?

**Comment by twiechert** [comment]
Sounds amazing :)

**Comment by sbordet** [comment]
@twiechert wanna give it a try and issue a PR? :)
