### ISSUE TITLE
Support WebSocket in Spring Boot example

### ISSUE THREAD

**Issue by qq61966100** [cometd/cometd#845]
Hi, I`m new to spring boot and cometd, some issue after I download the spring boot example
after I run the application,  console showed below message
'o.c.server.BayeuxServerImpl.1d035be3     : JSR 356 WebSocket classes available, but org.cometd.websocket.server.WebSocketTransport unavailable: JSR 356 WebSocket transport disabled'
and when I go to the url 'localhost:8080/cometd', response was 400, anyone can help me? why I got this issue?

**Comment by qq61966100** [comment]
![Image 12](https://user-images.githubusercontent.com/15924518/54251989-25948200-4584-11e9-903e-9d688b6e6fb8.png)

**Comment by qq61966100** [comment]
by the way, I changed the pom.xml, because 'cometd-java-examples-embedded' used project version, but can not found, so I changed it to version 4.0.3

**Comment by sbordet** [comment]
Thanks for reporting this, I will make sure that the Spring Boot example will work with WebSocket too.
The change requires a new dependency in the POM and a little bit of new code in the application class.

**Comment by qq61966100** [comment]
Got it,  many thanks, and waiting for the new version.

**Comment by qq61966100** [comment]
And any existing solution for the cometd if I want to change my project from spring to springboot ? 
Can I keep the old way  in spring ? But I tried it, the error message is can not found servletcontext

**Comment by sbordet** [comment]
@qq61966100 with commit 6a63498 I have updated the Spring Boot example to use WebSocket, thus getting rid of the warning you were seeing.
The changes interesting for you are the changed in `CometDApplication` and in the POM.

Let me know if those changes work for you too.

**Comment by qq61966100** [comment]
![image](https://user-images.githubusercontent.com/15924518/54402660-bf386c80-4707-11e9-81f2-e0ce44b62de7.png)
@sbordet Thanks for your support, And why the project version is 4.0.4, but plugin latest version is 4.0.3 in maven ?  And If I changed version manually the pom.xml occurred another error

**Comment by qq61966100** [comment]
sorry, I changed version to 4.0.3 , then clean the cache, The build error disappeared , and may I know how to test ? I tried to use the url 'localhost:8080/cometd' , is it correct? but I got 400
![image](https://user-images.githubusercontent.com/15924518/54403299-6f0ed980-470a-11e9-8bc2-a0148566e581.png)

**Comment by qq61966100** [comment]
And I tried to use junit, It looks fine

**Comment by qq61966100** [comment]
![image](https://user-images.githubusercontent.com/15924518/54405917-0e37cf00-4713-11e9-91a5-3aedccfa0d58.png)
Although I got the 'yahoo', but junit test failed

**Comment by sbordet** [comment]
@qq61966100 you have to build the latest CometD code, see https://docs.cometd.org/current/reference/#_build.

Once you have done that, you can reference CometD `4.0.4-SNAPSHOT` in your project, or run the tests that should pass cleanly.

Mixing 4.0.4-SNAPSHOT with CometD 4.0.3 won't work because while I was working on this issue I discovered #849, so you really need the latest CometD code.

**Comment by qq61966100** [comment]
@sbordet Got it, Let me try it follow the guide, so let`s close this issue, and any further question I`ll open new issue then, many thanks for your patient and support
