### ISSUE TITLE
Switch with possible null String object

### ISSUE THREAD

**Issue by jaypatel512** [cometd/cometd#850]
We are receiving null pointer exception in some very corner cases in production. Looking further, we noticed that we have a switch statement for `message.getChannel()`. We were wondering if the value of `getChannel()` could ever be null ? And if so, switch statement [won't be able to automatically run `default` codeblock](https://stackoverflow.com/questions/18263489/why-doesnt-string-switch-statement-support-a-null-case)

https://github.com/cometd/cometd/blob/6a63498dd8b60226e60f1b566d911fc8d3c34a4d/cometd-java/cometd-java-server/src/main/java/org/cometd/server/transport/AbstractHttpTransport.java#L162-L180

**Comment by sbordet** [comment]
A message without a channel is an invalid Bayeux message.

What client are you using?

**Comment by Iteratrix** [comment]
@jaypatel512 I think we may have run into something similar at one point. Any chance that you were trying to integrate with the Salesforce Streaming API?
