### ISSUE TITLE
OkHttpWebsocketTransport also handles ProtocolException

### ISSUE THREAD

**Issue by nathklei** [cometd/cometd#851]
OkHttp [propagates java.net.ProtocolException ](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.java#L222-L225) for adverse HTTP results on websocket open. 

Proposing a change to handle this in the OkHttpWebsocketTransport to allow retries.

**Comment by sbordet** [comment]
Fixed by #852. Thanks!
