### ISSUE TITLE
Cometd Listener going into pending state and taking time to connect with cometD 4.0.2 and  apache tomcat  8.5.6

### ISSUE THREAD

**Issue by PSHREYASHOLLA** [cometd/cometd#853]
Hi,

We were using comet-java-*-2.3.1 jars with jetty-*-7.4 and bayeux-api-2.3.1.jar.

Now we have upgraded to comet-java-*-4.0.2 with jetty-*-9.4.1 and bayeux-api-4.0.2.jar.

After upgrade, the long polling connectivity is happening in case of Wildfly 10.0 server,
But in case of Apache tomcat 856 server, after handshake below is the network on inspecting in chrome browser,
![image](https://user-images.githubusercontent.com/19671054/55874264-7f9e5c80-5baf-11e9-953f-d4a464ab4e59.png)

After handshake, the first connect is happening in 4ms but after that,

Below is the subsequent requests which is taking a minute and are pending for that long
![image](https://user-images.githubusercontent.com/19671054/55873969-a5773180-5bae-11e9-9589-c68773be18da.png)

Please let us know if there are any configuration that needs to be done for tomcat

**Comment by sbordet** [comment]
Replied to the mailing list. This is normal and expected behavior.
