### ISSUE TITLE
Handshake 404 ERROR (Wildfly + Angular 6)

### ISSUE THREAD

**Issue by skryabinvi** [cometd/cometd#856]
Hello! It's my first experience with Cometd. And i have some problems. 
I have a project: Java EE 8, Wildfly 10, Angular 6, Cometd 4.0.3, jetty 9.4.15.v20190215

My web.xml:

        <servlet>
                <servlet-name>cometd</servlet-name>
                <servlet-class>myproject.cometd.MyAnnotationCometDServlet</servlet-class>
                <load-on-startup>1</load-on-startup>
                <async-supported>true</async-supported>

                <init-param>
                    <param-name>ws.cometdURLMapping</param-name>
                    <param-value>/cometd/*</param-value>
                </init-param>
                <init-param>
                    <param-name>transports</param-name>
                    <param-value>org.cometd.websocket.server.WebSocketTransport, org.cometd.server.transport.JSONTransport, org.cometd.server.transport.JSONPTransport</param-value>
                </init-param>
                <init-param>
                    <param-name>services</param-name>
                    <param-value>myproject.cometd.SystemNotificationService</param-value>
                </init-param>
        </servlet>
        <servlet-mapping>
                <servlet-name>cometd</servlet-name>
                <url-pattern>/cometd/*</url-pattern>
        </servlet-mapping>

My angular code:

        constructor() {
            this.cometd.configure({
              url: location.origin + '/cometd',   //http://localhost:4200/cometd
              logLevel: 'info'
            });

            this.cometd.handshake(function(handshakeReply) {
              if (handshakeReply.successful) {     

                this.cometd.subscribe('/systemNotification', (message: Message) => {
                  console.log(message.data);              
                });
              }
            });
          }

So, i have a 404 error in browser console:

> POST http://localhost:4200/cometd/handshake 404 (Not Found)

My app work on URL: http://localhost:4200/
My server work on 8081 port.

In my app all http request start with http://localhost:4200/sur/
In proxy.local.config.json i have:

          "/sur": {
              "target": "http://localhost:8081",
              "secure": false
            }

If i send request http://localhost:4200/sur/cometd/handshake - i have 500 error:

> java.lang.IllegalStateException: UT010026: Async is not supported for this request, as not all filters or Servlets were marked as supporting async

I assume that the problem is in the wildfly settings or with the client proxying to the server.

Thank for any help!

**Comment by sbordet** [comment]
I'm not familiar with wildfly. Can you explain how you have the server on port 8081 but call CometD on port 4200?

If it's some kind of wildfly proxying, are you sure you are proxying CometD correctly?

**Comment by skryabinvi** [comment]
Oh, my stupid bad... 
I must send request http://localhost:4200/sur/cometd/handshake.
500 error tell me - server got request but throw exception. I forgot add async-supported = true to the filters.

Sorry and Thanks for help!

**Comment by skryabinvi** [comment]
Please tell me two more:
1) Is it normal for a client to send a "/connect" request every 30 seconds? I subscribe to the channel in the header of my site. It turns out that during the life of the entire session, the client will send requests every 30 seconds. This is normal? I'm just not good at this field ...
2) The subscribed channel  returns me information only if I reloging in to the system. If I just open a browser and go to the site through current session - cometd does not work. The channel does not give data.

**Comment by sbordet** [comment]
> Is it normal for a client to send a "/connect" request every 30 seconds? 

Yes it's normal. That is CometD doing "long-polling".

> The subscribed channel returns me information only if I reloging in to the system. 

You have to explain this in more details.
If you handshake and then subscribe to a channel, messages sent to that channel will be delivered to subscribers. There is no need to "re-login" or "re-handshake".

**Comment by skryabinvi** [comment]
1. OK. 

2. Again my bad. Problem on my code in front-side.

I have not any questions.

Thank you!
