### ISSUE TITLE
BayeuxClient retrying handshake forever, even in case of SSL failures

### ISSUE THREAD

**Issue by jaypatel512** [cometd/cometd#857]
Hey !

We see that the bayeux client keeps on retrying even if handshake failed with SSL error of hostname not valid.

What is the correct procedure to shutdown, or limit the retries during fatal errors like above.

Thanks.

**Comment by sbordet** [comment]
You call `BayeuxClient.disconnect()` to stop the handshake retries.
You use a `/meta/handshake` listener to count how many retries you want to do.

**Comment by jaypatel512** [comment]
Thanks @sbordet ! We will try that out. Thanks for all your help so far 🙇
