### ISSUE TITLE
CometD does not start when bundled with rollup and rollup-plugin-commonjs

### ISSUE THREAD

**Issue by bidorffOL** [cometd/cometd#863]
Ever since #858, I'm getting a `Cannot read property 'cometdRuntime' of undefined` when attempting to initialize CometD. I believe that it may be because I'm bundling CometD into my app using `rollup` and `rollup-plugin-commonjs`.

Shouldn't this patch be using `var runtime = root['cometdRuntime'];` instead of `var runtime = this['cometdRuntime'];` or check if `this` exists ?

**Comment by sbordet** [comment]
@bidorffOL `this` is being passed as an argument in the immediate invocation of the function.
For formal parameter that receives that argument is called `root`.
What environment are you using, where `this` is not defined?
In NodeJS, `root` and `this` will point to different objects (one to the module context, the other to the global context).

**Comment by bidorffOL** [comment]
I'm running the app in the browser. However, I'm using `rollup `to bundle my app as an 'IIFE' , this may be the reason why `this` is `undefined`.

**Comment by sbordet** [comment]
@bidorffOL CometD also uses IIFE, and `this` is defined.
Can you give me a small project that reproduces the error you have?

**Comment by bidorffOL** [comment]
I'm sorry for replying so late, [here](https://github.com/bidorffOL/cometd_defect_863) is a small example where you can reproduce the behavior (the error is shown in the devtools when browser-sync starts up).
(BTW, the error can't be reproduced with CometD <4.0.4)

**Comment by dirk-olmes** [comment]
I'm stumbling over the same issue, albeit I'm using rollupjs directly not via gulp. I have also put together [a small project](https://github.com/dirk-olmes/cometd-issue-863) to demo my use case.

**Comment by sbordet** [comment]
I'm out next week, but I will take a look and fix this issue (or rollback to previous code).
Thanks for the repro projects!

**Comment by sbordet** [comment]
I decided to rollback the fix for #858 (cometd/cometd-nodejs-client#17), so rollup should be fixed now.
