### ISSUE TITLE
How to use cometd when your client can't use cometd to manage the  http connections

### ISSUE THREAD

**Issue by CapVidotti** [cometd/cometd#867]
How to use cometd when your client can't use cometd to manage the  http connections?

My app needs to use a lib that manage the http connections in order to garantee the security. I can add new headers, for example. 

Today I have a chat using the bayeux transaction in short polling mode. I would like to move to long polling.

**Comment by sbordet** [comment]
You have to explain a bit more your case.

If you can use short polling with CometD, you can use long polling too.

> My app needs to use a lib that manage the http connections in order to guarantee the security.

What does that mean, in details?

> I can add new headers, for example.

If it's just about adding headers, you can already do it with CometD.

**Comment by sbordet** [comment]
No further activity, closing.
