### ISSUE TITLE
Messages lost when slow message processing

### ISSUE THREAD

**Issue by 3DRaven** [cometd/cometd#868]
Hi! 
When i make slow message processing in MessageListener then messages is lost. Example
new MessageListener() {
    @Override
    public void onMessage(ClientSessionChannel channel, Message message) {
     Thread.sleep(3000);    
    }
if i register this message listener on channel then messages is lost on client side when we have 100 messages per second. 50% messages is lost. How to process messages properly?

**Comment by sbordet** [comment]
Please read this section of the documentation: https://docs.cometd.org/current4/reference/#_concepts_threading
