### ISSUE TITLE
WebsockTransport mishandles websocket extensions

### ISSUE THREAD

**Issue by zenbones** [cometd/cometd#873]
The problematic code is this...

```java
@Override
public List<Extension> getNegotiatedExtensions(List<Extension> installed, List<Extension> requested) {
  List<Extension> negotiated = new ArrayList<>();
  for (Extension extension : requested) {
    String name = extension.getName();
    boolean option = getOption(ENABLE_EXTENSION_PREFIX_OPTION + name, true);
    if (option) {
      negotiated.add(extension);
    }
  }
  return negotiated;
}
```

The problems are...
1) The transport assumes that if the extensions is requested, and not explicitly turned off in the options, that it's negotiated, whether it's actually installed or not. If the option is true, we should still be checking whether there's an installed extension which at least has the same name as the requested extension.
2) The transport returns a list of requested extensions, and not a list of installed extensions. The requested extensions are just wrappers around the requested extension names and parameters. They have no intelligence or business logic and can't do anything but parrot back the requested names and parameters. The installed extensions contain the business logic and can return not only their names, but a set of parameters representing the implementations of the extension types that they are actually capable of supporting. As a consequence, the client, also CometD code, rightly rejects all attempts at Per Message Deflate extensions because the requested parameter 'client_max_window_bits' is just parroted back with no value. Whereas, if the negotiated extension which was returned was the installed extension, it could include a parameter set which made sense, with the proper values (if any) included.

I would suggest this code...

```java
@Override
public List<Extension> getNegotiatedExtensions(List<Extension> installed, List<Extension> requested) {
  HashSet<Extension> negotiated = new HashSet<>();

  for (Extension requestedExtension : requested) {
    String name = requestedExtension.getName();
    boolean option = getOption(ENABLE_EXTENSION_PREFIX_OPTION + name, true);
    if (option) {
      for (Extension installedExtension: installed) {
        if (installedExtension.getName().equals(name)) {
          negotiated.add(installedExtension);   
          break;
        }
      }
    }
  }
  return new LinkedList<>(negotiated);
}
```

**Comment by joakime** [comment]
> 2\. The transport returns a list of requested extensions, and not a list of installed extensions. The requested extensions are just wrappers around the requested extension names and parameters. They have no intelligence or business logic and can't do anything but parrot back the requested names and parameters. The installed extensions contain the business logic and can return not only their names, but a set of parameters representing the implementations of the extension types that they are actually capable of supporting. As a consequence, the client, also CometD code, rightly rejects all attempts at Per Message Deflate extensions because the requested parameter 'client_max_window_bits' is just parroted back with no value. Whereas, if the negotiated extension which was returned was the installed extension, it could include a parameter set which made sense, with the proper values (if any) included.

The [`javax.websocket.server.ServerEndpointConfig.Configurator.getNegotiatedExtensions(List<Extension> installed, List<Extension> requested)`](https://docs.oracle.com/javaee/7/api/javax/websocket/server/ServerEndpointConfig.Configurator.html#getNegotiatedExtensions-java.util.List-java.util.List-) works like this ...

1. The client makes a HTTP/1.1 WebSocket Upgrade request with offered `Sec-WebSocket-Extensions`
2. The javax.websocket implementation collects the Set of installed / supported extensions (by name, no parameters)
3. The javax.websocket implementation collects the list of requested Extension Configurations (name + parameters) from the upgrade request.
4. The javax.websocket implementation calls the `Configurator.getNegotiatedExtensions(installed, requested)` and gets a list of pre-negotiated extensions.
5. The javax.websocket implementation initializes each pre-negotiated extension in the order it was given on `Configurator.getNegotiatedExtensions(installed, requested)` return.
6. Each internal Extension implementation negotiates its own parameters.
7. The Upgrade Response header `Sec-WebSocket-Extensions` returns the actual negotiated extensions + parameters. (this can be the same or less than the list from `Configurator.getNegotiatedExtensions(installed, requested)` and the request `Sec-WebSocket-Extensions` header, but never more)
8. The websocket client can choose to use the extensions negotiated, or close the connection.

It is not possible for the installed list to have the parameters pre-configured.

The javax.websocket API for this is bad.

It should have had the contract ... `List<ExtensionConfig>  .getPreNegotiatedExtensionConfigs(Set<String> installedExtensionsByName, List<ExtensionConfig> requestedExtensionConfigs)`
