### ISSUE TITLE
Fatal error when running cometD primer 

### ISSUE THREAD

**Issue by laeeqkhan01** [cometd/cometd#876]
I followed instructions as described in

https://docs.cometd.org/current4/reference/#_primer_maven_way

it goes till step  "mvn install"  without error, but when I try to run it, I get following fata errors,

```
[INFO] jetty-9.4.18.v20190429; built: 2019-04-29T20:42:08.989Z; git: e1bc35120a6617ee3df052294e433f3a25ce7097; jvm 12.0.2+10
[WARNING] FATAL@null line:1 col:14 : org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 14; The processing instruction target matching "[xX][mM][lL]" is not allowed.
[WARNING] Failed startup of context o.e.j.m.p.JettyWebAppContext@177c41d7{/dojo-jetty9-primer,[file:///C:/workspace/tst/d_cmt/primer/t2/dojo-jetty9-primer/src/main/webapp/, file:///C:/workspace/tst/d_cmt/primer/t2/dojo-jetty9-primer/target/jetty_overlays/cometd-javascript-dojo-4_0_4_war/],UNAVAILABLE}{file:///C:/workspace/tst/d_cmt/primer/t2/dojo-jetty9-primer/src/main/webapp/}
org.xml.sax.SAXParseException: The processing instruction target matching "[xX][mM][lL]" is not allowed.
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException (ErrorHandlerWrapper.java:204)
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError (ErrorHandlerWrapper.java:178)
```

Also, when I try to go to page,  http://localhost:8080/dojo-jetty9-primer/

I get Error 503, 
This page isn’t working
Any ideas, what I could be doing wrong.

**Comment by sbordet** [comment]
This is typically due to the fact that there is a BOM at the beginning of the XML file.
You appear to be on Windows, so if you cut/pasted from the documentation to create the XML file, depending on the editor you used on Windows you have to disable the BOM (could be an option in the editor), or manually remove it from the file.
