### ISSUE TITLE
autoBatch doesn't work

### ISSUE THREAD

**Issue by boris-petrov** [cometd/cometd#877]
I'm not sure I correctly understand what `autoBatch` in JavaScript should do, but even when I set it to `false`, CometD batches a bunch of subscription/publishing messages that I do before the handshake is complete into one big websocket message and sends them over. This causes the dreaded `The decoded text message was too big for the output buffer and the endpoint does not support partial messages` error. Am I missing something and is there some way I could make CometD not do that? CometD version is 3.1.10.

**Comment by sbordet** [comment]
@boris-petrov you need to show the code.

If you do:

```javascript
cometd.handshake();
cometd.subscribe(...);
cometd.publish(...);
```

then it's wrong.

If you do:

```javascript
cometd.handshake(function(r) {
  if (r.successful) {
    cometd.subscribe(...);
    cometd.publish(...);
  }
});
```

then with WebSocket you should have 2 separate messages going out (unless you explicitly batch them together).

**Comment by boris-petrov** [comment]
@sbordet - I've always done like in your first example and it has always worked in the sense that once the handshake is successful, all subscriptions and publishing happens then. The only trouble is that all of them are sent as one websocket message. Are you saying that this was never intended to work and it worked by chance?

So what exactly does the `autoBatch` setting do?

**Comment by sbordet** [comment]
The first example is wrong (although it works) because you are not testing that the handshake is successful. This has always been documented, [here](https://docs.cometd.org/current4/reference/#_javascript_handshake).

The problem of your approach is that until the handshake is replied, CometD has to queue messages such as subscriptions or publishes (because it does not yet have a `clientId` to send them), and that is why you get all of them in a single WebSocket message.

Instead, if you wait for the handshake reply, CometD does not have to queue and can send subscriptions and publishes right away (because the `clientId` has arrived with the handshake reply).

The `autoBatch` configuration parameter is explained [here](https://docs.cometd.org/current4/reference/#_javascript_batch).
It is relevant only for HTTP, not WebSocket, I should clarify that in the documentation.

**Comment by boris-petrov** [comment]
Thanks for the response.

I do check for errors in my code, it's a bit more complicated than your example. But, in the end, that's what happens - handshake is called and then a bunch of subscribe/publish. And it's always been like this because it works and as you say, CometD takes care of queuing these requests which is very convenient and useful.

In order to do what you suggest (which I know will work) however, I will have to do that queuing myself which is what I was trying to avoid. I hoped that `autoBatch` would do exactly that - not batch these initial requests (as the documentation is a bit vague on exactly what it does). Obviously I was wrong.

What do you suggest I do? Implement the queuing mechanism myself? Perhaps an option in CometD about that would be useful so clients don't have to do that themselves?

Thanks again.

**Comment by sbordet** [comment]
You don't have to queue, just rearrange the code.

From 
```javascript
cometd.handshake();
cometd.subscribe(...);
cometd.publish(...);
...
```

to

```javascript
cometd.handshake();
afterHandshake();

function afterHandshake() {
  cometd.subscribe(...);
  cometd.publish(...);
  ...
}
```

to

```javascript
cometd.handshake(function(r) {
  if (r.successful) {
    afterHandshake();
  }
});
```

**Comment by boris-petrov** [comment]
Of course, that would be easy, however our application is very dynamic and I don't know in advance what subscriptions and publishing will be done. This is determined at runtime and is different every time/on every page.

**Comment by sbordet** [comment]
I guess you are waiting in your page for the load/ready event, or some framework does it for you.

You should be able to solve the issue in the same way, where _all_ your code is called _after_ the handshake reply returns - you just have to run your logic a little later.

Note that this will not have any performance impact, as the subscribe and publish messages will leave the client at exactly the same time (when the handshake reply is received).

**Comment by boris-petrov** [comment]
Well, it will have a minor performance impact, as sending multiple messages in a single websocked message is slightly faster than sending them one by one, correct?

In any case, I'll figure it out.

Just a few quick questions:

1) A `BayeuxServer.SessionListener`'s `sessionAdded` method (on the Java side) is called only when a new client connects, not on every subscription, right? What about reconnects for the same client - that is when the `'/meta/connect'` listener is called for the second time for a client - does that call `sessionAdded` anew on the backend?

2) Are `ServerSession`'s valid on the backend between multiple handshakes? That is if I have something like:

```java
@Listener(CHANNEL)
public void someRequest(ServerSession remote, ServerMessage message) {
	longRunningOperation(() => remote.deliver(remote, ...));
}
```

Imagine `longRunningOperation` takes a while and until it finishes the client re-handshakes a bunch of times. Is that `ServerSession remote` variable still valid and will this `deliver` call succeed? What about between reconnects?

Otherwise thanks again for the support! Feel free to close this issue at any time.

**Comment by sbordet** [comment]
> Well, it will have a minor performance impact, as sending multiple messages in a single websocked message is slightly faster than sending them one by one, correct?

Correct, IFF the WebSocket message does not fail because it's too large :wink: 

1. `sessionAdded()` is called when a client handshakes with the server. Could be a new client, could be an existing client that lost connection for long enough that is now re-handshaking. Subscriptions and `/meta/connect` messages do not cause this method to be invoked.
1. Running operations that takes a lot of time in a listener is _really_ wrong, as explained [here](https://docs.cometd.org/current4/reference/#_concepts_threading).

**Comment by boris-petrov** [comment]
About number 2 - I didn't explain it very well - of course I mean that `longRunningOperation` is an asynchronous method which spawns threads/uses async IO/whatever and calls the callback in a different thread than the original. That is, I'm not blocking the execution of the listener at all. But the question remains - is the `remote` variable still valid between re-handshaking? I guess it isn't between re-connects?

**Comment by sbordet** [comment]
Depends what you mean by "valid". If the client is re-handshaking, then on the server there will be a new `ServerSession` object representing the new handshake.

If the client is gone (e.g. all connections from that client are lost), the `ServerSession` object is "valid" on the server, but when the server-side application tries to deliver messages they will fail.
The session won't receive the heartbeats via  `/meta/connect` messages, so eventually the server will expire it.

**Comment by boris-petrov** [comment]
So in either case (re-handshake or re-connect) `remote.deliver(sender, ...)` will do nothing/throw an exception, right?

**Comment by sbordet** [comment]
`remote.deliver(...)` will enqueue the message on the session, and will try to flush it.
The flush may happen later (e.g. lazy channel) and possibly in another thread (e.g. waking up a suspended `/meta/connect`), so the sender won't know if the transport failed to write the messages.

**Comment by sbordet** [comment]
@boris-petrov seems this was clarified. If you're good, can you please close the issue?

**Comment by boris-petrov** [comment]
@sbordet - yes, thank you for the support!
