### ISSUE TITLE
The dojo.js file location was not found in the example

### ISSUE THREAD

**Issue by FC2333** [cometd/cometd#880]
<title>CometD Oort Auction Demo</title>
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Varela+Round">
  <link rel="stylesheet" type="text/css" href="auction/css/styles.css" />

  <script type="text/javascript" src="../js/dojo/dojo.js"></script>

  
  <script type="text/javascript" src="auction/js/prototype.js"></script>
  <script type="text/javascript" src='auction/js/scriptaculous.js'></script>
  <script type="text/javascript" src='auction/js/behaviour.js'></script>
  <script type="text/javascript" src='auction/js/builder.js'></script>
  <script type="text/javascript" src='auction/js/effects.js'></script>
  <script type="text/javascript" src='auction/js/controls.js'></script>
  <script type="text/javascript" src='auction/js/dragdrop.js'></script>
  <script type='text/javascript' src='auction/js/editinplace.js'></script>
  <script type='text/javascript' src='auction/js/dwr-util.js'></script>

  <script type="text/javascript">
    dojo.require('dojox.cometd');
    dojo.require("dojox.cometd.timesync");
    dojo.require("dojox.cometd.ack");

    dojo.addOnLoad(function()
    {
        var cometURL = location.href.replace(/\/auction\/.*$/, '') + "/cometd";
        dojox.cometd.init({ url: cometURL, logLevel: "info" });

        var tick=function()
        {
            var now=dojox.cometd.timesync.getServerDate();
            dojo.byId("time").innerHTML=now.toUTCString();
            now=now.getTime();
            var next=""+(1+now/1000);
            next=parseInt(next.split('.')[0])*1000+10;
            dojox.cometd.timesync.setTimeout(tick,next);
        };
        setTimeout(tick,1000);
    });
    dojo.addOnUnload(dojox.cometd, "disconnect"); 
  </script>

  <script type='text/javascript' src='auction/js/demo.js'></script>
</head>

**Comment by sbordet** [comment]
The problem could be that you have put the `dojo.js` file in a place that is not what is referenced by the snippet above.
