### ISSUE TITLE
How to broadcast in a clustered setup?

### ISSUE THREAD

**Issue by Pojahn-Netent** [cometd/cometd#888]
Using CometD 4.0.5, I am using a clustered setup to scale horizontally.

We have configured CometD to be server to client communication only. So the server decide when it's time to broadcast a message.

I wan't all the nodes in the cluster to broadcast a message to all their subscribers of a given channel. I don't however see a relevant method in org.cometd.oort.Oort to achieve this. The documentation seems to suggest that it's done this class.
Or do I simply need to call BayeuxServer.createChannelIfAbsent()?

**Comment by sbordet** [comment]
https://docs.cometd.org/current4/reference/#_broadcast_messages_forwarding
