### ISSUE TITLE
Support SameSite cookie attribute

### ISSUE THREAD

**Issue by sbordet** [cometd/cometd#889]
Chrome 80 will ship with enhanced support for cookies, see the specification: https://tools.ietf.org/html/draft-west-cookie-incrementalism-00.

Applications should be able to configure CometD with the `SameSite` cookie attribute.

**Comment by itselov** [comment]
Hi @sbordet,

Am I understand correct that this feature will be introduced in upcoming releases (3.1.12 and 4.0.6)?
If yes, when do you plan to release these new versions?

Application which I'm working on require SameSite support and depends on this feature.

TIA
Ilya

**Comment by sbordet** [comment]
@itselov you are correct on the release numbering that include this fix.

I was planning to wait for Jetty 9.4.25 before releasing the new CometD versions.
That may be subject to change if there is enough pressure from the community.

Can you detail how `SameSite` is required? For now browser will just emit a warning, and will probably remain a warning for a few more months AFAIU.

**Comment by itselov** [comment]
@sbordet, thx a lot for response.

> Can you detail how SameSite is required? For now browser will just emit a warning, and will probably remain a warning for a few more months AFAIU.

Correct, right now there are warnings only, but if I understand correct Chrome 80 stable build will be released at February 4, 2020.

Our product is REST API platform, which customers use to build theirs custom apps and UIs.
Unfortunately in enterprise world upgrade schedules are pretty conservative, so our rough estimation was:
* if we deliver new version of our product at mid December 2019
* our customers will take in consideration that new version available in the beginning of January 2020
* so they will have 2-3 weeks for testing their apps before deadline at the beginning of February.

> I was planning to wait for Jetty 9.4.25 before releasing the new CometD versions.
That may be subject to change if there is enough pressure from the community.

Jetty introduced SameSite support not so long ago (and we already using this version). so I hoped CometD will do the same :)

**Comment by sbordet** [comment]
@itselov CometD 3.1.12, 4.0.6 and 5.0.0-BETA1 have been released.
