### ISSUE TITLE
Which version of the JavaScript library should be used with a Java server running CometD 3.1.2?

### ISSUE THREAD

**Issue by swese44** [cometd/cometd#894]
Java server is running 3.1.2. Should our web client be running the npm `cometd` module version 3.1.2, or are there non-breaking improvements in the 3.1.x releases we should be using (latest is 3.1.12)? Or should we be using the 4.x branch?

Thanks!

**Comment by sbordet** [comment]
We always recommend to run the latest CometD versions on both client and server.
CometD 3.1.2 is quite old now and likely the Jetty version too, so if you can, upgrade the server, possibly to version 4.0.x.

The protocol did not change so you should be able to use CometD 3.1.12 on the client and older versions on the server.
