### ISSUE TITLE
Restrict characters in channel names

### ISSUE THREAD

**Issue by sbordet** [cometd/cometd#905]
As a follow up of #526, the client libraries should have a similar logic where Bayeux message fields that have restricted characters should be validated, and report an error if the user uses invalid characters.

**Comment by boris-petrov** [comment]
@sbordet this works good, however I again hit the problem with exceptions being logged with the wrong logger... this time on the frontend. :smile: 

[Here](https://github.com/cometd/cometd/blob/7.0.8/cometd-javascript/common/src/main/webapp/js/cometd/cometd.js#L2828) an exception is logged with `console.info`. It's obviously an exception and (most likely) a user error. Why is it logged with `info` and not with `warn` or (even better) `error`?

**Comment by sbordet** [comment]
Because throwing from a batch function may or may not be a real problem.
Only applications can decide the level of the problem (not CometD), so the best way is for you to catch the exception in your application, and act accordingly.

**Comment by boris-petrov** [comment]
In the case of using restricted characters in channel names - that's **always** a problem I believe. But OK, I'll go with that, thanks for the answer!
