### ISSUE TITLE
subscribeProps an object to be merged with the subscribe message is set to undefined

### ISSUE THREAD

**Issue by rameshmurthy** [cometd/cometd#915]
Hi,
CometD java script client allows to subscribe to a channel using the subscribe method. Please follow the link (https://github.com/cometd/cometd/blob/5.0.x/cometd-javascript/common/src/main/webapp/js/cometd/cometd.js#L2795)

`this.subscribe = function(channel, scope, callback, subscribeProps, subscribeCallback) {
`
This method accepts `subscribeProps` argument. Internally it has some logic that sets it to undefined. So, even when we pass the value to `subscribeProps` it gets set to undefined. During normalization of arguments it is lost.

Here is the code here it sets to undefined:

```
            // Normalize arguments
            if (_isFunction(scope)) {
                subscribeCallback = subscribeProps;
                subscribeProps = callback;
                callback = scope;
                scope = undefined;
            }
            if (_isFunction(subscribeProps)) {
                subscribeCallback = subscribeProps;
                subscribeProps = undefined;
            }
```
(https://github.com/cometd/cometd/blob/5.0.x/cometd-javascript/common/src/main/webapp/js/cometd/cometd.js#L2829)

Thanks

**Comment by sbordet** [comment]
I don't understand?
What is the problem? 
Can you show a clear example of how you use that code, what you expect to happen, and what happens instead?

**Comment by rameshmurthy** [comment]
Excuse me for not making it clear.
I am working on a channel subscription authorization. Currently we are not passing any information with channel subscription request. When i looked at source code of cometd.js i found out it allows us to pass `subscribeProps` which is sent to the server as part of channel subscription request. I can use that information on the server to perform my channel subscription authorization.

Later i found out a link which has described my approach, for your reference providing here. This is using 2.1 version.
https://objectpartners.com/2012/09/27/using-cometds-hidden-subscribeprops/

may be due to legacy reasons the method call we have currently was (we are passing two functions after channel name parameter. I dont know the reason, i am looking into it internally.)
`client.subscribe("/test/channel", this.handleRespons.bind(this),  this.CallBack)`

I have changed it to 
```
let subscribeProps = { test : "test_value" }; // Assuming this will be sent to server for channel subscription
`client.subscribe("/test/channel", this.handleRespons.bind(this),  this.CallBack, subscribeProps)`
```
During normalization of parameters inside the subscribe method it is setting `scope = undefined and subscribeProps = undefined.`

**Comment by sbordet** [comment]
I still don't understand.

`this.Callback` should be the last parameter as described in the jsdoc.

`client.subscribe(channel, messageFunction, subscribeProps, subscribeCallback)`.

I think you are getting the order of the parameters wrong.

**Comment by rameshmurthy** [comment]
I think I should say this as not issue. Sorry for the confusion.
May be this is more of a ask how to pass the subscribeProps. I think that you have explained it rightly. Let us close the issue, thank you for your help.
