### ISSUE TITLE
Expired sessions being disconnected with Websocket transport

### ISSUE THREAD

**Issue by nathklei** [cometd/cometd#921]
I'll try to explain what I'm seeing as best as I can - it's fairly difficult to reproduce at the moment but I think I have a bit of an idea what's going on.

Background:
* Using the WebSocketTransport on the server
* Using the javascript client
* Using the AcknowledgedMessagesExtension on server and client

What I'm seeing is that from time to time, the server sends the client a /meta/connect message with an advice of "reconnect":"none" combined with a 402::unknown_session message. The later one makes sense - it's been more than 10s interval from what I'm seeing - but the "none" reconnect disconnects the client, and is not consistent with what I'm seeing in the unknownSession logic.

I've traced the logic to AbstractWebSocketEndPoint#resume, where we have this logic:

https://github.com/cometd/cometd/blob/5.0.x/cometd-java/cometd-java-server/cometd-java-server-websocket/cometd-java-server-websocket-common/src/main/java/org/cometd/server/websocket/common/AbstractWebSocketEndPoint.java#L257-L259

which would overwrite any original reconnect value.

Based on other examples, I suspect this should be session.isDisconnected instead of isTerminated - since expired is considered terminated. This would make the client re-handshake rather than disconnect.  This seems to be what the HTTP transport does, for example.

I have not been able to put together a minimal repro of this behavior, though can investigate if this needs additional detail.

Thank you!

**Comment by nathklei** [comment]
Or, an alternative would be to use putIfAbsent rather than a put to avoid overwriting the value set by unknownSession(), it seems.

**Comment by nathklei** [comment]
I've put the first approach in this PR: https://github.com/cometd/cometd/pull/922

**Comment by nathklei** [comment]
One more data point in a report I've received - there is a ~39 second difference between when the client sent the last /meta/connect message (with ID 293 in this example) and the server sent the "402::unknown_session" back with the same ID (293).  Prior to that, the replies were consistently coming back every 30s - the default for timeout.  Do you have any ideas on what could cause that irregularity? Some sort of scheduling / timing issue? I likely want to look into this as well, but if we sent "reconnect":"handshake" it would at least allow the client to reconnect properly.

**Comment by sbordet** [comment]
@nathklei do you have more information about this ~39 s "timeout" that is handled incorrectly? Maybe DEBUG logs?

**Comment by sbordet** [comment]
@nathklei are you able to test the latest `5.0.x` code with the fix?

**Comment by nathklei** [comment]
Hey @sbordet I unfortunately do not have a reliable repro, and have not (yet) added DEBUG to one of our systems where we've repro'd the issue. I do have some chrome debugger websocket payloads that may help provided by the user who reported the issue:

```
          {
            "type": "receive",
            "time": 1593552350.9356,
            "opcode": 1,
            "data": "[{\"ext\":{\"ack\":73},\"channel\":\"/meta/connect\",\"id\":\"290\",\"successful\":true}]"
          },
          {
            "type": "send",
            "time": 1593552350.937186,
            "opcode": 1,
            "data": "[{\"id\":\"291\",\"channel\":\"/meta/connect\",\"connectionType\":\"websocket\",\"clientId\":\"ix1ynlhdesmdy3egcicmoca7o\",\"ext\":{\"ack\":73}}]"
          },
          {
            "type": "receive",
            "time": 1593552380.97698,
            "opcode": 1,
            "data": "[{\"ext\":{\"ack\":74},\"channel\":\"/meta/connect\",\"id\":\"291\",\"successful\":true}]"
          },
          {
            "type": "send",
            "time": 1593552380.978484,
            "opcode": 1,
            "data": "[{\"id\":\"292\",\"channel\":\"/meta/connect\",\"connectionType\":\"websocket\",\"clientId\":\"ix1ynlhdesmdy3egcicmoca7o\",\"ext\":{\"ack\":74}}]"
          },
          {
            "type": "receive",
            "time": 1593552411.020224,
            "opcode": 1,
            "data": "[{\"ext\":{\"ack\":75},\"channel\":\"/meta/connect\",\"id\":\"292\",\"successful\":true}]"
          },
          {
            "type": "send",
            "time": 1593552411.0219991,
            "opcode": 1,
            "data": "[{\"id\":\"293\",\"channel\":\"/meta/connect\",\"connectionType\":\"websocket\",\"clientId\":\"ix1ynlhdesmdy3egcicmoca7o\",\"ext\":{\"ack\":75}}]"
          },
          {
            "type": "receive",
            "time": 1593552450.402819,
            "opcode": 1,
            "data": "[{\"ext\":{\"ack\":76},\"advice\":{\"interval\":0,\"reconnect\":\"none\"},\"channel\":\"/meta/connect\",\"id\":\"293\",\"error\":\"402::unknown_session\",\"successful\":false}]"
          }
```

The ~39 second gap is in between when the client sent its last ack to when the server replied with the 402. This is with the default settings of 30000 ms timeout and 10000 ms maxInterval.

I studied the code a fair amount and it seems like if there is a delay in resuming the suspended /meta/connect reply, through a busy server or something of that nature, we could end up in this scenario that I am seeing.

**Comment by nathklei** [comment]
@sbordet really appreciate you helping with this, as well! Would you be able to create a release so I can fully integrate this change?
