### ISSUE TITLE
Question: Expected Behavior for Rehandshaking, Subscriptions and Acknowledgements

### ISSUE THREAD

**Issue by nathklei** [cometd/cometd#927]
Hello - I've been looking into how rehandshaking works, as from time to time I must re-authenticate my client with the service using a new credential.

I've figured out how to pass the new credential - simply mutate the handshake message that I initially sent into the original handshake with my new credential (though maybe a more explicit mechanism should be provided!). However, when I do rehandshake, I've been observing some behaviors that I want to make sure I understand:

1. Subscriptions are reset - I need to keep track of any subscriptions and explicitly resubscribe. This happens here: https://github.com/cometd/cometd/blob/5.0.x/cometd-java/cometd-java-client/cometd-java-client-common/src/main/java/org/cometd/client/BayeuxClient.java#L1394. I could override resetSubscriptions to no-op, but I'm not sure what consequences that may have / why this logic exists.
2. The message ack is re-added to the existing session after it reshandshakes. It does not check if the session already has the session installed. Is this expected to cause issues? I wrapped the extension in one that checked for existence, but I'm not sure what side effects that may have.
3. Because of 1) and possibly 2), if a message is published to a channel while a client is REHANDSHAKING, that the client was subscribed to before entering REHANDSHAKING, it is received by the client but not delivered to any listener callbacks. 

Was my understanding correct, and if so, is there any way to improve the handling of message delivery during REHANDSHAKING? Possibly retain the messages on the server and delivering once re-handshook? Or am I misunderstanding something?

**Comment by nathklei** [comment]
I suspect the reason 1) exists is that you do not know whether or not the client should be allowed to be subscribed once they re-handshake. What's interesting is that there's nothing that clears the session's subscriptions on the server, though, as far as I can tell.

**Comment by sbordet** [comment]
> from time to time I must re-authenticate my client with the service using a new credential

Is it the server that decides this? I.e. the server sends down a message with `advice: { reconnect: "handshake" }`?

1. if you re-handshake you will have a different session ID, so for the server the new handshake produces an entirely new session. Even if subscriptions for the previous session remain active on the server, they belong to a different session -- even if logically you consider them the same.

If you want to re-subscribe, see how to do it in #798.

2. I am not sure I understand this?

3. Not sure I understand this one either. Is the message published by the client or by the server?

If it is the server that decides for the re-handshake, it should disconnect the session (which resets all server subscriptions) and along with that add an `advice: { reconnect: "handshake" }`.

If it is the client that is re-handshaking, it should not send messages while it is doing so and wait until the re-handshake and until subscriptions are restored.

**Comment by nathklei** [comment]
@sbordet yes it is the server that determines this - the credential has a time to live, and the server tells the client when it needs to present a new one.

Thanks for the example - that's roughly how I am doing my re-subscription.

I think what I was missing is that when I send the "reconnect": "handshake", I do not send a disconnect. What I was seeing is that the re-handshake was NOT creating a new session, which e.g. caused the extension to be added twice.

To confirm, for 3 - since I am establishing a new session / subscription, there is a (very small) period during which I can lose messages.  Is that right?

**Comment by sbordet** [comment]
@nathklei if it is the server that determines whether a re-handshake is necessary, you should disconnect the client via `ServerSession.disconnect()`.

This will clear all server-side data structures for that session (i.e. subscriptions), so messages after the call to `disconnect()` will be "lost".

Uhm. With this, however, the client will get a `reconnect: none` and disconnect for good. There are ways to re-handshake but they're quite cumbersome - maybe we can improve here.

Can you explain what happens exactly on the server when it determines that the client must re-handshake?
How does the client know the new credential?

Point being that maybe using handshakes for this kind of application authentication is not the right choice -- maybe you can do it with application messages so that you will only have 1 session, no messages lost, etc.

**Comment by nathklei** [comment]
Hey @sbordet your part about the client permanently disconnecting is exactly the issue I was running into when I was previously using .disconnect().  I didn't want to encode large amounts of logic on disconnect to then know to reconstruct a brand new client (which I'll need to swap in with my old one, etc) so keeping the same client reference is greatly preferred - and doing a re-handshake seemed to do almost exactly that!

For your question about how the client knows the new credential, it depends somewhat, but generally my client has a mechanism for "refreshing" its credential as necessary as part of an oauth2 flow, and is periodically able to get a new API token that can be used to re-authenticate.  The server detects that the token in the session state is invalid - it is stored as a known session attribute - and tells the client via a "402::unknwon_session" error with "reconnect":"handshake" advice, very similar to the unknownSession logic when the cometd session cannot be located. 

Point taken about using application messages vs handshakes. If that maintains continuity for the session's acknowledged messages, I will investigate it. It means that I need my different clients (javascript, java) to hold this logic, but I can control that - I was trying to use the built-in concepts to improve portability.

**Comment by nathklei** [comment]
@sbordet for an application-specific message, would you recommend putting these as replies on /meta/connect, or make a new channel for such a thing?

**Comment by sbordet** [comment]
@nathklei I'd let CometD do the handshake. From the client successful handshake callback, I would batch the CometD subscriptions and a message to `/service/login` that contains the credentials, with a reply from the server (or you can use the CometD `remoteCall()` APIs).

The client should always renew the credentials before the server detects the credentials expiration.
Alternatively, the server may send a message to the client that the credentials are expired, and the client arranges to renew them.
However, there will be a window of time where the credentials are expired, but messages to subscribers continue to flow -- perhaps until a `maxWindow` parameter.

If the server detects credentials expiration, it CometD `disconnect()`s the client.

How does that sound?

**Comment by nathklei** [comment]
That makes sense. I think I can work with what you've outlined - I understand things a bit better and why trying to hijack handshaking for this purpose is not the best long-term. We can close this out for now - I appreciate you getting back to me so quickly!
