### ISSUE TITLE
Discontinuing message processing in Extension results in 404::message_deleted error

### ISSUE THREAD

**Issue by nathklei** [cometd/cometd#928]
I may be misunderstanding the API a bit, but if I return "false" from an extension (in this case, I have an extension that tells the client to re-handshake under some condition - set a reconnect: handshake advice and return false) then I always get "404::message_deleted" in the reply message because of this code in BayeuxServerImpl:

```
                if (!reply.isHandled()) {
                    error(reply, "404::message_deleted");
                }
```

There's no public API to set handled boolean. I can cast to the implementation and set it, but also would like to know if this is the appropriate usage of the API.  I see no usages of setHandled anywhere in the cometd codebase.

**Comment by sbordet** [comment]
Can you detail why you are deleting message replies?

> I have an extension that tells the client to re-handshake under some condition - set a reconnect: handshake advice and return `false`

You should return `true` and the advice will do the rest.
Have you tried returning `true` already?

**Comment by nathklei** [comment]
I think I just misunderstood the docs for the extension - I'll return true and things should be OK - I was trying to stop processing of the incoming message from within the extension, as I had determined that I wanted the client to re-handshake.

**Comment by sbordet** [comment]
@nathklei exactly what docs did you misunderstand? Perhaps we can improve them.

**Comment by nathklei** [comment]
From rcvMetadata in Extension, where I took "should continue" as, if I return false, I will immediately reply.

```
         * @return whether message processing should continue
```

In my case, I do NOT want to continue processing the message. I've gotten a /meta/connect message for a session where the underlying session needs to be refreshed - that is, I need the client to resend its credential, and re-handshaking seemed like the way to do that.

However, I've tried always returning "true" and now the re-handshake isn't triggered because the server always resets "success" on the outbound message, removing my previously set value of "false":

https://github.com/cometd/cometd/blob/5.0.x/cometd-java/cometd-java-server/cometd-java-server-common/src/main/java/org/cometd/server/BayeuxServerImpl.java#L1354

Would it be helpful if I wrote out the desired outcome?

**Comment by sbordet** [comment]
I'm so confused.

What message are you trying to stop the processing? a `/meta/connect` message? If that's the case, why you don't want to continue processing that message? It's a `meta` message and applications should not mess with them unless they know what they're doing.

Can you please detail exactly what you are trying to do, make channel explicit, detail exactly what messages you intercept in the extension, etc. and detail what you expect and what happens instead?

**Comment by nathklei** [comment]
@sbordet this is related to the other question, I have an extension where:
1. For a `/meta/connect` message, evaluate a session attribute referencing an API token against authentication system. This also refreshes said authentication system's idle timeout
2. If the authentication system tells me that the credential is expired, find a way to instruct the client to re-send a new one.
3. (here's where the other question came into play) To do this, send the client a reply on `/meta/connect` with successful: false, and a "reconnect":"handshake" advice, which instructs them to re-send handshake message.  The client handshake message will be mutated in memory (I see no way to set the backing map in BayeuxClient).
4. If I've determined the session is invalid and I sent a re-handshake reply, return false, otherwise things do not work as expected.

Based on the conversation in #927 this is not conventional, and moving to a /service/login or /service/relogin type system would be preferred.

I guess, to close this out, IS there a conventional way for the server to tell the client to re-handshake, other than disconnect (thus forcing the client to reconstruct itself)?

**Comment by sbordet** [comment]
> is there a conventional way for the server to tell the client to re-handshake, other than disconnect?

The conventional way would be to write an extension and add the advice to the `/meta/connect` reply, which is a bit cumbersome to code -- we could make it simpler but it's a rare use case.

However, a re-handshake comes with its price, which is the creation of a new session, the reset of the subscriptions, windows of lost messages, etc.
It's a new handshake, not a "refresh".

Your case seems more like a "refresh", which is why I think using application messages would be better.

**Comment by nathklei** [comment]
Ok cool - so I am doing things the conventional way (write an extension to add advice to /meta/connect replies), except that when I return "true" from my extension, "successful" is set to "true" and the rehandshake does not occur. It seems that only if the reply says "successful":false do things work properly.

That said, I don't think this is worth investigating further as I'm going to experiment with application messages.

**Comment by sbordet** [comment]
I think you are intercepting the incoming (to the server) `/meta/connect`, while you should intercept in the extension the `/meta/connect` reply outgoing from the server.

Adding `advice: { reconnect: "handshake" }` to the `/meta/connect` reply and possibly make it `successful: false` should be enough to make the client re-handshake. If it's not enough, I think it's a bug.

**Comment by nathklei** [comment]
Ah! ok. That was exactly it. I was implementing rcvMetadata - but implementing sendMeta works perfectly. Thanks - apologies for the confusion.
