### ISSUE TITLE
Slow data channels with big batch download

### ISSUE THREAD

**Issue by lmartorella** [cometd/cometd#930]
Hi,
I've found a CometD issue triggered by the combination of two factors:

- Slow network infrastructure / connection
- High volumes of subscribed data in a single batch

and I hope that the CometD protocol can be enhanced in order to take in account such scenario. I'm using the Javascript client and WebSockets.

If the HTTP channel takes more than the configured client-side `maxNetworkDelay` time to download a batch of data from the server, it can happen that the client code drops the connection with "Message Timeout" error message. (I see that `/meta/connect` messages will wait more, and precisely (`maxNetworkDelay + timeout`), but the channel drop can be caused even by other `/subscribe` messages performed at the beginning of the batch subscription).

What is happening is that the websocket incoming channel will be clogged by a big amount of messages coming from the snapshot of the subscriptions. This causes the responses to `/meta/connect` and to other `/subscription` messages to be put in queue, reaching the client potentially after the `maxNetworkDelay` time, causing the premature channel closure.

I understand that the very reason of such `maxNetworkDelay` flag is to exactly cover this scenario. 
However, since I cannot predict the amount of the data that should be downloaded in a batch, I'm forced to put there a high period to cover the worst case scenario (something like 60 seconds in some cases).

This however can hide other issues, in which some message response are really delayed too much when the system load is low (for instance after the batch download is finished).

I was wondering if it would be possible to implement a different logic to let the client to not drop the connection in case of a steady incoming data flow. I was trying to do some experiment in that direction, but I've found that in this case, it is the server that will terminate the session: the client will not be able to perform a new `/meta/channel` request after the server 'closed' the previous request.

Is there some additional flag that can be used to cover this scenario, without the need to use huge values of `maxNetworkDelay`? 

Perhaps, I'm just guessing, a good solution could be a sort of 'heartbeat' message that the client regularly send to the server, but not related to the `/meta/connect` traffic, that can inform the server about the client download progress in case of slow channel/big amount of data. When the server receives the periodic hearbeat message (that can contains the message.id of the last message processed), it could adapt the session timeouts to take in account the global end-to-end delay. 
I think the AckExtensions is not useful in this case, since it only transport information on the `/meta/connect` message. 

What do you think?

Thanks, Luciano

**Comment by sbordet** [comment]
CometD is not really meant for big downloads - the idea is web messaging, not web downloads.

Do you have these download spikes only at subscription time, or they may always happen?
Have you tried gzipping and using the CometD binary extension?

Let's say that the client subscribes to 42 channels. As soon as it subscribes, it receives so many messages that the reply to the subscription is delayed more than `maxNetworkInterval`.
How would the client know that one particular subscription has been delayed by the messages from another subscription?
For example, let's say that you subscribe to `/chan1` and to `/chan2`, and `/chan1` has a lot of messages, but `/chan2` requires to contact an external service to confirm the subscription.
Now the client sees a lot of messages from `/chan1`, but no reply for the subscription to `/chan2` because the external service is slow to confirm the subscription.

In this case you have a steady incoming data flow, but it's unrelated to `/chan2` that should in fact fail after `maxNetworkDelay`.

Note that the `maxNetworkDelay` may be changed dynamically since #507.

It's a tough problem and I don't see any generic solution that can be implemented by CometD, but I'm open to suggestions.

For this kind of large "downloads" I've seen using a side transport that was not CometD (i.e. plain HTTP or similar).

**Comment by lmartorella** [comment]
Hi,
Thanks for your response.

I confirm that I'm already leveraging the binary extension for large packets.

Your idea to throttle `maxNetworkDelay` dynamically can be a solution. A possible implementation can be, for example, to update this value in reaction to a detected slowness (or to a recovered speed) using some extension like the Timestamp Extension.

Supposing that the network channel (physical connection, routing infrastructure, etc..) won't cache so many data, the server will be able to detect slowness in download since the TCP/WebSocket channel will clog at server side. If I'm not wrong, this behavior is currently tested by `SlowConnectionTest` test. So the Timestamp Extension can be effectively used for slow channel detection (and for fine end-to-end calc).

(Nothing can be done in case of a network infrastructure that can queue data indefinitely: but the TCP congestion support should prevent this behavior).

However, changing `maxNetworkDelay` at runtime won't affect the messages already on-the-fly: `setTimeout` is already performed during message send (at least in the Javascript implementation). If so, a fix is still required in the JS client: all the pending timeouts should be reset/rearmed/updated in case of `maxNetworkDelay` update.

Now, coming to your `\chan1` vs `\chan2` example, I see your point: in any case, increasing `maxNetworkDelay` will affect both channels, regardless their content and bandwidth usage. In that case, the client won't be able to detect `/chan2` applicative timeouts effectively.

However, let's try go more in deep about this specific example, dissecting all the possible ways the CometD protocol is currently transporting 'timeout' information. 

If the applicative server (`/chan2` server-side implementation) is implicitly relying on the CometD protocol to transport a 'timeout' failure (connecting to external resources), the effective timeout value will be affected by the `maxNetworkDelay` of the current client-side setting. 

Higher is set the max delay value (e.g. to support slow network), more "grace time" is indirectly allowed to the server in contacting the external resources. This introduces a variability in server behavior, that should finally be independent on the quality of the particular client connection.

Let's instead suppose now that the CometD server instance is always *canonical*, that we can define as "the server will always respond to all messages, meta and applicative, with success or fail messages". 

A "canonical" server, following the above definition, can indeed fail in many views: but in any case it will always try to report exceptions based on the context (e.g. reporting errors in the applicative channels, in the `/meta/connect` responses, or dropping the socket in serious cases). All these behaviors are currently implemented in CometD.

A 'canonical' version of the `/chan2` application can be implemented with an explicit timeout check _inside the applicative server-side code_. In case of timeout contacting the external resource, the `/chan2` request will be rejected with an applicative error.

The bare CometD server seems already to respect the 'canonical' definition in the all the protocol messages (`meta/connect`, subscriptions, unsubscriptions). In case that the application as well is following the same constraint, we could ideally removing the `maxNetworkDelay` client-side check. 

Or, better, we can relax it a bit, using it as a timeout for the very first incoming message received by the server (that proves that the whole server/connection is still alive in his canonical form). For every new valid message received, the timeout can be reset.

In the https://github.com/iongroup/cometd/tree/big-download branch I've tried to implement such logic in the JS client. In addition, I have prepared a UT test that checks that no disconnection is detected in this extreme cases (download of many messages simulating a slow channel).

I think this new feature can be safely enabled by all 'canonical' applications that always uses explicit timeouts, instead of relying on the implicit ones offered by the protocol. 

What do you think?
Thanks, Luciano

**Comment by sbordet** [comment]
@lmartorella, after some discussion with colleagues, there may be a better solution - using an extension to dynamically increase the `maxNetworkDelay` without having to change the CometD internals.

I'll try to code one in the next days and you can try it out.

**Comment by sbordet** [comment]
@lmartorella I just pushed an implementation for this feature.

It relies on listeners, so now you can do this:

```java
BayeuxClient client = ...;
client.addTransportListener(new TransportListener() {
  public void onTimeout(List<? extends Message> messages, Promise<Long> promise) {
    if (myLogic()) {
      // Extend the wait by 1 second.
      promise.succeed(1000);
    } else {
      // Do not extend the wait.
      promise.succeed(0);
    }
  }
});
```

Can you [build](https://docs.cometd.org/current/reference/#_build) the latest CometD 5.0.x branch and try it out?

**Comment by sbordet** [comment]
@lmartorella have you got the chance to try this out?

**Comment by lmartorella** [comment]
Hello, unfortunately not yet. I'll have a try next week.
Thanks! L

**Comment by sbordet** [comment]
Implemented.
