### ISSUE TITLE
Clients cannot determine if subscription message is sent

### ISSUE THREAD

**Issue by nathklei** [cometd/cometd#933]
The java client returns a boolean for the subscriber to know whether a subscription message was sent (and therefore, whether they should expect the subscribeCallback to be executed with success or failure of the subscription).

In the javascript API, subscribe() returns the subscription handle, but there seems to be no way to determine whether the message was sent. This complicates application logic that wants to handle subscription errors, as it can't know whether it should expect the callback to be executed. 

Is it possible to add similar functionality to the javascript client - or possibly internally call the subscribeCallback (though that may be a semantic break for consumers)?

**Comment by nathklei** [comment]
An alternative approach would be to always execute the callback, by 1) storing the successful subscription message from an existing subscribe() call, and immediately invoking the callback with this message and 2) if there's still an outstanding remote subscription, chaining the additional subscribeCallback(s) after invoking the first one.

In my opinion that would make the API a bit less surprising, as consumers will always expect the subscribeCallback to execute.

**Comment by sbordet** [comment]
@nathklei why would not a subscribe message be sent? because of client-side extensions that block it?

**Comment by nathklei** [comment]
Reading this code:
https://github.com/cometd/cometd/blob/5.0.x/cometd-javascript/common/src/main/webapp/js/cometd/cometd.js#L2919

if there is an existing subscription then a subscribe message is not sent, and therefore subscribeCallback is not called - so client code relying on that callback running will not function properly. This makes certain types of client applications difficult to code properly to handle subscription issues if there are possibly more than one logical subscriber.

Am I misunderstanding this?

**Comment by sbordet** [comment]
@nathklei thanks, I understand now. Pondering...

**Comment by nathklei** [comment]
Thanks for taking a look!

**Comment by nathklei** [comment]
Thinking about this a bit more, a solution that always calls the subscribeCallback, regardless of whether a subscribe message is sent, would seem the least surprising from a consuming perspective, but understand that it would possibly be a semantic break / complicated to implement.

**Comment by sbordet** [comment]
@nathklei I'm actually going the way of always calling the callback, possibly with a synthetic message that is not received by the server but generated locally -- should be fairly trivial.

Do you see particular problems with this approach?

**Comment by sbordet** [comment]
@nathklei should be fixed by always calling the callback.

**Comment by nathklei** [comment]
Thanks @sbordet the fix you put in place looks good to me, and will make some of our application logic much simpler. I appreciate your turnaround on this!
