### ISSUE TITLE
5.x.x versions - lack of jar in Maven Central

### ISSUE THREAD

**Issue by mslowiak** [cometd/cometd#934]
There is a lack of jar for versions 5.x.x in Maven Central
https://repo1.maven.org/maven2/org/cometd/java/cometd-java-client/5.0.1/
https://mvnrepository.com/artifact/org.cometd.java/cometd-java-client/5.0.0/

**Comment by sbordet** [comment]
The jars are not missing, the artifact has changed.
Please follow the migration guide: https://docs.cometd.org/current/reference/#_migration_40_to_50.
