### ISSUE TITLE
Reload extension "startBatch() and endBatch() are not paired" on "reconnect: handshake" advice

### ISSUE THREAD

**Issue by quovide** [cometd/cometd#952]
We wrote an extension that gives a reconnect: handshake advice to re-authenticate the current user. In combination with the Reload extension this gives the following error:

11:53:43.920 Exception during execution of extension reload Calls to startBatch() and endBatch() are not paired

**Comment by quovide** [comment]
This commit fixes the issue for us: https://github.com/quovide/cometd/commit/dbf48bce5e0902833359d9d3f4e61b4626f0ed91

**Comment by sbordet** [comment]
Can you describe the case in more details?

Are you actually reloading or this happens just because the reload extension is registered and your `/meta/connect` contains `reconnect: handshake`?

What exact CometD version?

**Comment by quovide** [comment]
@sbordet Hopefully this explains our issue in more detail:

The message will occur when the page reloads and the first /meta/connect occurs.
We are using the reload extension so the handshake is stored in session local storage and is not issued to the server.
That's why we use the /meta/connect channel.
Our extension detects on /meta/connect that the current session is no longer valid and advices a reconnect: handshake.

You ask:
> Are you actually reloading or this happens just because the reload extension is registered and your /meta/connect contains reconnect: handshake?

It only happens on reload, not when a new /meta/connect occurs and the session is detected as invalid.

> What exact CometD version?

We are using 5.0.1

**Comment by sbordet** [comment]
Why are you using the reload extension, if upon reload you ask yo re-handshake?

**Comment by quovide** [comment]
@sbordet We like to keep the same session to store some state information and to combine with the Ack extension.

**Comment by quovide** [comment]
@sbordet Sorry, now I understand your question. For the majority of time the session has to be kept the same (Reload extension), but if the same browser changes user we have to switch sessions (advice, reconnect: handshake). 
Maybe another solution is to change the CometD URL when reloading with some contextual information in the query parameter

**Comment by sbordet** [comment]
I'll try to write a test case as non paired start/end batch should not happen -- from your description the application is not doing anything wrong to cause that.

**Comment by quovide** [comment]
@sbordet Ok, great. Sounds fine! Let me know if you have any further updates.
I searched the source for Message.RECONNECT_HANDSHAKE_VALUE and it's only used here (server side):

```java
    protected void unknownSession(Mutable reply) { 
        error(reply, "402::session_unknown"); 
        if (Channel.META_HANDSHAKE.equals(reply.getChannel()) || Channel.META_CONNECT.equals(reply.getChannel())) {
            Map<String, Object> advice = reply.getAdvice(true);
           advice.put(Message.RECONNECT_FIELD, Message.RECONNECT_HANDSHAKE_VALUE);
            advice.put(Message.INTERVAL_FIELD, 0L);
        }
    }
```

This is a **rare** case so I can imagine my issue isn't very common.

**Comment by quovide** [comment]
Works, I see you refined my solution with some fine grained details. Thanks!

**Comment by sbordet** [comment]
@quovide thanks for the feedback!
