### ISSUE TITLE
bump jetty to 9.4.34.v20201102

### ISSUE THREAD

**Issue by squiddle** [cometd/cometd#959]
There is a regression in jetty 9.4.33.v20201020 that got fixed in 9.4.34.v20201102.

https://github.com/eclipse/jetty.project/issues/5555

we just tried to upgrade to 5.0.2 using the recommended jetty version and instantly ran into the problem (in our case the default "jsp" servlet triggered this bug).

**Comment by sbordet** [comment]
You can typically run CometD 5.0.x with any version of Jetty 9.4.x greater or equal than the one used at the moment of the CometD release, so it would be enough for you to update Jetty and keep 5.0.2.

Having said that, I'll soon release 5.0.3 with updates to Jetty 9.4.35.

**Comment by squiddle** [comment]
ah i see. i missed the change in wording over time to now being just a default dependency. in very past versions of cometd there was a much tighter coupling. thanks for taking care, anyways.
