### ISSUE TITLE
Migrate to Jakarta APIs

### ISSUE THREAD

**Issue by boris-petrov** [cometd/cometd#974]
Jakarta EE 9 is out already along with stable versions of the two most popular containers - Tomcat 10 and Jetty 11. `cometd` internally still uses `javax` (e.g. [here](https://github.com/cometd/cometd/blob/5.0.2/cometd-java/cometd-java-server/cometd-java-server-websocket/cometd-java-server-websocket-common/src/main/java/org/cometd/server/websocket/common/AbstractBayeuxContext.java#L27)) so it is incompatible with an application that runs on these two containers. It would be nice to release a new version that is compatible with them. Unfortunately a single version cannot be made compatible with both the "old" `javax` and the "new" `jakarta` namespaces so perhaps a new major one should be released.

The migration is simple enough - just depend on the new artifact versions and rename the imports from `javax.*` to `jakarta.*`.

**Comment by sbordet** [comment]
@boris-petrov this has already been done in branch `7.0.x`. Stay tuned, I need to fix a few bugs in `5.0.x` and port them forward, then I will release CometD 6.0.0 (based on Jetty 10) and 7.0.0 (based on Jetty 11).
