### ISSUE TITLE
Support clients that send JSON object

### ISSUE THREAD

**Issue by sbordet** [cometd/cometd#975]
The Bayeux Protocol specifies that Bayeux messages should be encoded in a JSON array.
However, older clients may still send a single Bayeux message as a single JSON object, not wrapped in an array.

The CometD server used to support single JSON objects because it was wrapping them via e.g. `JettyJSONContext.adapt()`.
However, with the new async JSON parser this wrapping is not done, and should be restored for backwards compatibility.

**Comment by rododin** [comment]
👍 Thank you, Simone!
