### ISSUE TITLE
WebSocketTransport.Factory does not add WebSocketContainer as a bean

### ISSUE THREAD

**Issue by sbordet** [cometd/cometd#981]
In the client transport `WebSocketTransport.Factory` does not add `WebSocketContainer` as a bean, which does not stop the `WebSocketContainer` implementation possibly causing eclipse/jetty.project#5832.

**Comment by lachlan-roberts** [comment]
@sbordet I don't think your commit for this made it to the `6.0.x` branch. But I don't think it would work anyway.
see https://github.com/eclipse/jetty.project/issues/5832#issuecomment-749323551.
