### ISSUE TITLE
Client-side check for max size of output messages

### ISSUE THREAD

**Issue by sbordet** [cometd/cometd#986]
In particular for the WebSocket transport, the client should perform message size checks so that it does not exceed the message size when sending messages.

This is currently implemented but only on the receiving side.

**Comment by rameshmurthy** [comment]
Does it need to consider if permessage-deflate extension is enabled or not. I mean the size of the message from the client needs to consider if compression is enabled, If so, the size of the message post compression needs to be taken into consideration vs before compression the size of the message.

**Comment by sbordet** [comment]
No, it will not consider compressed size, only uncompressed size.
